### ISSUE TITLE
Send whisper only if CTRL is held when copying whisper text.

### ISSUE THREAD

**Issue by XScorpion2** [C1rdec/Poe-Lurker#100]
**Is your feature request related to a problem? Please describe.**
Frequently when I copy a whisper I am not ready to send it, PoE Lurker sends it anyways. I need a way to control when I want Lurker to auto send vs not when I copy a whisper string.

**Describe the solution you'd like**
Lurker should check the status of the CTRL key and if it is held down then send it.

**Describe alternatives you've considered**
Alt? Win?

**Additional context**
Similar to how PoE Trades Companion works.

**Comment by C1rdec** [comment]
Yeah I'll think of something to disable the feature temporally.

**Comment by C1rdec** [comment]
In 1.5.10 holding `Left Shift` while clicking on the whisper button on trade site will stop Poe Lurker from sending to Poe.
