### ISSUE TITLE
[Request] Auto-Update

### ISSUE THREAD

**Issue by livejamie** [C1rdec/Poe-Lurker#101]
It would be nice if when I click update in the system tray the next version of the app would download and install on its own.

Currently, it just opens the github project in a web browser and I have to do that all manually.

**Comment by C1rdec** [comment]
Mm no the apo should b updated

**Comment by C1rdec** [comment]
I will close this issue.

**Comment by livejamie** [comment]
I'm requesting a feature where the app updates itself.

Like this:
![image](https://user-images.githubusercontent.com/49513/78279932-22d93780-74cd-11ea-9761-d6e17b19643e.png)

You click the button and a window pops up downloads and installs the update automatically in the background.

Poe Lurker sends you to Github to install it manually.

**Comment by C1rdec** [comment]
No the app is updated
