### ISSUE TITLE
Add process

### ISSUE THREAD

**Issue by s-john-cm** [C1rdec/Poe-Lurker#102]
Hi 
In poe korea version
PathOfExile_x64_KG.exe = 64bit
PathOfExile_KG.exe = 32bit

thanks for great app

**Comment by C1rdec** [comment]
I can add them but Poe Lurker wont work since korea client are not writing in the Client.txt

**Comment by C1rdec** [comment]
in 1.5.9

**Comment by s-john-cm** [comment]
I tested But, Not work in korea client
The problem is that the file name is different

Korea client are writing KakaoClient.txt instead of client.txt

ClientLurker.cs
`private static readonly string ClientLogFileName = "Client.txt";`

If ClientLogFileName add, work?

**Comment by C1rdec** [comment]
Like I said your client is not writing any chat log...
