### ISSUE TITLE
app stops working after 1st click

### ISSUE THREAD

**Issue by nengoxx** [C1rdec/Poe-Lurker#103]
Hi, I found some issues when using the app, when someone whispers and I click for the first time it works(invites the other person) most of the time but sometimes it doesn't tho the color of the icon changes as it should, usually it seems that the game loses focus for a second then comes back to focus. The second time, when it should start the trade, it doesn't work and neither does the stash highlight. I tried the debug option and when I click the green areas that show, the game loses focus just as before, I'm running in windowed fullscreen and when it does lose focus it appears to show the windows taskbar with the game in the back. I'm also using poe-overlay so I thought that might be the issue but I read many people are using both overlay+lurker without any issues.

I attached the log file in case it helps, I saw some errors there.

[2020-04-02.log](https://github.com/C1rdec/Poe-Lurker/files/4420566/2020-04-02.log)

**Comment by C1rdec** [comment]
You might have 2 poe lurker running

**Comment by nengoxx** [comment]
I don't think that was it, didn't open it twice and there was only one icon in the tray, also it happened after closing everything(poe included) and relaunching it again

**Comment by C1rdec** [comment]
Can we setup a discord call ?

**Comment by C1rdec** [comment]
Any news for this issue?

**Comment by C1rdec** [comment]
I'll close this for now
