### ISSUE TITLE
Clear chat box before sending trade request

### ISSUE THREAD

**Issue by DSCriErr** [C1rdec/Poe-Lurker#104]
When clicking copy on trade site, it goes to Poe window and pastes message, if there was something in chat, it just adds to it.

**Comment by C1rdec** [comment]
There's no way to detect that... I would need to perform a Enter + Ctrl/A and delete everytime and if the chat is already open this wont work... So i think this is the user responsability to make sure there's no text in the chat.

**Comment by C1rdec** [comment]
I found a simple solution

**Comment by C1rdec** [comment]
I was already doing what I was thinking... The issue is that you have the chat open when you pastes new messages and there's nothing we can do here...
