### ISSUE TITLE
Mouse stuttering on startup

### ISSUE THREAD

**Issue by chromaticred** [C1rdec/Poe-Lurker#106]
The mouse jitters and I cannot control it until the GFL advertisement runs its course. Similar lock ups sometimes happen when removing a trading partner and whispering 'Thanks' successively via the app.

**Comment by Patton-Luke1996** [comment]
I'm experiencing the same issues. I find that during the logo display, my CPU is shooting up to approx 60% - 70% usage, coming from approx 10% usage even with several programs running in the background (I have a Ryzen 7 2700x for reference). 

After the logo dissapears, Lurker can still crash if you end up messing with settings if it hasn't been reopened fresh along with poe. I've also experienced the lockup when responding to the trading partner outlined above.

**Comment by C1rdec** [comment]
Those issue are not related to the GFL logo I'm already on it.

**Comment by C1rdec** [comment]
Those are cause by a third party package that I'm trying to replace.

**Comment by C1rdec** [comment]
While waiting for the process hook I'll make that if you don't use the Item Lurker the Global mouse wont be enable.
Without the Global Mouse Hook the mouse shuttering should stop.

**Comment by C1rdec** [comment]
fixed in 1.5.11
