### ISSUE TITLE
Allow us to reinvite

### ISSUE THREAD

**Issue by Asymat** [C1rdec/Poe-Lurker#110]
Dunno how to do that elegantly but sometimes people quit party and it's a pain to re-invite.

**Comment by C1rdec** [comment]
Yeah let me know your ideas :)

**Comment by Asymat** [comment]
I found the solution: Clicking a trade should do both: Invite AND trade. OK, you'll get poe message than you allready invited but who cares.

It also solves another things: say you'r in town when you invite then go to hideout AFTER buyer came, you don't need to double click (to fake invite then trade).

**Comment by C1rdec** [comment]
Smart I'll play with that

**Comment by Asymat** [comment]
Wait there is some caveats.

Out of my mind:
* People leave party but still wait for trade in your ho. => gonna re-invite them in party
* ...

Not enough to still want this feature imo. Plus it's easier: one click to rule them all!

**Comment by C1rdec** [comment]
I wont be able to do the double actions for 1 button since this is not legal for GGG

**Comment by C1rdec** [comment]
in 1.5.14 (Hold down for 500ms to reinvite
