### ISSUE TITLE
Nothing happens.

### ISSUE THREAD

**Issue by JamesASW** [C1rdec/Poe-Lurker#112]
Poelurker is running, nut doesn't not show anything.

I did find the log which contains an error message:
[2020-04-09.log](https://github.com/C1rdec/Poe-Lurker/files/4454225/2020-04-09.log)

**Comment by thatguy692** [comment]
same problem here, just launched the app noting happened, launched it again and got "another instance is running" message.
Can't find the running process though..

**Comment by C1rdec** [comment]
@JamesASW I will need to connect with you on Discord
@thatguy692 Can you provide your log

**Comment by C1rdec** [comment]
Discord: https://discord.gg/jYujrJ 

My username is **Cedrico**

**Comment by C1rdec** [comment]
I'll close this issue since the issue is to broad and no information is provided.
