### ISSUE TITLE
Addon not always picking up the fact that item has been sold

### ISSUE THREAD

**Issue by Th4n** [C1rdec/Poe-Lurker#114]
It seems like addon is not always picking up the fact, that item has already been sold. I'm not sure how this check is implemented to suggest something reasonable, but as a temporary solution, I'd propose a third action on a trade button, sending proper message (perhaps on right side, below dimiss action?).

Maybe action marking item as sold, would also be usefull?

**Comment by C1rdec** [comment]
The tool is traking your last 5 offers why would you need another button?

**Comment by Th4n** [comment]
Apologize then, somehow I missed Cheat Sheet section and didn't know about key shortcuts (I'm justused to readme having all necessary info in one page rather than splitted (: ). Might be worth adding it directly to readme section.

**Comment by C1rdec** [comment]
It wad like that and it was cumbersome. But I curious regarding the item not being flagged as sold. Do you remember what was the items?

**Comment by Th4n** [comment]
Happened to me multiple times and it's pretty frequent issue. Seems like to not depend on an item (happened to Simulacrum, gems, armor/weapons,etc). It might be however related to multiple trade request being sent at the same time, (A,B,C sends rq, you sell item to one of those, then D,E,F arrives and but the fact that item is already sold hasn't been acknowledged.

**Comment by Th4n** [comment]
Btw, have anybody ever complained about addon not pickup up certain actions? For example issue I'm also having pretty frequently is trade request that are not recognized by addon (even though the pattern seem ok on the first glance). It might be a different trading page tough, and different regexp.

For example:
![image](https://user-images.githubusercontent.com/5339311/78994654-e8147680-7b40-11ea-88fe-5fcbcf91273e.png)
Maybe issue I mentioned preuviosly and this one are connected and tied to POE->lurker communication?

**Comment by C1rdec** [comment]
Map and currency will never be marked as sold since those can be bought in bulk
