### ISSUE TITLE
Rare maps doesn't highlight in map tab

### ISSUE THREAD

**Issue by Asymat** [C1rdec/Poe-Lurker#115]
Ex: Forbidden Roost Arachnid Nest Map

|  | Highlight only the one map in regular tab | Highlight at least all map bases in regular tab | Highlight map base in map tab | Highlight only the one map in map base tab |
| --- | --- | --- | --- | --- |
| Keep full name (currently) | Y | N | N | Y |
| Remove rare name | N | Y | Y | N |
| Ideal solution | Y | N | Y | Y |

Not found the ideal solution here but maybe someone smarter will. ;)
Maybe there's a way to detect if map stash?

**Comment by C1rdec** [comment]
There is no way to know the Stash tab type... I'll try to parse the map name.

**Comment by Asymat** [comment]
Same with magic maps too.

Ex: Dark Forest of Bloodlines

**Comment by C1rdec** [comment]
Yeah it's the same story affix name needs to be removed

**Comment by C1rdec** [comment]
After investigation map with affixes are being highlighted in Stash tab and regular map

**Comment by Asymat** [comment]
They are highlighted in map base tab but the map base type is not highlighted in tier tab. and the tier type is also not highlighted.
