### ISSUE TITLE
Color of Stash Tab

### ISSUE THREAD

**Issue by idecibel** [C1rdec/Poe-Lurker#116]
Hello,
Just downloaded this and it's great, thank you!
As far as I can see I can't find anywhere to change the text color, specifically the text color over your HP bar that indicates the stash tab you need to go to.

I'm playing CI, and with White text on ES white background I usually only see the ~... and I use multiple so I have to recheck the message on what tab to go to.

Can we set this to a non conflicting color like blue/black or get the options to change it?

Thanks!

**Comment by C1rdec** [comment]
Good point I'll add an option :)

**Comment by C1rdec** [comment]
In 1,5,16
