### ISSUE TITLE
If I have listed a stack of things but only sell part of it all buyers afterwards have the "shopping cart" icon in the ui

### ISSUE THREAD

**Issue by Xebtria** [C1rdec/Poe-Lurker#117]
If I have listed a stack of things but only sell part of it all buyers afterwards have the "shopping cart" icon in the ui
Which means, I cannot invite them anymore via the tool because it only sends the "sold" message instead of the invite on left click

**Comment by C1rdec** [comment]
And what is the item type?

**Comment by Xebtria** [comment]
In that case it was a divination card, but I could bet it happens with others (currency, breachstones, whatever) as well

**Comment by C1rdec** [comment]
I will remove all the items that are currencies

**Comment by idecibel** [comment]
How does it work exactly, it looks on item name to determine if an item is sold or not, or item name + location?

If so the splitting them up in the sales tab seems less intrusive than removing the currencies?

**Comment by C1rdec** [comment]
Bassicaly I only have the information from the trade message soo ya the Item name and position. 

Regarding "removing them" I will not ignore trades from currencies but the program will by pass the sold state for all the currency item (currency, card, shard, breatch stone, fossils) and maps

**Comment by C1rdec** [comment]
Fixed in 1.5.16
