### ISSUE TITLE
The clickable elements of lurker are on top of even windows, preventing going into the menu/options

### ISSUE THREAD

**Issue by Xebtria** [C1rdec/Poe-Lurker#119]
The (half-) circles (and maybe the rest of the elements as well, but for them it is the most prominent) of the Lurker UI are almost always topmost. While this is intended I believe in order to make them clickable during gameplay, it is annoying at best when I want to do anything on the systray-rightclick-menu (like going into the settings).

it's a weird and complicated thing to reproduce, but this is what I usually have to go through

### so what I usally do is this:
1) press windows button to bring the task bar in front of the game
![](https://i.imgur.com/4XT45t0.png)
2) click the little arrow (because the lurker item is not shown by default, it is "hidden" behind that little arrow with the rest of the systray icons)
![](https://i.imgur.com/W2S4UDu.png)
Note: for now I can still click the systray icon for lurker without a problem, I could also select any of the other icons in my systray and do anything I want with them, and also go right click menus on them, lurker does not affect anything there.
3) Now I right click the lurker icon to bring up the menu
![](https://i.imgur.com/NoXZVFD.png)
Note 1: As you can already see, the menu item is not highlighted by the cursor, so if I click now, it clicks the circle item which brings up the dashboard, because now at this point for whatever reason the clickable circles or any ui elements for that matter are top most over everything.
Note 2: it also means if that menu is closing (sometimes it closes by itself, I do not know why), that I cannot do anything on anything in that systray, because that clickable circle is top most as I mentioned. 
4) I am rather lucky with the position of poe lurker in the systray in my case, because there is like one pixel where I can click the icon again, because this pixel is outside of the circle area
![](https://i.imgur.com/u1ykKwn.png)
![](https://i.imgur.com/1PGFzc3.png)
Note: As you can see, in the middle of the lurker systray icon, the mouse curser is the hand icon (which is the case for every other icon in my systray as well), and if I would click it again it would click the circle and show the dashboard. But right in the corner I can select the icon again.
5) and if I would do that it would open the right click menu again:
![](https://i.imgur.com/uxJATHJ.png)
Finale Note: And as you can see if I do that in that case, the menu items are highlighted and I can again e.g. go into the options.

Consindering my screenshot tool closes all menus, taskbars etc each time I make a screenshot, the fact that I could make all those screenshots should be a fairly good indicator that this is perfectly reproducible for me. 😛 

Please note this does not only happen on the right side for the mana circle (which I guess would make it a Pro-only-problem), but it does also happen on the health (half-) circle, if I for whatever reason have the taskbar on the left side of the screen. the mana circle is affected when the task bar is either bottom or right, and if I have the task bar on the top of the screen, this is not a problem at all because there are no lurker UI elements on the top of the screen.

While the whole thing is not really affecting any functionality, it is rather annoying and maybe some poeple do not have as much luck with the position of poe lurker in their systray.

**Comment by C1rdec** [comment]
Yeah the problem here is that when you right click Poe Lurker is set to the foreground process and all the overlays  are shown. I did send a message to hide overlays for 10s when you right click on the system tray but I guess there's a race between the message and the foreground change. I'll mess aroubd with it. Thanks

**Comment by C1rdec** [comment]
You can double click the system tray icon to open settings ;) 

For now this will patch your issue regarding have problem opening the settings window

**Comment by C1rdec** [comment]
Fixed will be in the next release

**Comment by C1rdec** [comment]
Fixed in 1.5.16
