### ISSUE TITLE
Items Listed for GCP Don't Work Correctly

### ISSUE THREAD

**Issue by WhiteSammy** [C1rdec/Poe-Lurker#122]
**Describe the bug**
GCP Icon doesn't show in sale box it's completely blank, doesn't work with the search function, and breaks the reply options.

**To Reproduce**
Try to sell something for a GCP.

**Expected behavior**
It to work like the other currencies.

**Please complete the following information:**
Last confirmed with 1.15.14 but it's been like this for as long as I've used the program.
No logs as I just installed the current release.

**Comment by C1rdec** [comment]
On it

**Comment by C1rdec** [comment]
Yeah GCP are not parsed but all other action are working fine for me

**Comment by WhiteSammy** [comment]
The only one that bugs out is the "are you still interested" function.

**Comment by C1rdec** [comment]
in 1.5.18
