### ISSUE TITLE
Question about Chat , open with other Key .

### ISSUE THREAD

**Issue by BBigL** [C1rdec/Poe-Lurker#123]
The Tool works very well with standart key from POE.  I am lefthanded player (mouse ist in the lefthand) and i play NumBlock. The problem is, i use Num-Enter for FlameDash or Shieldgrage.  Is the Binding in POE standart you will DIE in HC, why is that , you open the chat with NUM-Enter ! 

Solution a key binding the allows a other key, so that  PoeLurker nows, which Key opens the Chat. Chat close is Enter, even if Enter can't open the chat, because it has been bind to a other key.

i try Tools like sharpKeys, the key chang works great but PoeLurker not so well. my only hope is that i can tell POELurker which Key opens my chat.

All sales tools use ENTER to bring the commands into the chat. Maybe I'll get lucky someday and someone will bring a key mapping for the chat. 

best regards 
MMotzen

**Comment by C1rdec** [comment]
Poe lurker is not using the Numkey... I dont understand your issue

**Comment by BBigL** [comment]
Enter and Num_Enter share the same Key_value. I open the Chat with an other Key. But PoE_Lurker use Enter to open the Chat and send commands, am i right ? and sorry for bad english. 

best regards
MMotzen

**Comment by C1rdec** [comment]
Yes and you are sayingthat it should use num key?

**Comment by C1rdec** [comment]
Can we connect on discord?

**Comment by BBigL** [comment]
sure we can meet at Discord. i need a time 

best regrds
MMotzen

**Comment by C1rdec** [comment]
https://discordapp.com/invite/hQERv7K

Send a DM when you are free I'm **Cedrico**
