### ISSUE TITLE
highlighting doesn't work (win7)

### ISSUE THREAD

**Issue by divinitaz** [C1rdec/Poe-Lurker#124]
haven't updated in a while, so i can't tell when the bug exactly was introduced.
if i accept a trade and invite the person, the item is shown at the globe as intended.
if i open the stash and click on the text it only opens chat and inputs nothing.. it seems like it only presses F and not control-f since if i click into the search field myself and hit the text afterwards it types the name with an F in front of the name.

version: v1.5.16
os: win7

**Comment by C1rdec** [comment]
Can we connect on discord?

**Comment by C1rdec** [comment]
And what are you doing on win7 :P

**Comment by divinitaz** [comment]
i am old! win7 is old! :P discord: divinitas#8649

**Comment by divinitaz** [comment]
seems like time to update my os.. since poe-overlay is also causing problems

**Comment by divinitaz** [comment]
thanks again, great support :) all fixed :+1:

**Comment by C1rdec** [comment]
Check your discord ;)
