### ISSUE TITLE
Overlays misplaced

### ISSUE THREAD

**Issue by 1012-sp** [C1rdec/Poe-Lurker#125]
**Describe the bug**
It works fine 8/10 times, but when I come back after being AFK, I noticed that POELurker stops functioning.  This happens every time I come back from being AFK. Not once have I gone AFK and came back to POELurker notifications as I had hoped. Changing to full-screen and back to windowed full-screen does not seem to fix the issue. Restarting the app also does not seem to fix this issue. Restarting the client also does not seem to fix the issue. However, it comes back and starts functioning whenever it wants to. From my experience, this can be anywhere from 5 minutes to 2 hours. Also, I use the POELurker app with notification sounds on, and when the app stops functioning correctly, I can still hear the notification noise but I do not see the normal trade box that I can click on.

**To Reproduce**
Go AFK while the game is running on windowed full-screen.
**Expected behavior**
I expected the app to keep functioning while I am AFK. I also expected to see all the unfulfilled trade notifications, but I did not because the app stops functioning while AFK.

**Screenshots**
![POElurker bug ss](https://user-images.githubusercontent.com/60894188/79298969-8bde8900-7e97-11ea-990c-b7467794ce51.jpg)
This screenshot was taken right after the latest trade request. As you can see, the box to invite the player is missing.

**Please complete the following [information:**](url)
 - Version v1.5.17
 - Provide Log (C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs)
 There is no "logs" file or folder in my "app-1.5.17" folder.
**Additional context**
Another thing that I would like to add is that there is no support for trade requests from users in other languages. I have only experienced this with Russian and Korean, but when they request trades, the app does not work how it is intended. I do not get the notifications when the users are named in other languages.

**Comment by C1rdec** [comment]
Korean trades cannot be supported #4
But regarding the afk issue I'll try to reproduce the issue

**Comment by 1012-sp** [comment]
Hi, thanks for the reply. I'm hoping more information will be helpful! 5 mins ago, I just updated POE to 3.10.1d. The first trade after I logged in gave me the exact same issue. Got the audio notification, but no interface to click on. Thanks.

**Comment by C1rdec** [comment]
If you enable debug mode can you see green boxes? 

![image](https://user-images.githubusercontent.com/5436436/79304140-982a0c80-7ebe-11ea-980d-ac6f5490d5de.png)

**Comment by 1012-sp** [comment]
![Untitled](https://user-images.githubusercontent.com/60894188/79305475-4fffef80-7ea8-11ea-8a38-5d188c322b2d.png)

![Untitled1](https://user-images.githubusercontent.com/60894188/79305520-65751980-7ea8-11ea-9677-42547b5824e4.png)
 Took 2 screenshots, one with the task bar on top, and one without. I cannot see the green boxes with debug mode on. I am also using POE overlay, just in case that is what's causing the issue. Hope this helps.

**Comment by 1012-sp** [comment]
Restarted client just after posting the last post, and I see the green boxes. POE Overlay still active. 
![Untitled3](https://user-images.githubusercontent.com/60894188/79305806-eaf8c980-7ea8-11ea-81d8-7b78f0199b08.png)
Thanks.

**Comment by C1rdec** [comment]
So you can see the offer?

**Comment by 1012-sp** [comment]
I did some more testing last night... I found out that when I only get the audio queue and not the visual queue, I can see the visual interface right under the settings box which I am able to interact with. It seems "attached" to the settings box ( it moves with the box when I move the box). While this was happening and with debug mode active, I was also able to see the green boxes attached to the settings box, almost like it thought that the settings box was the POE client. I will try to reproduce the issue and post some screenshots if necessary.

**Comment by C1rdec** [comment]
What's the settings box?

**Comment by 1012-sp** [comment]
The box that pops up when you right click the app and click settings. My screen resolution is 2560 * 1440.

**Comment by C1rdec** [comment]
Moving the settings moved the overlays?!

**Comment by 1012-sp** [comment]
So when I tabbed out to the settings, I saw the green boxes and the visual box attached to it. The green overlay moved with the settings box.

**Comment by C1rdec** [comment]
Can we setup a discord screen share?

**Comment by 1012-sp** [comment]
Yes can I have your discord information

**Comment by C1rdec** [comment]
https://discord.gg/uRzn2f

**Comment by Blekota2k** [comment]
i can confirm that i experience the same issue. my ressolution is 1920x1080 and sometimes (didnt get that far to dinf out its when i go afk) i can hear the incomming trades but cant see any pop up overlays, restarting app doesnt fix it, restarting client doenst fix it, havent tryed restarting PC.

**Comment by C1rdec** [comment]
I might have a release contender for this issue. I'll put the fix in the next release and I will wait for you guys confirmation if you can reproduce the issue

**Comment by 1012-sp** [comment]
Hello, same issue confirmed in 1.5.18. 
![5 18 issue](https://user-images.githubusercontent.com/60894188/79675379-34dbfb00-819a-11ea-8651-e3dbb6b84767.jpg)

Restarting lurker seemed to have fixed the issue however.

**Comment by Blekota2k** [comment]
still having the same issue, if i go AFK a then return or i close both poe and lurker and then start it again, i can hear lurkers sound of incomming trade but i cant see any overlay, restarting poe or lurker doesnt work, only restarting PC

**Comment by C1rdec** [comment]
Still trying to replicate the issue 😭😭
I'll give you guys a custom builds with additional logging.

**Comment by EThaNol2005** [comment]
Hey guys, something seems off.
First time install here, and it looks kind like this problem.
Yesterday after install i heard the sound but no ui(Debug Mode no green overlays)
Today it's started with green overlay but didn't recognize trades, i whispered myself so i can test all settings. After lurker restart no more green overlay or trade sound.
I did't found any logs in (AppData\Local\PoeLurker\app-1.5.20)
Configfile looks pretty empty for me. 
![IIpO1IwQRu](https://user-images.githubusercontent.com/6765072/80695020-96bf2d80-8ad5-11ea-8530-2e7271d1b890.jpg)

[PoeLurker.exe config - Kopie.txt](https://github.com/C1rdec/Poe-Lurker/files/4557393/PoeLurker.exe.config.-.Kopie.txt)

i installed steam and standalone, how the program know where are my poe logfiles if not in default place?

**Comment by C1rdec** [comment]
Poe Lurker locate the exe path to find the client.txt

Did you try the always visible option?

**Comment by EThaNol2005** [comment]
Yes i did. i started it 5 min ago and the green overlay shows. i can click the healthbar for ho. But no sound/hud if a trade is incoming(no korean, my other tool got the trade).
hmm i turned the debug mode off and on but no more greenlayer..

**Comment by C1rdec** [comment]
Can we connect on discord

**Comment by C1rdec** [comment]
I fixed some issue regarding overlays positioning when Poe is Maximixe/Minimize let me know if the issue still occur.

**Comment by C1rdec** [comment]
Do you guys still experience the issue?

**Comment by C1rdec** [comment]
I'll close this for now.
