### ISSUE TITLE
Mobile Lurker

### ISSUE THREAD

**Issue by C1rdec** [C1rdec/Poe-Lurker#126]
As a user I want to be able to be notified when an offer comes in while AFK.

**Comment by JusKillmeQik** [comment]
Another tool uses Push Bullet to achieve this, which could be an easy way for your tool as well without actually writing a mobile app

**Comment by C1rdec** [comment]
I know, I do not like push bullet. 
The mobile app if pretty much done 8 just need to work on network stuff.
