### ISSUE TITLE
Add the option to highlight item using an overlay.

### ISSUE THREAD

**Issue by Atresia** [C1rdec/Poe-Lurker#127]
**Is your feature request related to a problem? Please describe.**
My Problem with the current way items are searched is that it takes ages to load and find the item if you have multiple quadstashtabs.

**Describe the solution you'd like**
A solution like for example Poe-Trade-Companion has is much faster and safes server workload. 
Its an overlay-grid (12x12 or 24x24) which represents the stashtab (normal or quad).
When you get a trade message the right position of the item will be shown. 
The version of Poe-Trade-Companion is a bit advanced as it detects the resolution of your gameclient automatically and therefore always shows the grid-overlay on the right position. 
The old tool named Mercury-Trade has a simpler solution. It lets you safe the position of the grid manually.

**Additional context**
Great Tool,
Keep up the good work sir!

**Comment by C1rdec** [comment]
I know those tools I might put this as an option I'll keep you updated here

**Comment by C1rdec** [comment]
Regarding the issue what the overlays will bring it to you? you still have to find the right tab...

**Comment by C1rdec** [comment]
I'll close this issue since there's no point having an overlay. The problem here is the multiple tabs with the same name but there's no way to find the right tab when the whisper comes in.

**Comment by TheOne320** [comment]
Scrolling through tabs is much faster with the overlay. The text search is not instant, so each tab switch the search has to first highlight the items in the tab before you can continue scrolling to the next. With the overlay you just have to watch the highlighted area and can quickly scroll through all tabs to find the item overlayed with the highlight area.

**Comment by C1rdec** [comment]
And the overlays will point you on wrong items...

**Comment by TheOne320** [comment]
Most people do not have the same item type at the exact same position in every tab.

**Comment by C1rdec** [comment]
To know the "item type" you would need to check the trade message and sometime the item type is not easy to guess. I think this will just add some confusion to a lot of users that I will need to deal with ;)

**Comment by C1rdec** [comment]
Furthermore, There's no way to know if its a regular or a quad tab...

**Comment by Atresia** [comment]
TheOne320 is completely right. The current feature of searching items is nearly useless to me and any other user with more than 3 quadtabs.
If you implement it in a clean way (desabled by default) no user should be confused and the stashtab/quadstash-problem can be solved by letting the user decide for either one.

**Comment by C1rdec** [comment]
Would you need both or the option could be to replace the current search feature with the overlays?

**Comment by C1rdec** [comment]
- 1e Click: Show the overlay.
- Next Clicks: swap from `Normal` to `Quad` tab

**Comment by Atresia** [comment]
> Would you need both or I can add an option in the settings that would replace the default behavior?

A checkbox in the settings to activate/deactive the overlay-feature and an option to choose between Normal- or  Quad-Overlay would be perfect. 
When the feature is active the overlay should pop up on pressing a hotkey or on clicking a button.
Of course it can just replace the default hightlighting feature or even do both but it would be really nice to have the possiblity to look for the item **before** you invite the person.

**Comment by C1rdec** [comment]
Alt+click on the offer to check the item

**Comment by Atresia** [comment]
> Alt+click on the offer to check the item.
> 
> Take a look at the cheatsheet

Missed that hotkey - thanks for your advice.

**Comment by C1rdec** [comment]
> feature or even do both 
Doing both will still have your issue
