### ISSUE TITLE
Chat File Selection

### ISSUE THREAD

**Issue by Craere** [C1rdec/Poe-Lurker#128]
**Is your feature request related to a problem? Please describe.**
Manual File selection for Chat Parsing

**Describe the solution you'd like**
Manual File selection for Chat Parsing

**Comment by C1rdec** [comment]
??

**Comment by Craere** [comment]
because of my system specifics the Program is not finding the chatlog file

**Comment by C1rdec** [comment]
And what is your specific system?

**Comment by C1rdec** [comment]
I'll close this issue for now since I don't have more information
