### ISSUE TITLE
Stop changing focus from game to another app by clicking on ui.

### ISSUE THREAD

**Issue by Vovchikan** [C1rdec/Poe-Lurker#129]
I just see image of updating icon on my mp bar, and click it, but nothing happens and image has disappered. Then i go to map, and when i start fighing with mobs, my browser suddenly opended your page on github and i died, because my browser was on full screen and focus was changed on browser.

Stop dooing things like that. Changing focus from game to another app.

Use hotkeys, for changing focus. And opening smth in another app.
.

**Comment by C1rdec** [comment]
The problems there is that you updated the tool and you did not wait for the completion

**Comment by Vovchikan** [comment]
The problem is me?) Or the problem is that i want to update? Or that after update suddenly focus of monitor was switched to browser? IMO, the program should can not switch focus, if user doesn't espect this behaviour.
