### ISSUE TITLE
Chat Scanner

### ISSUE THREAD

**Issue by Leoguy77** [C1rdec/Poe-Lurker#131]
Since i switched from Mercury to  PoE Lurker( i really like it btw. thanks for the great work), im really missing the chat-scanner. i really liked this feature and used it pretty often. I really would love to see it in PoE Lurker :)

**Comment by C1rdec** [comment]
Yes it's in my bucket list :) I'll keep you posted here.

**Comment by C1rdec** [comment]
Maybe something like that ?
`Match` will pop like incoming offer and you'll be able to set icon and the actions for the incoming match.

![image](https://user-images.githubusercontent.com/5436436/81302130-f3779680-9047-11ea-840a-8546489f8ace.png)

**Comment by Leoguy77** [comment]
i think it should be an extra window. showing it on the chat window will very quickly run through and you will no longer see the message.

**Comment by C1rdec** [comment]
This will be a fix overlay like the incoming trades

**Comment by Leoguy77** [comment]
ok. i like that :)

**Comment by Asymat** [comment]
I think this is out of your scope. I'd leave this to other projects that can focus entirely on that. (No need to reinvent the wheel but that's just my opinion).

I'm using https://github.com/Panaetius/PoETradeMonitor and it's allready working like a charm.
