### ISSUE TITLE
Delays during player invite and other chat initiated commands.

### ISSUE THREAD

**Issue by adldaz5184** [C1rdec/Poe-Lurker#132]
**Describe the bug**
There are seemingly random delays when sending party invites, whispers, trade request etc. The delay only persists for the first 1-3 characters, but it is something like 1-2 seconds per action.

**To Reproduce**
When a whisper comes in for an item, left click the button to invite to party. Some of the time it will invite immediately with barely a hint of a delay. Other times the chat dialog box will gain focus as if I pressed enter, then it will type \ [delay 1-2s] char1 [delay 1-2s] the rest of the characters of the players name for the invite.

This happens for all chat actions... whispers and even /kick commands.

This has like a 30-40% chance or working properly with no delays.

**Expected behavior**
Messages are sent without delay.

**Screenshots**

**Please complete the following information:**
All recent versions. I had no issues with early releases, cannot identify what the break point was.
version 1.5.23, 1.5.24

[2020-05-05.log](https://github.com/C1rdec/Poe-Lurker/files/4595945/2020-05-05.log)
[2020-05-07.log](https://github.com/C1rdec/Poe-Lurker/files/4595942/2020-05-07.log)

**Additional context**

**Comment by C1rdec** [comment]
This is weird because it's working on my side with no issue what so ever and I'm using it alot.

**Comment by adldaz5184** [comment]
Yes I believe i have a fringe case since it has never been brought up before. I'll first try a full uninstall/reinstall. I also run along side POE Overlay, but that is about it. I do have other antivirus software which normally runs. I'll see what I can do for white listing.

**Comment by adldaz5184** [comment]
[https://www.youtube.com/watch?v=fb2obf0CfgQ](url)

This is a video clip I made for one example. In the clip, I use the "hideout" overlay button in the left corner as the trigger. I used it 3 times in 3 different areas and one out of the three you can see the delay. Unfortunately the video capture makes it look like my client is lagging, but its smooth in reality.

I can try some other things as well, or enable more detailed debugging if possible.

Thanks

**Comment by C1rdec** [comment]
Yeah I think I know what's the problem I'll release a fix in 30m

**Comment by C1rdec** [comment]
1.5.25 should fix the issue.
