### ISSUE TITLE
After setting Thank You message, cheat sheet does not say how to send the Thank You message

### ISSUE THREAD

**Issue by Maldini999** [C1rdec/Poe-Lurker#133]
I see in the Settings panel how to set a Thank You message.  But I can't see in the Cheat Sheet how to send the Thank You message.

https://github.com/C1rdec/Poe-Lurker/blob/master/assets/CheatSheet.md

This is not a bug as much as just a question.

**Comment by C1rdec** [comment]
The thank you message will be sent automatically

**Comment by Maldini999** [comment]
I see that the Thank you message is sent when I am the seller, but it does not get sent when I am the buyer.

**Comment by C1rdec** [comment]
Yes

**Comment by Maldini999** [comment]
ahh, ok I did not realize that was the intended behavior.  Thank you for your prompt replies!
