### ISSUE TITLE
POE-Luker overlay not working.

### ISSUE THREAD

**Issue by itchi84** [C1rdec/Poe-Lurker#134]
**Describe the bug**
downloaded and used for a bit now the overlay is not working as it should. 

I'm not getting any icons pop up at all and cant see overlays in debug mode.

I'm on an ultrawide monitor would this affect the overlay?

think the app is still working otherwise,  I can jump on discord if you need.

**Comment by C1rdec** [comment]
Yes Discord would help me to find what's your issue is.
Can you try to enable debug mode in the settings and put PoE in Windowed mode.

Resize PoE smaller to see if you can see the green overlays

**Comment by itchi84** [comment]
If you can give me discord  details I can  jump on now and shere screen
too, ill get windows team viewer

**Comment by C1rdec** [comment]
Nah Discord will do can you try the steo I gave you and screen shot the overlays

**Comment by itchi84** [comment]
sorry I'm being special cant find discord link =*(

**Comment by itchi84** [comment]
I'm on now sorry was being special.

**Comment by itchi84** [comment]
so it was the scaling on systems that was making it go out of whack, once I put it back to 100% and rebooted it sorted it self out.
