### ISSUE TITLE
website whisper > POE doesn't work

### ISSUE THREAD

**Issue by Loftaris** [C1rdec/Poe-Lurker#135]
Haven't tested this on my desktop yet, so I'm only having this trouble on a laptop.

Windowed, Full Screen, 1920x1080
Chrome, not in full screen mode, stretched about 75% from the right towards the left, so POE is visible on the left 1/5th of my screen.

When I click "Whisper" on the www.pathofexile.com/trade website, it moves my mouse to the left side of the Chrome window, highlights the entire page, and ends up refreshing the trade search.  It doesn't bring POE into focus at all.

I do use other POE tools: DeadlyTrade, and LutTools which have keys bound to them, like F4, F7, and a few others, however I shut them off entirely, and the problem still persists; they work fine, even work with your tool running.

**Comment by C1rdec** [comment]
You should try a vanilla test (without any other tool running) because Poe Lurker is not moving the mouse... 

If you need help to find the problem we could connect on Discord.

**Comment by Loftaris** [comment]
I mentioned that I tried it without the tools running, it still doesn't work.

Quote: "and a few others, however I shut them off entirely, and the problem still persists;"

**Comment by Loftaris** [comment]
Loftaris#9161 on Discord

**Comment by C1rdec** [comment]
Poe Lurker discord => https://discord.com/invite/hQERv7K
