### ISSUE TITLE
lurker don't recognize some prices

### ISSUE THREAD

**Issue by Nikolaz81** [C1rdec/Poe-Lurker#136]
Lurker don't recognize some prices in incoming whispers:
1. Words: "chisel", "silver".
Examples:
` Hi, I would like to buy your Matua Tupuna Tarnished Spirit Shield listed for 2 chisel in Delirium (stash tab "~price 2 chisel"; position: left 19, top 5)`
`Hi, I would like to buy your The Plaguemaw I listed for 1 silver in Delirium (stash tab "~b/o 1 silver"; position: left 4, top 6)`
2. Prices with decimal separator ".". When i recieve wisper with price somthing like:
`Hi, I would like to buy your level 21 20% Volatile Dead listed for 1.1 exa in Delirium (stash tab "sale"; position: left 12, top 11)`
lurker cant recognize price.

**Comment by C1rdec** [comment]
The `.` is working for me but yeah those 2 currency types are missing

**Comment by tamaroth** [comment]
FYI: [here(on the right-hand side)](https://www.pathofexile.com/trade/about) is a list of all currency and item types supported by the trade API.

**Comment by C1rdec** [comment]
By locale settings I guess you mean the culture ?

**Comment by Nikolaz81** [comment]
@C1rdec 1.5.29
1 - Still don't work
2 - I found problem and solution. My regional decimal separator is "," but i play in english language, english separator is ".". Temporary i change separator in windows settings, but this is not correct solution. Maybe you make setup for separator in Lurker with options like system default and custom symbols?

**Comment by C1rdec** [comment]
Ueah sorry I'm busy with work... I'll make a build

**Comment by C1rdec** [comment]
Fixed in 1.6.1
