### ISSUE TITLE
Close button (bug)

### ISSUE THREAD

**Issue by igorcastroo** [C1rdec/Poe-Lurker#137]
This often happens to me, and there is no way to close this icon, so I have to close the application and open it again

![Sem título](https://user-images.githubusercontent.com/39240321/81864567-31425680-9543-11ea-8426-5eed02e07f97.png)

**Comment by igorcastroo** [comment]
a suggestion was to add a button or shortcut to close that icon

**Comment by C1rdec** [comment]
I already have a fix for that in dev. I'll to a build to night

**Comment by igorcastroo** [comment]
Sorry for asking,
any news? the error still persists here

![image](https://user-images.githubusercontent.com/39240321/82396194-b0dc9380-9a23-11ea-989f-ff101163f2df.png)

**Comment by C1rdec** [comment]
I though my fix would have work for that... 
Did you find the pattern to replicate the issue?

**Comment by igorcastroo** [comment]
simply send pm to someone to buy an item, then the person sends you to be part of the group (instead of you doing that), and complete the purchase and close the pm icon, which continues.

sorry for my bad English

**Comment by C1rdec** [comment]
Can you try to show me a video this scenario is working for me

**Comment by igorcastroo** [comment]
I managed to reproduce the error,

1. send pm and then click on the guy's nick
2.Click again without the person accepting the group
3. Then close by clicking on the red


1 - ![image](https://user-images.githubusercontent.com/39240321/82502601-e5a52500-9acd-11ea-84b4-d18437fe73f3.png)

2 - 
![image](https://user-images.githubusercontent.com/39240321/82502629-f2c21400-9acd-11ea-9969-e57dc2abc200.png)

3 - 
![image](https://user-images.githubusercontent.com/39240321/82502646-fa81b880-9acd-11ea-8e13-49269d2469ce.png)

4- 
![image](https://user-images.githubusercontent.com/39240321/82502657-ff466c80-9acd-11ea-937f-dd8366f5e535.png)

**Comment by C1rdec** [comment]
Fixed in 1.5.28
