### ISSUE TITLE
CTRL-F does not clear the clipboard after pasting the item.

### ISSUE THREAD

**Issue by tamaroth** [C1rdec/Poe-Lurker#141]
**Describe the bug**
When a CTRL+F is pressed when a cursor is over an item, the name of that item is copied and then pasted into the search box. However, the item is never removed from the clipboard.

**To Reproduce**
1. Hover over any item in-game in the stash.
2. Press CTRL-F.
3. The item will be highlighted.
4. Clear the search box manually.
5. Press CTRL-F while hovering over empty space.

**Expected behavior**
I expected the search box to be focused and waiting for the input, however, the previously copied item was automatically filled in. This is unwanted (or at least should be optional) since oftentimes when you search something again, you want a blank search box.

**Please complete the following information:**
 - Version 1.5.29

**Comment by C1rdec** [comment]
Ctrl+F doesn't add the item in the clipboard...

**Comment by C1rdec** [comment]
Ohh yeah right...

**Comment by C1rdec** [comment]
In 1.5.30
