### ISSUE TITLE
send whisper with party invite?

### ISSUE THREAD

**Issue by argash** [C1rdec/Poe-Lurker#142]
When sending the party invite it would be nice if it would also send a whisper to the trader letting them know that "{ItemName} for {Price]" is ready for pickup like POE Trade Companion does. 

This is particularly helpful when there is a delay between the initial trade message being received and when I actually exit my current map to make the trade.

**Comment by C1rdec** [comment]
I want to avoid to make multiple server actions. But I guess I could add a hotkey

**Comment by ShizuneHakamichi** [comment]
That would break GGG's ToU.

**Comment by C1rdec** [comment]
Yeah I know but an action like the "Still Interested" action would be ok but I'm not sure at this point is this is a feature that I want.
