### ISSUE TITLE
Doesn't work with Vulkan

### ISSUE THREAD

**Issue by lobo235** [C1rdec/Poe-Lurker#143]
Using version 1.5.29 it doesn't seem to work with the new Vulkan beta for PoE. Would be nice to get this fixed.

**Comment by C1rdec** [comment]
Yeah I know. I'm looking for an answer but even the discord overlay is not working 😭

**Comment by C1rdec** [comment]
For now I got it working by playing fullscreen and if you "alt-tab"  out and In you'll get it to work

**Comment by ShizuneHakamichi** [comment]
If you use WINDOWED mode EXCLUSIVELY (Windowed-Fullscreen, for Vulkan, is exactly the same as running IN Fullscreen) it'll work just fine.

**Comment by C1rdec** [comment]
Yeah for now there's nothing we can do. 

The work around for now is to run PoE in Windowed.
