### ISSUE TITLE
Non-English names causes trade overlay to not appear

### ISSUE THREAD

**Issue by weiyuan95** [C1rdec/Poe-Lurker#144]
**Describe the bug**
When a non-english username whispers for a trade, the overlay does not appear. Screenshot below

![image](https://user-images.githubusercontent.com/35588002/83329872-6cbc7f00-a2be-11ea-8569-56ead4722cb4.png)

When the korean user whispered me, the overlay did not show up. But when I found my own trade and whispered myself, the overlay popped up.

**To Reproduce**
1. Get a non-english username user to whisper with a trade
2. The overlay should not pop up

**Expected behavior**
The overlay should pop up across all usernames, especially those with special characters.

**Screenshots**
Screenshot above

**Please complete the following information:**
 - Version 1.5.29
- No logs available, I guess because no exceptions were thrown? No logs were created for today though (30th May)

**Additional context**
Using the new Vulkan renderer, but these issues were also happening with the DirectX11 one. Playing on windowed-fullscreen, 1280x768 res. It's also not a new problem, it has been happening from 1.5.26 at least, when I started using this.

Great tool btw! Really appreciate it 😬

**Comment by C1rdec** [comment]
Korean client are not logging in Client.txt it's a politic issue.

**Comment by C1rdec** [comment]
https://github.com/C1rdec/Poe-Lurker/issues/4#issuecomment-570510029

**Comment by weiyuan95** [comment]
Got it! Thanks for the (extremely) quick response. Stay safe!
