### ISSUE TITLE
Overlay disappear if toggle on/off V-Sync in-game

### ISSUE THREAD

**Issue by nomis51** [C1rdec/Poe-Lurker#147]
**Describe the bug**
The overlay disappear if I turn on/off V-Sync while in-game. The controls are still working, like the Hideout button is still showing the hand cursor on mouse hover and if I click on it, it works has intended. But, the UI is invisible.

If I check the Always visible option in the settings, the Hideout button appear, on my Windows desktop, but not in-game.

**To Reproduce**
1. Go in game, like in your hideout.
2. Open the Options menu
3. Toggle on or off V-Sync
4. Note that the Hideout button has disappear

**Expected behavior**
The UI should be visible even if I toggle v-sync on and off while gaming

**Please complete the following information:**
 - Version 1.5.30
- Wasn't able to find the log file

Vulkan is enabled aswell as the option in the settings of the app.
V-Sync was at first enabled.

**Comment by C1rdec** [comment]
Yeah making change to the option with Vulkan for now will reset the Issue regarding Vulkan. You'll need to Restart Poe.

**Comment by nomis51** [comment]
Restarting the Lurker, seems to be working. But, yeah, messing with Graphics settings seems to broke the UI with Vulkan.

**Comment by C1rdec** [comment]
Yeah for now there's not much we can do.
