### ISSUE TITLE
Micro-Stutter in-game

### ISSUE THREAD

**Issue by nomis51** [C1rdec/Poe-Lurker#148]
**Describe the bug**
There are some micro stutter while playing that are not showing on the in-game FPS watcher. The game is running smooth if the app is closed, and start having problem if the app is opened

**To Reproduce**
Just go in a map in-game.

**Expected behavior**
Should not affect the in-game experience

**Please complete the following information:**
 - Version 1.5.30

Vulkan is enabled.
V-Sync is enabled.

**Comment by C1rdec** [comment]
This is an issue with Vulkan for now there's nothing we can do. On my side everything is stable with Vulkan and VSync.
