### ISSUE TITLE
Can no longer highlight items in stash

### ISSUE THREAD

**Issue by KanskeD** [C1rdec/Poe-Lurker#149]
**Describe the bug**
Since v1.5.30 when a trade request comes in and I go to the tab and press the life orb it doesn't type out the item in the search box. I can see that the typing indicator quickly appears but then disappears and the chat box opens up with nothing typed in.

**Comment by C1rdec** [comment]
Working on my side I will need to connect with you.

**Comment by C1rdec** [comment]
I'll close this for now since no information is given.
