### ISSUE TITLE
Trade icon move from original position when using Vulcan Rendering with "Windows Mode"

### ISSUE THREAD

**Issue by pongsacha** [C1rdec/Poe-Lurker#150]
Trade icon move from original area to around middle of screen when using Vulcan Render with "Windows" (not windows borderless)

- Lastest Version of Poe Lurker
- Vulcan Render BETA
- Play in Window mode 1920*1080 but using Autohotkey Scipt to make Window mode become Window Borderless Mode download in this link https://www.reddit.com/r/pathofexile/comments/gseuoy/vulkan_test_technical_megathread/?utm_source=share&utm_medium=ios_app&utm_name=iossmf (first comment there link download "PoE Borderless script" script made by Poe Trading Companion dev)
- After getting trade offer the trade icon move a bit to middle of the screen but program is still usable just fine
- Also the hideout icon on the bottom left also move a bit just like trade icon

**Comment by C1rdec** [comment]
You should use the Vulkan option in Poe Lurker instead of the script.
