### ISSUE TITLE
Unintentionally steals focus from game

### ISSUE THREAD

**Issue by SnosMe** [C1rdec/Poe-Lurker#152]
**Describe the bug**

When PoE window is activated, PoE Lurker tries to show itself and steals focus from game.

**Screenshots**

![2020-06-09](https://user-images.githubusercontent.com/4292308/84088973-7a78af80-a9f6-11ea-99a7-c32b06330dc8.png)

**Please complete the following information:**
 - Version latest

**Additional context**

I think it can be fixed by setting `ShowActivated=false` prop. 
https://docs.microsoft.com/en-us/dotnet/api/system.windows.window.showactivated?view=netcore-3.1
https://stackoverflow.com/questions/1456529/how-to-prevent-a-new-wpf-form-from-stealing-focus

**Comment by C1rdec** [comment]
Are you using the Vulkan option?

**Comment by SnosMe** [comment]
No

**Comment by C1rdec** [comment]
What's the behaviour you are experiencing?
I'm not sure if I understand your issue.

Are not able to use the tool or you are just saying that the focus is given to Poe Lurker

**Comment by SnosMe** [comment]
Poe Lurker is playing against Windows foreground window rules.

When PoE Lurker's windows are shown (from hidden state) they are not meant to become foreground window(s).

Next version of Awakened PoE Trade depends on those events, and since the last SYS_FOREGROUND is triggered by Lurker, it keeps thinking that foreground window is not PoE.

Also want to say that this behavior seems like a UX improvement from Microsoft side. The PoE window is *actually* not losing focus, I think it is made to prevent from input interruption.
Anyway if window is not meant to become foreground on show it must be shown without activation (https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowpos#SWP_NOACTIVATE). 

Also I do have example of well behaved app: MercuryTrade.

![image](https://user-images.githubusercontent.com/4292308/84090801-67b4a980-a9fb-11ea-93de-0bccd0f93908.png)

Window is shown without activation.

**Comment by C1rdec** [comment]
Fixed in 1.6.3.
