### ISSUE TITLE
Functionality for outgoing trades?

### ISSUE THREAD

**Issue by DavidRehm** [C1rdec/Poe-Lurker#154]
Not sure if bug or feature request.

Is PoE-Lurker supposed to provide functionality for outgoing trades as well as incoming ones? For example after the 'auto whisper' (which does work), is it supposed to show an icon at the bottom with the price and that would serve as a button to go to their hideout or accept the party invite or trade invite?--mine doesn't seem to do anything after the 'auto whisper'.

 - Version 1.5.30

**Comment by C1rdec** [comment]
Working normally on my side.

![Outgoing](https://user-images.githubusercontent.com/5436436/84329625-2b945c80-ab53-11ea-9cba-e84cf8a889bb.gif)

**Comment by DavidRehm** [comment]
Huh. I don't get those buttons at all. I get the square incoming icons to the right of that, and the corresponding search functionality over the health globe, but nothing in that area ever. (I saw that in screenshots and thought maybe it was just a previous incarnation of the UI that had since changed.)

I am using the Steam version--is there any difference between the version on Steam and the standalone client?

**Comment by C1rdec** [comment]
You'll get the price when you'll click on the Incoming offer to join the seller hideout...
