### ISSUE TITLE
Poe Lurker Trade Icon Misplace with Vulcan Window mode + AHK Script to Borderless Fullscreen

### ISSUE THREAD

**Issue by pongsacha** [C1rdec/Poe-Lurker#155]
I have post this issue week ago with vulcan support turn on and its cause a trade icon to misplace and you didn't believe me.

how the issue happen
- 1920 * 1080 resolution screen 24" asus monitor 144hz
- Vulcan in game turn on
- Vulcan in Poe Lurker turn on
- PoE setting is "Windows Mode" not borderless one
- Using AHK Script from PoE Trade Companion Dev https://www.reddit.com/r/pathofexile/comments/gseuoy/vulkan_test_technical_megathread/?utm_source=share&utm_medium=ios_app&utm_name=iossmf to make Window mode become Window Borderless Mode
- PoE Lurker still work but icon move a little bit

![001](https://user-images.githubusercontent.com/65549606/84509827-7a2a2e00-acee-11ea-93b9-078f407ac932.jpg)
![002](https://user-images.githubusercontent.com/65549606/84509841-7eeee200-acee-11ea-887e-565e31845806.jpg)

p.s. Korean & Russia trading not function with Lurker if you can make that happen that would be great

**Comment by C1rdec** [comment]
Yes for now there's nothing we can do. 
But my question is why do you use both the script and the Vulkan option in Poe Lurker.

**Comment by pongsacha** [comment]
because using Vulcan in PoE and play with Windows Borderless cause screen to flicker. that's why people using that script to make game become fullscreen borderless without flicker.

and people didnt just use PoE Lurker alone they use other 3rd party too like poe overlay , awaken poe trade etc. those app can run on vulcan right now but it cannot show program on top of poe because when vulcan enable PoE will have priority to always on top of all the app.

**Comment by C1rdec** [comment]
The flikering issue is related to Vsync.

**Comment by pongsacha** [comment]
I have Vsync off in game and Nvidia control panel
