### ISSUE TITLE
Poe Lurker close himself upon starting

### ISSUE THREAD

**Issue by RomainCarpentier** [C1rdec/Poe-Lurker#157]
Hello,
I want to thank you for your program, it works wonderfully and it is really pleasant to use.

I had a little issue recently.
I'm used to launch PoE and several add-ons with a .bat file, nothing fancy, I had to look how to do it a few months ago. It was working fine until recently, but now Poe lurker stop right after being launched.

What happens : 
- I use the bat.file 
- everything launch 
- then Poe lurker close himself
- I launch Poe lurker again but directly with the executable
- Poe lurker launch and works fine

I don't know what could be the cause, I use the Vulkan version.

The .bat I use  : 

@echo off
start "Poe Overlay" "E:\Programmes\Grinding Gear Games\AddOn\Poe Overlay\poe-overlay.exe"
start "Poe Lurker" "E:\Programmes\Grinding Gear Games\AddOn\Poe Lurker\PoeLurker.exe"
CD /d "E:\Programmes\Grinding Gear Games\Path of Exile"
start PathOfExile_x64.exe

By the way, I use Poe Overlay only for the programmable command, the hideout icon is a nice feature but I would rather be able to use shortcut like this : 
![Capture](https://user-images.githubusercontent.com/45791186/84597409-32c5ae00-ae64-11ea-81be-bf49be9aa544.JPG)
(especially for the log-out and hideout macro)

Thank you again for your work.
Regards,
Romain

**Comment by C1rdec** [comment]
Do you have any logs?

**Comment by C1rdec** [comment]
And keep in mind that Poe Lurker will automatically start with Path of Exile.

**Comment by RomainCarpentier** [comment]
![image](https://user-images.githubusercontent.com/45791186/84904929-3a799280-b0b0-11ea-8522-b4f575caf3ac.png)
![image](https://user-images.githubusercontent.com/45791186/84905060-6e54b800-b0b0-11ea-95f6-4a88e51f0fe8.png)
![image](https://user-images.githubusercontent.com/45791186/84905114-8298b500-b0b0-11ea-87b2-27a4d54ce195.png)

These are the error logs, if they can be of any help. 
I don't start Poe Lurker on windows boot, so it doesn't automatically start when I launch Path of Exile. Or maybe it tries to and that conflict with my script launch ?

**Comment by C1rdec** [comment]
Get the log of Poe Lurker...

**Comment by C1rdec** [comment]
![image](https://user-images.githubusercontent.com/5436436/84905705-ffab3680-b07e-11ea-953f-2ab3bc487f41.png)

**Comment by RomainCarpentier** [comment]
[2020-06-12.log](https://github.com/C1rdec/Poe-Lurker/files/4792937/2020-06-12.log)
[2020-06-13.log](https://github.com/C1rdec/Poe-Lurker/files/4792939/2020-06-13.log)
[2020-06-14.log](https://github.com/C1rdec/Poe-Lurker/files/4792940/2020-06-14.log)
[2020-06-15.log](https://github.com/C1rdec/Poe-Lurker/files/4792941/2020-06-15.log)
[2020-06-16.log](https://github.com/C1rdec/Poe-Lurker/files/4792942/2020-06-16.log)
[2020-06-06.log](https://github.com/C1rdec/Poe-Lurker/files/4792943/2020-06-06.log)

It seems that the older logs are from about ten days ago

**Comment by C1rdec** [comment]
Try to start Poe Lurker after Path of Exile.

**Comment by RomainCarpentier** [comment]
I tried, with a 10sec delay, then a 60sec delay. 
It seems that the launch method isn't the issue because it works fine the second time with or without delay, but the first time after PC restart it don't work even with 60sec delay.

New log
[2020-06-17.log](https://github.com/C1rdec/Poe-Lurker/files/4793026/2020-06-17.log)

**Comment by C1rdec** [comment]
I've change process handling for the next release that might fix this issue

**Comment by RomainCarpentier** [comment]
Thank you, I'll give you a feedback after release.

**Comment by C1rdec** [comment]
Let me know if 1.6.3 fix your issue.

**Comment by RomainCarpentier** [comment]
The last update seems to effectively fix that issue. Thank you again !
