### ISSUE TITLE
Question: Item Highlight vs PoE TOS

### ISSUE THREAD

**Issue by hammypants** [C1rdec/Poe-Lurker#158]
My question is simple, how does the _item highlight_ feature not break PoE's TOS when it performs multiple keystrokes in one feature? Or it does and we simply don't care at this point in time?

**Comment by C1rdec** [comment]
The TOS is regarding server action. The big thing that GGG dont want are timers that check a state of the game to perform actions. Since the key strokes are perform really fast I'm pretty sure only one server action is made. But even if multiple server calls were made there's no worries.
