### ISSUE TITLE
Resend party invite

### ISSUE THREAD

**Issue by Murdoc84** [C1rdec/Poe-Lurker#159]
Great work with this tool!
I miss the opportunity to resend invitation to the party.

**Comment by C1rdec** [comment]
Long press the offer (500 ms)

**Comment by Murdoc84** [comment]
Thanks for fast answer, can't find this information on gif's :)

**Comment by C1rdec** [comment]
Take a long at the [Cheat Sheet](https://github.com/C1rdec/Poe-Lurker/blob/master/assets/CheatSheet.md).
