### ISSUE TITLE
Null pointer on items with no price?

### ISSUE THREAD

**Issue by kasiopec** [C1rdec/Poe-Lurker#16]
Had fossils up for sale without a price, lying in the delve tab. 
Guy messages me and app insta crashes. 

Logs show: 

2020-01-06 21:49:56.8439 ERROR Value cannot be null.
Parameter name: value
2020-01-06 22:01:48.7262 ERROR Value cannot be null.
Parameter name: value

**Comment by C1rdec** [comment]
Will try this out after work in about an hour.
Can you try to get the whisper out of Client.txt

**Comment by kasiopec** [comment]
2020/01/06 21:49:56 41387343 ac9 [INFO Client 3412] @From Marimo_Moss: Hi, I would like to buy your Jagged Fossil in Metamorph (stash tab "D"; position: left 4, top 1)
2020/01/06 21:50:00 41391031 ac9 [INFO Client 3412] @From Marimo_Moss: 1c offer each

2nd msg: 

2020/01/06 22:01:48 42099046 ac9 [INFO Client 3412] @From Loramendiz: Hi, I would like to buy your Bound Fossil in Metamorph (stash tab "D"; position: left 14, top 1)
2020/01/06 22:01:49 42099937 ac9 [INFO Client 3412] @From Loramendiz: 5cea

**Comment by C1rdec** [comment]
Its fixed i'm getting the new release up
