### ISSUE TITLE
Overlay work only in specific situation

### ISSUE THREAD

**Issue by Murdoc84** [C1rdec/Poe-Lurker#160]
Overlay only works if I start Lurker before running the game, in addition I need to run it as administrator. Otherwise, an eye icon will appear on the mana ball, but overlay does not work. Regardless of whether the overlay is visible or not, there is a Lurker icon in the system tray and its operation works properly.

1. Run PoE first
2. Run Lurker
or
1. Run Lurker first
2. Run PoE as normal user (not as administrator)

**Expected behavior**
Overlay should start regardless of whether the game or Lurker will be started first.

**Screenshots**
No screenshot because there is nothing to show.

**Please complete the following information:**
 - Version 1.5.30
 - Provide Log - sorry cannot find any log file or log folder in this directory, only .dll .exe. .config files and winook.support directory

**Comment by C1rdec** [comment]
Can you check the permission on the Foldet where Path of Exile is installed

**Comment by Murdoc84** [comment]
Yes, "everyone" have "full control"

**Comment by C1rdec** [comment]
I will need to connect with you on Discord to investigate further.
