### ISSUE TITLE
Add a hotkey to send a trade message, like in MercuryTrade

### ISSUE THREAD

**Issue by momocorpo** [C1rdec/Poe-Lurker#161]
**Is your feature request related to a problem? Please describe.**
A keybind like F2 that will paste the current trade message with a verification of it's content to avoid sending it twice, then it gives back the focus to the previous windows

**Describe the solution you'd like**
Its use case would be as such :
 - Go into any trade website
 - find a trade I want
 - Click on "whisper" or equivalent that copies a trade message to clipboard
 - press keybind
 - poe lurker writes the message in PoE and sends it
 - click on another "whisper" from another seller
 - press keybind
 - poe lurker writes the message in PoE and sends it
etc...

**Comment by C1rdec** [comment]
This is already implemented.
