### ISSUE TITLE
Click to Highlight Bugged?

### ISSUE THREAD

**Issue by livejamie** [C1rdec/Poe-Lurker#162]
Clicking the bottom of the orb to highlight the item you're trading doesn't seem to be working anymore. 

Thank you!

**Comment by C1rdec** [comment]
Working on my side can we connect on discord?

**Comment by livejamie** [comment]
After doing some investigation it seems like the new Poe Overlay Overwolf edition was blocking that functionality.

I can look for a different price checking tool if there isn't a way to get around it.

Lurker is much more important to me. :)

**Comment by C1rdec** [comment]
Take a look at the Community Edition of Poe Overlay 

https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork
