### ISSUE TITLE
Sound when buyer join my HD

### ISSUE THREAD

**Issue by Murdoc84** [C1rdec/Poe-Lurker#163]
Sound when buyer join my HD like in old fashion TradeCompanion ;)

**Comment by C1rdec** [comment]
Good idea !

**Comment by C1rdec** [comment]
Just to be sure by HD you mean Hide Out?

**Comment by Murdoc84** [comment]
Yes :)

**Comment by C1rdec** [comment]
Added in 1.6.3.

**Comment by Murdoc84** [comment]
Work great, thx :)
