### ISSUE TITLE
Buying improve

### ISSUE THREAD

**Issue by Murdoc84** [C1rdec/Poe-Lurker#164]
Automatically leave seller HD and party after successively buy item

**Comment by C1rdec** [comment]
This will break the TOS of GGG

**Comment by Murdoc84** [comment]
How?
just 2 chat commands:
/kick MyCharName (can be set in settings or collected from poe site)
/hideout
Nothing more than actual Lurker functions :)

**Comment by C1rdec** [comment]
Multiple server actions are made base on 1 actions technically the Auto Kick is not legal that's why there's an option in tje settinga

**Comment by Murdoc84** [comment]
Can you contact me on discord? :) MrOne#1676

**Comment by C1rdec** [comment]
Not for now... But I dont know what Discord will bring.

**Comment by Murdoc84** [comment]
How about add in:
\src\Lurker.UI\ViewModels\OutgoingbarViewModel.cs
in Lurker_TradeAccepted

`private void Lurker_TradeAccepted(object sender, Patreon.Events.TradeAcceptedEvent e)
        {
            if (this._activeOffer == null)
            {
                return;
            }

            if (!string.IsNullOrEmpty(this.SettingsService.ThankYouMessage))
            {
                var tradeEvent = this._activeOffer.Event;
                this._keyboardHelper.Whisper(tradeEvent.PlayerName, TokenHelper.ReplaceToken(this.SettingsService.ThankYouMessage, tradeEvent));
                // add
                this._keyboardHelper.Kick("MyNameFromConfig");
                this._keyboardHelper.JoinHideout();
            }

            this.InsertEvent(this._activeOffer.Event);
            this.RemoveOffer(this._activeOffer);
            this._activeOffer = null;
            this._removeActive = null;
        }`

and add in Settings field for MyName
is this break GGG TOS?

**Comment by C1rdec** [comment]
Yes like I told you multiplr server actiobs are made.
