### ISSUE TITLE
I have an issue with RCtrl.

### ISSUE THREAD

**Issue by Georgiimo** [C1rdec/Poe-Lurker#165]
On Discord I have RCtrl bound to mute/unmute my microphone and it seems that Poe Lurker uses RCtrl every time you click on the overlay buttons. Is there any way to make it not do this, or do I have to rebind my Discord mute/unmute?

**Comment by C1rdec** [comment]
Yeah for now hotkeys are not configurable but this will come.
LCtrl is supported in Poe Lurker.
