### ISSUE TITLE
Copy to clipboard trigger Error

### ISSUE THREAD

**Issue by Murdoc84** [C1rdec/Poe-Lurker#166]
**Describe the bug**
Sometimes when i copy to clipboard text that is not trade message i got .NET Framework Error

**To Reproduce**
1. Open PoeLurker
2. Copy something to clipboard that is not trade message
SPORADIC

**Expected behavior**
No error occurred

**Screenshots**
![image](https://user-images.githubusercontent.com/22428605/85317583-e101d100-b4be-11ea-9f6f-d2535d9a5adb.png)

**Please complete the following information:**
 - Version v1.6.2

**Comment by C1rdec** [comment]
yeah this is an issue regarding the library that I'm using for monitoring the Clipboard. 
Are you using remote Desktop ?

**Comment by Murdoc84** [comment]
You ask because need to connect to my PC or this may cause problem? 
No i don't use RDP, but i share mouse/keyboard/clipboard between two computers.

**Comment by C1rdec** [comment]
Will be in the next release when the SharpClipboard will be updated.

https://github.com/Willy-Kimura/SharpClipboard/issues/13

**Comment by Murdoc84** [comment]
About clipboard now i also have strange situation, sometimes i need to Ctrl+Click on https://www.pathofexile.com/trade few times to send trade request in game, most time 2-3 times. Will this new update also solve this problem or create new issue? :)

**Comment by C1rdec** [comment]
The trade should be sent to Poe without holding ctrl.

**Comment by C1rdec** [comment]
If you the trade is not sent to Poe can you share the whisper here.

**Comment by Murdoc84** [comment]
Old habit from the times of TradeCompanion :) I'll check it!

**Comment by C1rdec** [comment]
Basically Poe Lurker will do the opposite. 

While holding `left shift` the trade wont be sent to Poe.

**Comment by C1rdec** [comment]
Fixed in 1.6.3
