### ISSUE TITLE
Buttons render "under" POE window

### ISSUE THREAD

**Issue by Tripwyr** [C1rdec/Poe-Lurker#167]
**Describe the bug**
The buttons for incoming sales and outgoing buys appear to be rendering underneath the POE window. I am able to click on the buttons, at which point the screen flashes revealing the buttons and executing their commands, but otherwise during gameplay they are not visible.

**To Reproduce**
Launch POE
Launch Lurker
Receive trade message
No button appears, but if moused over the cursor changes
Click where the button should be, screen flashes and trade message is sent

**Expected behavior**
The button renders above POE so that we can see it

**Screenshots**
Unable to screenshot as taking a screenshot re-focuses the game

**Please complete the following information:**
 - Version 1.6.2
 - No logs exist in the folder, does this need to be enabled somewhere?

**Additional context**
I am using Vulkan in Fullscreen Windowed. It worked fine before the Vulkan compatibility mode was removed.

**Comment by Tripwyr** [comment]
Reinstalled and resolved.

**Comment by Tripwyr** [comment]
Issue re-occurred the next day.

**Comment by C1rdec** [comment]
Can we connect on discord so I can investigate further with you?

**Comment by Tripwyr** [comment]
Yep, send me a message at Tripwyr#0001

**Comment by C1rdec** [comment]
Duplicate : https://github.com/C1rdec/Poe-Lurker/issues/172
