### ISSUE TITLE
Dashboard Causing Crash

### ISSUE THREAD

**Issue by Jensocide** [C1rdec/Poe-Lurker#168]
Anytime I go to my hideout and click the dashboard the program crashes

**Comment by C1rdec** [comment]
Can you send me your Trade.db file located in :

"C:\Users\\[user]\AppData\Roaming\PoeLurker\Trades.db"

**Comment by Jensocide** [comment]
Sure

[Trades.zip](https://github.com/C1rdec/Poe-Lurker/files/4816757/Trades.zip)

**Comment by C1rdec** [comment]
Fixed in 1.6.3
