### ISSUE TITLE
Sell use item name instead of item place in stash

### ISSUE THREAD

**Issue by Murdoc84** [C1rdec/Poe-Lurker#169]
**Describe the bug**
When i have few same items to sell, and sell one of them then instead of get info about next trade got only chart icon 

**To Reproduce**
1. Have more items same name
2. Sell one
3. Got another buy offer for different item with same name

**Expected behavior**
Overlay show normal sell icon instead of chart icon

**Please complete the following information:**
 - Version 1.6.2

**Comment by C1rdec** [comment]
This is not true you should have sell the same item since poe lurkrr check the position of the item.

**Comment by Murdoc84** [comment]
ok, sorry :)
but in this case how long lurker think this item is sell? i ask because i flip few items and always put them in same place :)

**Comment by C1rdec** [comment]
Poe Lurker will remember your last 5 trades
