### ISSUE TITLE
"Dismiss incoming trade request" action doesn't give back the focus to the game

### ISSUE THREAD

**Issue by nomis51** [C1rdec/Poe-Lurker#170]
**Describe the bug**
The "Dismiss incoming trade request" button (little red triangle), doesn't give back the focus to the game when you click on it.

**To Reproduce**
1. Open Poe-Lurke
2. Open PoE
3. Wait for incoming trade request
4. Dismiss the trade request

**Expected behavior**
Should dismiss the offer and give back the focus to the game (like all the other actions)

**Please complete the following information:**
 - Version 1.6.2

**Additional context**
Other actions such as Party Invite, Sold message, Busy message, etc. are doing their job, then give back the focus to the game.
I'm using Vulkan, but I'm experiencing the same problem with DX11 aswell. So I guess it's not a Vulkan related issue.
I'm using [Awakened-PoE-Trade](https://github.com/SnosMe/awakened-poe-trade) at the same time if that make any difference.

**Comment by C1rdec** [comment]
Fixed in 1.6.3
