### ISSUE TITLE
Trade requests missed

### ISSUE THREAD

**Issue by nomis51** [C1rdec/Poe-Lurker#171]
**Describe the bug**
Seems like the app is missing some incoming trade requests from time to time. I've noticed that multiple incoming requests back to back seems to be to fast or something. But, sometimes a single request alone can be missed by the app. I wasn't able to find any constant scenario for that.

Outgoing requests with non-english/french/spanish (such as russian, korean, etc.) aren't tracked correctly sometimes (happens a lot for me)

**To Reproduce**
1. Open lurker
2. Open PoE 
3. Wait for multiple incoming requests

1. Open Lurker
2. Open PoE
3. Send a russian/korean/etc. trade request whisper

**Expected behavior**
Should catch and queue all incoming/outgoing requests, even non-english/french/spanish ones, with maybe a built-in translator.

**Please complete the following information:**
 - Version 1.6.2

**Comment by C1rdec** [comment]
The trade message that are not track are from the Korean Client

**Comment by C1rdec** [comment]
#9
