### ISSUE TITLE
Overlay doesn't show up

### ISSUE THREAD

**Issue by Skaithakk** [C1rdec/Poe-Lurker#172]
**Describe the bug**
I've reinstalled and restarted my pc multiple times trying to fix this, the overlay doesn't show up with incoming trades but if i have the sound notification on that part works but nothing else, i always play in windowed fullscreen and i've tried with and without vulkan.

**To Reproduce**
Steps to reproduce the behavior: There's really no steps but here it.
1. Just open the lurker.ui and nothing pops up.

**Expected behavior**
I was hoping for it to just work, seems like a really cool app.

**Screenshots**
https://i.imgur.com/C9H71WP.jpg Here is a screenshot of the settings open and down in that highlighted area there's supposed to be a little house icon right? there's not much else i can screen shot cause it doesn't show up.

**Please complete the following information:**
 - Version 1.6.2
 - Provide Log: i'm sorry but there is no log file in that path for me, i've looked multiple times. Unless you mean Nlog.dll?

**Additional context**
No additional context.

**Comment by C1rdec** [comment]
Can you try with DirectX11

**Comment by Tripwyr** [comment]
It works normally in DirectX11, but unfortunately the game is unplayable in DirectX11.

**Comment by C1rdec** [comment]
Can we connect on discord so we can investigate further?

**Comment by nomis51** [comment]
I had the same problem with Vulkan, and I managed to fix it by starting Poe-Lurker as admin **before** PoE, then start PoE. But, of course, it's very annoying, because if you forgot to start the lurker, you'll have to restart PoE all over again, just to start the Lurker....

**Comment by Tripwyr** [comment]
As in the issue you closed, you can message me on discord at Tripwyr#0001 and I would be happy to connect

**Comment by C1rdec** [comment]
Can you join the discord https://discord.gg/Vnf96R I'm Cedrico
