### ISSUE TITLE
Copy Item Name and auto Enter

### ISSUE THREAD

**Issue by Npok** [C1rdec/Poe-Lurker#173]
**Describe the bug**
When you "ctrl-C" an item, PoE lurker will put the Item Name in the chat when a certain key is pressed and send the message

**To Reproduce**
1. Copy an Item 'CTRL-C'
2. ALT+TAB (like you want to go on PoB)
3. Return on the game press enter: "thx for" - and it will put the item name after this

**Expected behavior**
Don't do anything when I don't press any shortcut

**Screenshots**
item I put in clipboard: http://prntscr.com/t6cn8t
result in tchat: http://prntscr.com/t6cljn

**Please complete the following information:**
 - Version v1.6.2
 - Provide Log (don't have any?)

**Comment by C1rdec** [comment]
I'm not sure what would be the scenario

**Comment by Npok** [comment]
I wanted to put the wand into PoB but when I returned to the game to answer the guy, PoELurker put the name in the message text and send the message. It's something not wanted by your tool I think ^^

**Comment by C1rdec** [comment]
Are you sure that it was Poe Lurker?

**Comment by Npok** [comment]
Yup, only had PoELurker & PoE Overlay, try to exit one by one and the behavior happened only with Lurker

**Comment by C1rdec** [comment]
Are you able to show me a video?

**Comment by Npok** [comment]
can stream on discord if you want to : Npok#0001

**Comment by C1rdec** [comment]
After investigation this is caused by the Poe Overlay Community Edition.
