### ISSUE TITLE
Non-English name whisper didn't trigger the overlay or accrue in the dashboard

### ISSUE THREAD

**Issue by alexberryman** [C1rdec/Poe-Lurker#174]
**Describe the bug**
A trade whisper didn't trigger the overlay, but previous and later trade whisper in the same gaming session did trigger the overlay. The trade also didn't get tracked in the dashboard. The only difference I see is the non-English characters in the username.  

**To Reproduce**
1. Make a character with non-English character, i.e `벌처염동진`?
1. Whisper a user for trade?

**Expected behavior**
Non-English characters don't impact the behavior of the tool.

**Screenshots**
Top whisper didn't work, bottom one did.
![image](https://user-images.githubusercontent.com/1881846/85807577-f02f8b80-b717-11ea-86cc-4d996af87543.png)

**Please complete the following information:**
 - Version v1.6.2
 - No logs exist

**Additional context**
None

**Comment by C1rdec** [comment]
#4 
It's an issue with the Korean Client that is not logging in the client.txt
