### ISSUE TITLE
Feature Request: Variables from Stats

### ISSUE THREAD

**Issue by livejamie** [C1rdec/Poe-Lurker#175]
I think it would be fun to have access to variables related to your stats.

I would like my thank you message to be something like:
"Thank you for being my 305th trade this league. Stay safe exile!"

Ideas:
{LeagueTradeNumberOverall} - Amount of trades total for current league
{LeagueTradeNumberDaily} - Amount of trades for league total for that day
{TradeNumberOverall} - Amount of trades made for all leagues

It might be fun to even have access to the amount of currency you've made that day possibly?
{LeagueAmountMadeOverall} - Amount of currency made overall
{LeagueAmountMadeDaily} - Amount of currency made that day

Open to other fun ideas.

**Comment by C1rdec** [comment]
I like the idea!

**Comment by livejamie** [comment]
I still think this would be fun :)

**Comment by livejamie** [comment]
Did this end up being too complicated?
