### ISSUE TITLE
Feature request: Show Map Tier on HP Globe when selling map

### ISSUE THREAD

**Issue by Murdoc84** [C1rdec/Poe-Lurker#176]
**Is your feature request related to a problem? Please describe.**
Show Map Tier on HP Globe when selling map, also increase HP Globe click size to filter by

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/22428605/85992947-e34fb800-b9f5-11ea-911c-01cb04e500e7.png)

**Comment by C1rdec** [comment]
Poe Lurker do not know the map tier of the map. To have a system that would work even if GGG changed the map tier require alot of work.

**Comment by Murdoc84** [comment]
in the message sent by the buyer there is information about what tier in the case of a map, just need to parse the content of the message like you probably get information about item name, tab name and position

**Comment by Murdoc84** [comment]
@###### Hi, I would like to buy your Orchard Map (T7) listed for 1 alch in Harvest (stash tab "~price 1 alch"; position: left 4, top 4)
@###### Hi, I would like to buy your Orchard Map (T3) listed for 1 alch in Harvest (stash tab "~price 1 alch"; position: left 3, top 11)
