### ISSUE TITLE
Focus stealing and PoE become top most on event

### ISSUE THREAD

**Issue by nomis51** [C1rdec/Poe-Lurker#178]
**Describe the bug**
My previous issue #170 is fixed, but there's a bigger problem now... Everytime the app update the overlay

- Add a name to the dashboard
- Remove a name from the dashboard
- New incoming request that add a square
etc.

It steals the focus from any window that is not the Path of Exile window and put Path of Exile top most.

**To Reproduce**

1. Open Poe-Lurker
2. Open PoE
3. Send a trade request
4. Alt-Tab to another window (e.g. Google Chrome)
5. Wait until the timer is done
6. Steals the focus to show up the game

----

1. Open Poe-Lurker
2. Open PoE
3. Alt-Tab to another window (e.g. Google Chrome)
4. Wait for an incomingf trade request
6. Steals the focus to show up the game

**Expected behavior**
Should not steal the focus and put the game top most. It should just play the new notification sounds and that's it.

**Please complete the following information:**
 - Version 1.6.3

**Additional context**
Does not always happen, but it happened several times today while I was browsing trades on the PoE Trade website, so it should easy to reproduce.
The overlay doesn't get the focus for itself, it just put the game top most, which result in stealing the focus to any other windows.

**Comment by C1rdec** [comment]
-Add a name to the dashboard
- Remove a name from the dashboard
- New incoming request that add a square

I just dont understand...

**Comment by nomis51** [comment]
Dashboard, I mean
![image](https://user-images.githubusercontent.com/25111613/86061806-6f350480-ba35-11ea-9395-5d858601f18d.png)

New incoming request square, I mean
![image](https://user-images.githubusercontent.com/25111613/86061857-88d64c00-ba35-11ea-97dd-369d2248613a.png)

And yeah, the app puts PoE top most, when something happens with the overlay.

- Outgoing timer ends (remove the name)
- New whisper for trade / Incoming trade (Add that little square with the currency amount, bottom of the screen)
- etc.

**Comment by C1rdec** [comment]
yeah there's a bug when the timer run out but regarding the new incoming offer everything if fine on my side.

**Comment by C1rdec** [comment]
in 1.6.4

**Comment by nomis51** [comment]
Well, I don't want to be annoying, but with version 1.6.5 (wasn't online for the 1.6.4 release, so can't tell for that one), I've experienced the bug that makes PoE top most when the timer runs out for outgoing offers again... Got the bug 3 times in the last 20mins.
