### ISSUE TITLE
[1.6.3] Hideout join notification on by default

### ISSUE THREAD

**Issue by sethkinast** [C1rdec/Poe-Lurker#179]
Just a small bug--

When I updated to the new version, I started getting the new "buyer joined hideout" notification even though it was off in the settings.

Turning the option on and back off resolved the issue. Just a problem with the default null state, probably.

**Comment by C1rdec** [comment]
Thx I will check this out

**Comment by C1rdec** [comment]
Are you sure about this issue I tried multiple time and the default value is false.

Try to rename your settings Poe Lurker will generate new settings and try it out. 

C:\Users\\[user]\AppData\Roaming\PoeLurker\Settings.json

**Comment by sethkinast** [comment]
Maybe something weird with my particular config after several upgrades then. If it works for new installs doesn't sound like a big deal (and it works fine for  me now that I toggled the setting once).

I'll check the config JSON if it happens again in future updates. Thanks!

**Comment by C1rdec** [comment]
You were not crazy I did a typo :P
