### ISSUE TITLE
Alt + F shortcut gets stuck when alt tabbing

### ISSUE THREAD

**Issue by kookiekrak** [C1rdec/Poe-Lurker#180]
Repro:

Play poe windowed
Alt tab out
Alt tab back in
have a chat open and type f when you're mousing over an item or have something in clipboard

It'll automatically type the name of the item or paste my clipboard and hit enter into the chat.

The alt gets stuck when i alt tab and it thinks i constantly have alt open.

Please fix this since its making me send stuff from my clipboard to random people!

**Comment by C1rdec** [comment]
Close Poe Overlay

**Comment by kookiekrak** [comment]
@C1rdec is there an option to disable the hotkey alt + f?

**Comment by C1rdec** [comment]
Yes
