### ISSUE TITLE
Stutter in windowed fullscreen with gsync

### ISSUE THREAD

**Issue by Fugaz1** [C1rdec/Poe-Lurker#181]
**Describe the bug**
Might be duplicate of #148. When using app I have microstutter in game.

This might be related to "update" button, as long as app is not rendering anything it seems fine. As soon as I clicked and updated (to 1.6.5 just now) it seems to be gone.

**To Reproduce**
1. Go to, for example, highgate near stash.
2. Run left right, compare with app on and off (when it is rendering something, turning on debug had no effect).

**Expected behavior**
No microstutter. I have no stutter with other tools like poe overlay or poe trades companion.

**Please complete the following information:**
 - Version 1.6.4

**Comment by C1rdec** [comment]
Yeah I removed the Vulkan option pretty sure it was related to that.
