### ISSUE TITLE
Tooltip Help Overlay

### ISSUE THREAD

**Issue by RJonesUSC** [C1rdec/Poe-Lurker#183]
The program is very useful but coming from another trade type program there's a learning curve due to all the shift, control, right, left, clicks, etc.

It would be nice to have a tooltip type of help that can be displayed/overlayed above the moused-over icon that listed the options you have when interacting with the icon.

For example, for an incoming trade, when the user mouses over the currency icon located next to the flasks above the progress bar, the available option for interacting with that icon could appear showing something like this:

**First Click**: invite buyer to your party.
**Long mouse down (500ms)**: invite buyer to your party.
**Second Click**: send trade request.
**Left/Blue corner:** "Busy" message.
**Right/Red corner**: dismiss Buyer's offer.
**Right-Click**: /Whois Buyer.
**Alt-Click**: set active offer (if you have multiple incoming trades).
**Ctrl-Click**: "Already Sold" message.
**Ctrl-Shift-Click**: "Still Interested?" message.
**Click Health Globe**: highlight item in stash (must manually click relevant stash tab).

The above list tooltip help could change based on which step you're currently at.  Meaning, if you haven't clicked it yet, only list the first click in the tooltip help and not the second click option.  If the icon has already been clicked once, then only list the second click tooltip help and not list the first click option because we've passed that stage already.

The same could be done for the outgoing trade options:

**Click**: join Seller's hideout.
**Click on Health Globe**: send trade request.
**Right-Click**: /Whois Seller.
**Left/Brown corner**: resend offer.
**Right/Red corner**: dismiss your offer.
**Holding Left Shift**: cancel the auto whisper out of third party trade sites.

Also, this tooltip option could be toggled on/off via the settings menu.

Thank you for the great tool you've provided for us to use.

**Comment by C1rdec** [comment]
Agreed but I feel like people will naturally  learn the software and will quickly disable this option. 
I'm currently working on a tutorial that would basically showcase the available actions. But I think just an overlay that  would show case those action and the user could move around a pin it down will do it.
