### ISSUE TITLE
Toggle automatic check for sold items

### ISSUE THREAD

**Issue by Uffgepasst** [C1rdec/Poe-Lurker#184]
Quite often I have an entire tab of items I am selling that is fluctuating quite heavily.
If I sell an item with a specific name, I can't sell another item in that slot anymore until I have restarted the lurker since it thinks the item, which I have refilled in the meantime, is gone.

I'd love if this feature could be toggled.

**Comment by C1rdec** [comment]
Will do

**Comment by C1rdec** [comment]
Added the option in 1.6.8
