### ISSUE TITLE
Feature request: a shortcut or something to make outgoing trades not disappear

### ISSUE THREAD

**Issue by Xebtria** [C1rdec/Poe-Lurker#186]
**Is your feature request related to a problem? Please describe.**
sometimes seller asks me to wait, and I still want to use lurker to handle the trade when s/he is ready

**Describe the solution you'd like**
e.g. shift right click stops the counter to go down and makes the ui thing permanent even thought I havent joined the seller's hideout for the trade yet

**Describe alternatives you've considered**
only true "solution" at the moment would be to whisper the seller again which is super annoying him/her

**Comment by C1rdec** [comment]
Alt Click will do I think
