### ISSUE TITLE
Highlight Shortcut 

### ISSUE THREAD

**Issue by dpwnage177** [C1rdec/Poe-Lurker#187]
Hello,
I bind my HP flask to the "F" key, and my Inventory to "C" Key.

Randomly, when I press "F" sometimes during a Map it open's up my Inventory which I bind to "C".
After it happens once it keeps on happening if I keep spamming the F key.
Only way to stop it is by pressing "Alt", after which pressing the F key no longer also presses the C key which is my inventory. 

After I disable the Item Highlight feature the problem never occurs.

My keyboard is pretty scuffed and sometimes does things like pressing the same key twice with one press randomly, but it never types two different keys with one key press.

If i was able to change the Alt+F command for highlight, or turn it off while keeping the highlight from the in-game onscreen option on top of health bar, I think it would get rid of needing to fix any bug.

**To Reproduce**
Happens randomly, even without any other Macro software running.

**Expected behavior**
When I press F key I excpect Health Pot to be used, but instead Health Pot is used and Inventory Window also pops up (which is bound to C key.
Pressing Alt once after first instance of the bug get's rid of the bug for small a period of time.

 - Version v1.6.7
 - Provide Log (C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs) 
I don't see a "logs" folder in this version.

**Comment by C1rdec** [comment]
IT's the Poe Overlay Community. 
turn it off you'll see

**Comment by dpwnage177** [comment]
Still happens with PoE Overlay off

**Comment by C1rdec** [comment]
Disable this feature

![image](https://user-images.githubusercontent.com/5436436/87078202-49a4b980-c1f2-11ea-91a1-6f80d37b72c0.png)

**Comment by dpwnage177** [comment]
Yeah that's what I've been doing
