### ISSUE TITLE
Incoming offer: Price parsing failed

### ISSUE THREAD

**Issue by nomis51** [C1rdec/Poe-Lurker#188]
**Describe the bug**
Someone whispered me to buy an item. The currency icon didn't show up in the offer square on the overlay. I realized while replying to the buyer, that the price part of the whisper haven't been parsed correctly, because the "Are you still interested" whisper was incorrect. That explain why the currency icon didn't show up in the offer square either.

**To Reproduce**
It worked before, but not with that particular whisper.

**Expected behavior**
I guess it should have parsed the whisper correctly.

**Screenshots**
In game chat
![image](https://user-images.githubusercontent.com/25111613/87333677-723af500-c50b-11ea-8493-d7ea256b1003.png)

Client.txt
![image](https://user-images.githubusercontent.com/25111613/87334508-c1355a00-c50c-11ea-9490-f5465ba8cc8f.png)

**Please complete the following information:**
 - Version 1.6.7
 - Provide Log 
Here is the log I have, but considering the date and time and the fact that it seems to show up an error by calling a method on an object in one of the view models, I don't think it's related to the whisper parsing issue
```
[2020/07/13 10:32:16.334] Error [76] La référence d'objet n'est pas définie à une instance d'un objet.
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à Lurker.UI.ShellViewModel.CleanUp()
   à Lurker.UI.ShellViewModel.<PoeClosed>d__64.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   à System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()
   à System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() (Lurker.UI.AppBootstrapper)
[2020/07/13 10:32:17.327] Error [77] La référence d'objet n'est pas définie à une instance d'un objet.
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à Lurker.UI.ShellViewModel.CleanUp()
   à Lurker.UI.ShellViewModel.<PoeClosed>d__64.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   à System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()
   à System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() (Lurker.UI.AppBootstrapper)

```

**Comment by C1rdec** [comment]
Tanks I will take a look after work.

**Comment by nomis51** [comment]
I got another issue related tp parsing a whisper yesterday. The app crashed just after and in the log it stopped on a specific whisper.
Again I guess it's an error while validating the content of the string, cause it tried to substring with a length of -1.
Here is the log :
[2020-07-14.log](https://github.com/C1rdec/Poe-Lurker/files/4925196/2020-07-14.log)

**Comment by C1rdec** [comment]
La prochaine fois pour m'aider a debugger essaie de mettre le message du trade en text ;)

**Comment by nomis51** [comment]
Oui, je suppose que c'est une erreur de parsing aléatoire, qui arrive genre 0.01% du temps :p
Pas grave.

**Comment by C1rdec** [comment]
I'll close this for now let me know if you encounter the issue again.
