### ISSUE TITLE
Clipboard polling: Chat clearing too fast

### ISSUE THREAD

**Issue by nomis51** [C1rdec/Poe-Lurker#189]
**Describe the bug**
Happens several times per day. When I'm whispering players using the "Whisper" button on the trade website, the app seems to be doing a quick Ctrl + A, then paste the whisper and hit Enter. But, sometimes it seems like it's doing it too fast, or something, because there's a "a" at the beginning of the whisper that remain (The Ctrl key was too fast I guess). So, I end up whispering the previous player with a message that looks like :

@PlayerA **a**@PlayerB Hi, I woul like to buy your Item X listed for 0 Currency in Harvest (stash tab "Selling"; position: Left 0, Top 0)

Notice the **"a"** at the beginning of the whisper content.
See the screenshot for a real chat example.

**To Reproduce**
- Go to the trade website
- Whisper multiple players (no need to be fast, just casual browsing/whispering)
- You'll notice that sometime the bug happen

**Expected behavior**
Should be able to clear the chat input correctly, to be able to send a proper chat message

**Screenshots**
![image](https://user-images.githubusercontent.com/25111613/87579441-e8725f80-c6a3-11ea-8236-4083eb5cbcd6.png)

**Please complete the following information:**
 - Version 1.6.7

**Comment by C1rdec** [comment]
Added a small delay.

**Comment by C1rdec** [comment]
Let me know if 1.6.8 fixed the issue
