### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by Gitter3000** [C1rdec/Poe-Lurker#190]
**Is your feature request related to a problem? Please describe.**
It is frustrating to be forced into specific actions with your application and I had to make a workaround .txt file just so that it would perform properly.

**Describe the solution you'd like**
A few things:

1. A file browse section to find the client.txt file ourselves in case we have it installed in another location
2. The ability to either disable or change commands, I would rather be able to right click to send a busy message and never use the /whois command. Personally, I only need a few commands: invite, trade, busy, exit. Having to aim my mouse at certain positions is hard while I am mapping.

**Describe alternatives you've considered**
I can't find the program's configuration files to edit it myself.

**Comment by C1rdec** [comment]
The client.txt should be found where did you install Poe?
Regarding the action those wont change for now. If you have difficulty to click the button you can scale the UI the in settings.

**Comment by Gitter3000** [comment]
Installed it into a custom drive I set on my PC, your program does not auto find it.
