### ISSUE TITLE
App ("always visible"/freeze/crash) when you (open the system tray menu and/or change PoE display mode)

### ISSUE THREAD

**Issue by nomis51** [C1rdec/Poe-Lurker#191]
**Describe the bug**
Happen yesterday and today (the only two times I tried to open the menu). When I right click on the app icon in the system tray, the app kinda freeze, the UI in-game disapear and/or is frozen aswell.
Yesterday I had to task kill the app, today it crashed/closed by itself.
Today just before the crash, I noticed that the app was in the "Always visible" state, but that option was disabled in the settings (Like always), and when I tried to open the settings to see what's going on, it froze, then crashed.

**To Reproduce**
Try to open the settings or interact with the system tray menu.

**Expected behavior**
Should be able to interact with the system tray menu.

**Please complete the following information:**
 - Version 1.6.7
 - Provide Log 
[2020-07-16.log](https://github.com/C1rdec/Poe-Lurker/files/4938609/2020-07-16.log)
[2020-07-17.log](https://github.com/C1rdec/Poe-Lurker/files/4938611/2020-07-17.log)

**Additional context**
Today I switched the display mode of PoE from Windowed Fullscreen to Windowed right before it got stuck in the "Always visible" mode, etc.

Yesterday, nothing in particular.

**Comment by C1rdec** [comment]
Yes it's fix in dev
