### ISSUE TITLE
Feature: Show Item name

### ISSUE THREAD

**Issue by nomis51** [C1rdec/Poe-Lurker#192]
**Is your feature request related to a problem? Please describe.**
When I receive multiple trade offers, I often end up not knowing what offer represent which item. So I need to mouse hover the UI offer to see what's the item, but let's be honest the tooltip on mouse hover event is **very** slow to show up... So it's quite annoying.

And quite often I would like to know which item is related to which UI offer, **before** I send a party invite for.. you know...  price fixing and other reasons ;)

**Describe the solution you'd like**
So showing the item name on top of the UI offer would be very usefull. Maybe you can add a setting for enable/disable this for a minimal/details UI.

Maybe something like this :

![image](https://user-images.githubusercontent.com/25111613/87838990-e0aee880-c866-11ea-9482-3cd48d4c3e36.png)

**Additional context**
By "UI offer" I mean:

![image](https://user-images.githubusercontent.com/25111613/87838430-0f2bc400-c865-11ea-9708-d68f9f2291ae.png)

**Comment by C1rdec** [comment]
No this UI is meant to be simple you can enable the tool tip to have additional information.
