### ISSUE TITLE
Improvement: Outgoing trade UI/UX

### ISSUE THREAD

**Issue by nomis51** [C1rdec/Poe-Lurker#193]
**Is your feature request related to a problem? Please describe.**
I like the app a lot, it's fast, simple, easy, but the outgoing UI is just not efficient I would say. I end up not using it, because the UI/UX design is bad I think. I'm having hard time knowing which label is which player is which item when whispering multiple players, so it's just easier to look at the chat instead...

**Describe the solution you'd like**
Personally, when I'm sending trade offers to players, I'm sitting in my Hideout browsing the trade website and /or waiting for responses. So I don't mind if the "Outgoing UI" is bigger and eats a part of my game screen.

Having more detailed offers listing would make that feature usable for me, because right now I would like to use it, but it doesn't feel right, so I'm not...

Something similar to the UI of Mercury Trade would be nice. Of course with the current automation you already have in the app that Mercury Trade doesn't ;) And maybe with the "Join hideout", "Leave party", "Re-send whisper" and "Remove offer" buttons would be enough.

![image](https://user-images.githubusercontent.com/25111613/87839489-0b01a580-c869-11ea-952d-3c5b431859b9.png)

Or a simpler variant those informations  :
- the player name
- the item name
- the price
- the time elasped

Maybe you can add a setting to enable a minimal UI (the one that is currently in the app) or a detailed UI (the improvement i'm talking about).

**Describe alternatives you've considered**
Using Mercury Trade, but I just don't like it. Your app is just simpler and quicker in my opinion ;)

**Comment by C1rdec** [comment]
I agree that can be larger but the UI/UX that you gave has example is horrific. The only information is important when you receive a party invite is the player name.

**Comment by nomis51** [comment]
Of course the UI of Mercury Trade a bit messy if you ask me, I was asking you to reproduce the same thing... just to give a general idead.
But, I think you're wrong with the informations needed :

If you whisper multiple players selling the same item for several different prices, you need to see what's price each player are selling it.
Let's say got 2 players inviting you to their party. Of course, you want to choose the player that is selling the cheapest item. But, right now, we need to look at the chat to know the price of each player **before** accepting the party invite... Having the price is a must have I would say.

I'm sure i'm not the only one, but really often I whisper players to buy **different** items at **different** prices at the same time (e.g. I'm gearing a new character, or doing upgrades), so knowing what's the item the one player will be throwing in the trade box is kind of usefull to gather the good amount of currency with me.

As for the time, well that's was just a "nice-to-have" that I found interesting, but not necessary at all.

**Comment by C1rdec** [comment]
Agreed I will try something

**Comment by C1rdec** [comment]
![image](https://user-images.githubusercontent.com/5436436/88012006-c125f300-cae6-11ea-96a9-8aef971d261d.png)

As-tu d'autre idée?

**Comment by nomis51** [comment]
Ça semble très bien à date! Je pense que le plus gros truc qui me dérangeait, c'était de ne pas être capable de rapidement voir quel joueur représentait quel label. Ayant maintenant leur nom complet dans un gros label, sort par prix et pouvant faire un search si j'ai whisper beaucoup de monde, ça me semble très bien.

Peut-être, en dessous du prix lorsqu'on fait un _Alt + Click_, est-ce que ce serait possible d'afficher le nom de l'item ?

**Comment by C1rdec** [comment]
Tu utilise peut être ce feature autrement, mais je ne comprends pas pourquoi tu aurais besoin de savoir le nom de l'item. Les "OutgoingOffer" sont éphémère, donc, 95% de temps tu vas déjà être au courant de l'item.

**Comment by nomis51** [comment]
Oui, tu as sans doute raison.

**Comment by C1rdec** [comment]
Mais je vais grossir la Font un peu.

**Comment by C1rdec** [comment]
Fixed in 1.6.8
