### ISSUE TITLE
Item Search with Alt + Click before invite, doesn't close after trade accepted and is stuck

### ISSUE THREAD

**Issue by nomis51** [C1rdec/Poe-Lurker#194]
**Describe the bug**
I did a Alt + Click on an incoming offer **before** I send party invite to search the related item in my stash. That works, but after I invited the player and completed the trade with him, the Search Item button on the Health Globe is still there.
And then after that it's bugged, because it keeps the old item in memory, so I can't search items anymore.

Here's a example : 

Someone whispered me to buy my Shrieking Essence of Wrath. I did the Alt + Click thing, then I clicked on the Health Globe button to search the item before I invite the guy.
Then, we completed the trade, etc.

Another player whispered me to buy my Remnant of Corruption. I invited the player to my party. But, when I tried to search the item using the Health Globe button, it searched "Shrieking Essence of Wrath" instead. I completed the trade anyway. But, the Health Globe is stuck with "Shrieking Essence of Wrath" and it doesn't disappear even if there are no offers...

![image](https://user-images.githubusercontent.com/25111613/87855075-f44c6480-c8e3-11ea-96d6-2e44265686e3.png)

I looked into the CheetSheet and I don't think there's any command to close/reset it.

**To Reproduce**
- Get an incoming offer
- Alt + Clicked it
- Search the item using the Health Globe button
- Completed or Remove the offer
- You're stuck with the Health Globe button searching for that item no matter what you do

**Expected behavior**
The Health Globe button should be set properly when you activate an offer.
It should close itself when a offer is removed (completed or just removed)

**Please complete the following information:**
 - Version 1.6.7
 - Provide Log: There are no log files.

**Aditionnal infos**
By "Health Globe button" and "Search Item button", I mean:

![image](https://user-images.githubusercontent.com/25111613/87855157-59a05580-c8e4-11ea-84e4-1fa22b870d04.png)

**Comment by C1rdec** [comment]
Fixed in 1.6.8.
