### ISSUE TITLE
Thank You Message Bug?

### ISSUE THREAD

**Issue by livejamie** [C1rdec/Poe-Lurker#196]
![image](https://user-images.githubusercontent.com/49513/88332806-019e9000-cce4-11ea-8c0a-5b210e40c5ed.png)

I messaged these two sellers, "CuriousInnocentWitch" didn't respond, and the Russian guy did. 

We did the trade, he disbanded the party and it sent my "Thank you" message to the first seller instead of the Russian guy.

**Comment by C1rdec** [comment]
Poe Lurker will send the Thank you message to the active offer.
