### ISSUE TITLE
More Outgoing Control

### ISSUE THREAD

**Issue by livejamie** [C1rdec/Poe-Lurker#197]
It would be nice to have an option to turn off the outgoing monitor and/or to turn off the thank you message to outgoing trades.

Also it would be nice to have an option where (or maybe by default) it doesn't cover up the menu button.

Thanks!

**Comment by C1rdec** [comment]
You can turn off the Than you message be removing the text in the settings.

**Comment by livejamie** [comment]
I want the thank you for incoming trades not outgoing trades.
