### ISSUE TITLE
Issue #194 still happen

### ISSUE THREAD

**Issue by nomis51** [C1rdec/Poe-Lurker#198]
**Describe the bug**
The issue [#194](https://github.com/C1rdec/Poe-Lurker/issues/194) just happened once again with version 1.6.8.
But, this time, when I remove/complete the offer, the Life Globe button is removed (that's fine and fixed), but it's still stuck on the previous item/offer.

I restarted the app to reset the Life Globe button, but every time I do the steps in the ** To Reproduce ** section, the bug happen.

**To Reproduce**
1. Alt + Click on an offer (before you invite the player)
2. Highlight the related item
3. Complete/Remove the offer
4 Wait for another offer to come in
5. Invite the player to your party
6. Try to highlight the related item, it's stuck with the previous one

**Expected behavior**
See #194 

**Screenshots**
Here's another in-game example:

![image](https://user-images.githubusercontent.com/25111613/88571275-62dba180-d00b-11ea-8930-9922b76a86c4.png)

**Please complete the following information:**
 - Version 1.6.8
 - No logs

**Comment by nomis51** [comment]
Here's another variant of the bug. I didn't `Alt+Click` at all and the Life Globe button still show up, but doesn't get stuck with the previous offer. It reset once I select a new offer.

![image](https://user-images.githubusercontent.com/25111613/88821589-dbb83600-d190-11ea-9d3b-2638e0dbc611.png)

Again, no log.

**Comment by C1rdec** [comment]
What's the name of your tab?

**Comment by nomis51** [comment]
One instance
![image](https://user-images.githubusercontent.com/25111613/88822385-c8599a80-d191-11ea-9705-9bdc4aa0c4f4.png)

and there's no tab name, because that item come from a forum offer.
Here's the whisper:

`@From Vizziz: Hi, I would like to buy your Elegant Hubris Timeless Jewel listed for 24 chaos in Standard`

**Comment by C1rdec** [comment]
Can you show me your forum post? You created it?

**Comment by nomis51** [comment]
That's a forum post generated with the Acquisition app. I still use the app to do some stuff.
Here's an example of the output of the forum post : 

`[spoiler][spoiler=" ~b/o  0.1 chaos"][item post="23007195" index="1"][/spoiler][/spoiler]`

Nothing really usefull, cause it's getting indexed couple sec after it's posted into a "real" listed item that you can see on the trading website.

Here's the [link ](https://www.pathofexile.com/forum/view-thread/2802635) to that forum post, but keep in mind that the item shown in my previous post is sold and won't be in that post

**Comment by nomis51** [comment]
Since 1.7.x, I didn't get the bug, so I believe it's fixed.
Closing the issue.

**Comment by C1rdec** [comment]
Let me know if you experience the issue again.
