### ISSUE TITLE
POE Reforge Whispers Not Supported

### ISSUE THREAD

**Issue by livejamie** [C1rdec/Poe-Lurker#199]
There are currently two websites that allow users to purchase harvest crafts, there is [forbiddenharvest](https://forbiddenharvest.com/) and their whisper is in this format:

> @Baba_z_Kulami Hi, I would like to buy your craft Remove a random Chaos modifier from an item and add a new Chaos modifier listed for 16 chaos in Harvest.

This currently works with lurker's clipboard feature.

The other site [reforge](https://reforge.poe.dev/public/harvest/mod/remove-chaos-add-chaos) is formatted like this:

> @prilicnodobro Hi from PoE Reforge, I WTB [remove-chaos-add-chaos] for 15c

This is not supported by lurker, is that something that can be added?

**Comment by C1rdec** [comment]
Harvest is not going core.
