### ISSUE TITLE
Support for outgoing trades

### ISSUE THREAD

**Issue by Xebtria** [C1rdec/Poe-Lurker#2]
Since MercuryTrade's development is discontinued and it will only work "until it breaks", I am very happy to see some alternatives.

However, for it to "replace" mercurytrade it would be required to also incorporate some of its main features, one of it being outgoing trades, do you plan to support it at some point?

**Comment by C1rdec** [comment]
Mercury is a big beast but yeah we should list all the feature of Mercury in order of importance for the community.

**Comment by C1rdec** [comment]
I'm starting to prototype this feature I'm just curious to have your opinion. 

How would you see this feature?

**Comment by Xebtria** [comment]
Basically the same. you get the big button once you whisper a guy. 
clicking the big button is porting to that guy's hideout.
once trade completes, auto-say thanks and leave party. The latter might be difficult, you either also want to add a configurable setting for the charactername. Or is there another way to get the current charactername automatically?

There should also be a button to re-send the message (top left I guess), it sometimes happens that the seller 
gets so many whispers and then asks what you wanted to buy from him/her, so a re-send button might be helpful. I don't think that a "tradewith" is required, as usually the seller should initiate the trade.

and of course a button to close the thing (top right) in case like you do not want the item anymore or the seller doesn't answer etc. just close the button, not sending anything, that's it.

I think this should be the main features.

**Comment by C1rdec** [comment]
Are you seeing those "outgoing buttons" in the same "TradeBar" or you will want to have it place somewhere else ?

**Comment by Xebtria** [comment]
Frankly, I don't really care. comparing to mercury as this was the big OG thing, being in the same line is definitely an option, especially when you have squares for incoming and circles for outgoing.

Another thing that comes to mind especially when buying stuff is, you often have to whisper A LOT of people until you get an answer. is having some sort of scroll bar (in whatever specific way) an option? because even if it grows horizontally and not vertically, I am not sure if having e.g. 20 trades without a scrollbar is _that_ nice.

But I could also see two different bars, similar to how buffs and debuffs are two different bars. could also be an option.

**Comment by C1rdec** [comment]
![image](https://user-images.githubusercontent.com/5436436/74212494-7748ff00-4c62-11ea-9211-d9d3df8ca81c.png)


### **Action**

- OnClick (Join Hideout)
- Left Corner (Re-Send)
- Right Corner (Delete)

And the bottom border would display a decreasing progress that when it reach zero the offer would disappear. The time would be configurable in the settings.

**Comment by Xebtria** [comment]
This does sound like a nice way of doing it. would love to see it in action

**Comment by C1rdec** [comment]
Soon ;)

**Comment by C1rdec** [comment]
1.4.0 is out with the support of outgoing trades. 
I will add the trade value in 1.4.1. 

Give me some feedback :)

**Comment by Xebtria** [comment]
Like it in general. would it be possible to have the same autodetection when the trade was successful and automatically send a (customizable) message to the seller like there is when someone buys something from me?

**Comment by C1rdec** [comment]
Ofc I wanted to let this feature out quick to get some feedback.

**Comment by Xebtria** [comment]
Would it be possible to support other languages for outgoing trades as well? because using the official trade site, more often than not you actually get russians or koreans and whatnot and the site changes the trade message to their client language, and it isn't picked up (for obvious reasons I guess)

While I do not speak the language, I think the pattern is easily distinguishable from the rest of the message -  at least for russian and korean I put some examples there and marked the part which should be able to trigger the tool bold. Korean message interestingly seems to be split into two parts which are always the same. 

@КортикТу **Здравствуйте, хочу купить у вас** Клинок Иннсбери Меч старейшины за 5 chaos в лиге Метаморф (секция "Трейд"; позиция: 1 столбец, 9 ряд)
@бандиитка **Здравствуйте, хочу купить у вас** Зловещая грань Большой белый коготь за 1 chaos в лиге Метаморф (секция "~b/o 1 chaos"; позиция: 3 столбец, 11 ряд)
@ПЕДРИЛД **Здравствуйте, хочу купить у вас** Фениксовые кулаки Имперский коготь за 30 chaos в лиге Метаморф (секция "TD1"; позиция: 11 столбец, 5 ряд)

@로봇문_변형리그 **안녕하세요, 변형**(보관함 탭 "판매", 위치: 왼쪽 9, 상단 11)에 0 exa(으)로 올려놓은 최면의 발톱 공포의 클로 **(을)를 구매하고 싶습니다**
@지뢰깔기십초전 **안녕하세요, 변형 **(보관함 탭 "거", 위치: 왼쪽 11, 상단 6)에 3 chaos(으)로 올려놓은 인스뷰리 칼날(Innsbury Edge) 장로의 검 **(을)를 구매하고 싶습니다**
@마제티스 **안녕하세요, 변형**(보관함 탭 "아이템판매", 위치: 왼쪽 2, 상단 2)에 1 chrom(으)로 올려놓은 코발트색 주얼 **(을)를 구매하고 싶습니다**

**Comment by C1rdec** [comment]
WHY GGG 😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭

**Comment by Xebtria** [comment]
sorry I took a bit time off my pc, only saw it right now. :)
