### ISSUE TITLE
visual glitch after update

### ISSUE THREAD

**Issue by vadash** [C1rdec/Poe-Lurker#201]
![image](https://user-images.githubusercontent.com/1397582/93455604-79e49480-f8d4-11ea-8070-9cd5de7d87a0.png)

How can I disable this ?

**Comment by iynaix** [comment]
Same issue, disabling the build helper doesn't remove the bar.

**Comment by C1rdec** [comment]
yeah I just saw this morning.. I'll make an update in 1h but for now you can import a build and disable the timeline using the toggle switch.

**Comment by C1rdec** [comment]
Fix in 1.7.1
