### ISSUE TITLE
Build helper problem

### ISSUE THREAD

**Issue by AbrahamLincooln** [C1rdec/Poe-Lurker#202]
**Describe the bug**
Turning off build helper does not turn off skill timeline. Additionaly clicking on skill timeline with build helper turned off is crashing the app

**To Reproduce**
1. Turn on Build Helper
2. Turn on Skill timeline
3. Turn off Build Helper
4. Close and open again the app
5. Click on the timeline

**Expected behavior**
Turning off build helper should close timeline as well. That would prevent crashes associated with it.

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/51491427/93605115-9eb93480-f9c6-11ea-9634-15478880ca59.png)
![Screenshot_3](https://user-images.githubusercontent.com/51491427/93605134-a4167f00-f9c6-11ea-98dd-5b7b92e8559d.png)

**Please complete the following information:**
 - Version v1.7.2
[2020-09-18.log](https://github.com/C1rdec/Poe-Lurker/files/5245901/2020-09-18.log)

**Comment by C1rdec** [comment]
Thanks I will take a look.

**Comment by C1rdec** [comment]
Fix in dev I will release 2h before league launch.

**Comment by C1rdec** [comment]
Fixed in 1.7.3
