### ISSUE TITLE
Build Helper Gem Timeline visual bug

### ISSUE THREAD

**Issue by Reaver01** [C1rdec/Poe-Lurker#205]
**Describe the bug**
Build helper moves to tiny box in top left of screen when turned off.

**To Reproduce**
1. Turn on Build Helper
2. Import a Build
3. Turn off Build Helper

**Expected behavior**
Build helper is turned off and does not leave artifacts or any items on the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/1864450/93813962-22fef800-fc11-11ea-8cfc-a0d4e918cc71.png)
![image](https://user-images.githubusercontent.com/1864450/93814008-327e4100-fc11-11ea-9a1d-6c1db16ab33c.png)

**Please complete the following information:**
 - Version [e.g. v1.7.4]
 - Provide Log | No Logs

**Additional context**
Happens inconsistently seemingly related to when you open PoE Lurker and when you open PoE, but I can't tell if there is a relation or not as I have had it happen in both circumstances.

**Comment by C1rdec** [comment]
Fixed in 1.7.5
