### ISSUE TITLE
The program does not work at all.

### ISSUE THREAD

**Issue by Aldwew** [C1rdec/Poe-Lurker#207]
It just doesn't do anything else besides instantly sending the trade message when I click copy on the website. Tried using DX11 and Vulkan, no difference, tried running it as admind and non admin.

**Comment by C1rdec** [comment]
If you enable debug mode can you see the overlay?

(They will have green background)

**Comment by Aldwew** [comment]
Yep, a green bar appears on my srcreen when enabling debug mode.

**Comment by C1rdec** [comment]
Can you join the discord so we can connect?
(I'm Cedrico)

**Comment by Aldwew** [comment]
Sure thing, where's the discord link?
