### ISSUE TITLE
Add option to prevent the browser popup

### ISSUE THREAD

**Issue by Nuhauskis** [C1rdec/Poe-Lurker#208]
Current Feature: When Poe Lurker updates, it opens the latest release page on github to show us what was fixed or added.

Problem: The github page opens a new tab in the active browser window and sets it as the active tab. This can interrupt people while they're watching videos or doing anything else on their second monitor. The problem is worse for people with a single monitor as the browser will open directly on top of the game, which could cause issues for players who clicked the update button at the wrong time. The update button's icon on the mana orb looks out of place to me so I always click it to make it go away.

Solution: Add an option in the settings to disable patch notes. This option would prevent Poe-Lurker from opening its github release page when we click on the update button while still allowing users to update the program.

Alternatives:
   1. Disable the patch notes by default and make it opt-in by adding an option to enable patch notes.
   2. Add an option to disable the update button appearing over the mana orb and instead only make the taskbar icon yellow. This prevents the issue of the update button appearing within the game during gameplay.
   3. Add an option to auto-update only when we start the app and not while it's running.

**Comment by C1rdec** [comment]
Added in 1.7.8.

![image](https://user-images.githubusercontent.com/5436436/95037715-eb289380-0699-11eb-9628-de52b2530d63.png)

**Comment by Nuhauskis** [comment]
Cool, thank you

**Comment by C1rdec** [comment]
Sorry for the delay I was working on the unique item stuff for the timeline...

**Comment by Nuhauskis** [comment]
No worries!
