### ISSUE TITLE
v1.7.5 sometime PoE Lurker stops working

### ISSUE THREAD

**Issue by Chocapic** [C1rdec/Poe-Lurker#209]
I dont know if its related to alt tabbing / bein windowed fullscreen but sometime the trade overlay wont trigger when I receive an offer but might work for the next one. Usually if Im tabbed out and come back in the game the overlay will appear so I don't really know what this bug is.

Using dx11

**Comment by C1rdec** [comment]
Can you provide your logs plz

![image](https://user-images.githubusercontent.com/5436436/94579096-704d1c00-0246-11eb-870a-7660496ccc8c.png)

**Comment by Chocapic** [comment]
[2020-09-26.log](https://github.com/C1rdec/Poe-Lurker/files/5300160/2020-09-26.log)

**Comment by C1rdec** [comment]
OK merci je vais voir quesque je peux faire.

**Comment by C1rdec** [comment]
Les trade qui n'apparaissent pas c'est des trades des joueurs Korean. 

https://github.com/C1rdec/Poe-Lurker/issues/4#issuecomment-570510029
