### ISSUE TITLE
Chat window popping up as of 1.1.2 when issuing trade command

### ISSUE THREAD

**Issue by Maldini999** [C1rdec/Poe-Lurker#21]
After I downloaded 1.1.2, this is how my interactions work

1) Trade offer comes in and POE Lurker icon comes on screen
2) I click main action window to invite buyer
3) Buyer accepts and comes to my hideout
4) I click main action window to initiate a trade
5) Instead of trade being initiated like in previous version, chat window pops up
6) I close chat window
7)  I click main action window to initiate a trade
8) Trade request is initiated

Was something added to 1.1.2 that changes how I should be doing step 4 above?

By the way, LOVE the new "find in stash" feature.  Very nicely done.

**Comment by Reaver01** [comment]
You will have to click outside of the ctrl+f window more than likely. It sends "enter" "/tradewith person" "enter" so if you are clicked into the find box the first enter closes that, then it types into nowhere, and finally the second enter opens trade chat. Used to happen to me with Mercury all the time too.

**Comment by C1rdec** [comment]
Yeah I fixed the issue it will be in the next release. The problem was we did not register an Enter Key at the end of the search. The focus was staying the in search box...

**Comment by Maldini999** [comment]
ok thanks!!

**Comment by C1rdec** [comment]
I'll close this issue.
