### ISSUE TITLE
Chat actions not queued properly. Causing conflicts

### ISSUE THREAD

**Issue by nomis51** [C1rdec/Poe-Lurker#211]
**Describe the bug**
Since the last update, i'm getting a lot of problems with all the automatic chat actions, such as reply thanks, kick player, etc.
Instead of being processed one after the other to avoid conflicts while using the chat, now they just output their command at the same time (or almost) which result in uncomplete whispers, failed chat commands and even wrong chat channel/person whispered.

**Please complete the following information:**
 - Version1.7.7
- I'm using the auto kick and auto whisper options, like before

**Comment by sethkinast** [comment]
Getting the same thing. You can see here where it tries to say "ty and gl" to this buyer, and instead the commands get sort of mixed in.

![OgKXgyu](https://user-images.githubusercontent.com/1399532/94984650-fd23fe00-0502-11eb-9dbb-bac75c8fe18d.png)

**Comment by mohammedh123** [comment]
+1 to this. restarting it usually fixes it (albeit temporarily)

**Comment by C1rdec** [comment]
Should be fixed in 1.7.8.

Let me know if you guys still experience this issue.

**Comment by sethkinast** [comment]
It actually crashes Lurker completely now when it tries to reply. The tray icon and process die.

**Comment by C1rdec** [comment]
Can you provide the logs plz

**Comment by sethkinast** [comment]
[2020-10-04.log](https://github.com/C1rdec/Poe-Lurker/files/5325261/2020-10-04.log)

**Comment by C1rdec** [comment]
Go to %appadata%/poelurker and delete Xan you provide me your trades.db file located in "%appdata%/poelurker/trades.db"

**Comment by sethkinast** [comment]
[Trades.zip](https://github.com/C1rdec/Poe-Lurker/files/5325398/Trades.zip)

**Comment by sethkinast** [comment]
Cache deleted, will try again cheers 👍

**Comment by sethkinast** [comment]
Still crashed immediately; similar error.
[2020-10-05.log](https://github.com/C1rdec/Poe-Lurker/files/5325951/2020-10-05.log)

**Comment by nomis51** [comment]
As of 1.7.10, it seems good now!
