### ISSUE TITLE
"Cannot insert duplicate key in unique index" crash

### ISSUE THREAD

**Issue by judders96** [C1rdec/Poe-Lurker#213]
[2020-10-05.log](https://github.com/C1rdec/Poe-Lurker/files/5326105/2020-10-05.log)

App is crashing after finishing a trade.

**Comment by judders96** [comment]
Just to add, disabling auto-kick has stopped the crashes for me.

**Comment by Murdoc84** [comment]
Same problem here.

**Comment by C1rdec** [comment]
Fixed in 1.7.9

**Comment by sethkinast** [comment]
Confirmed all working well again as of the latest update.
