### ISSUE TITLE
Focus problems

### ISSUE THREAD

**Issue by nomis51** [C1rdec/Poe-Lurker#214]
**Describe the bug**
Quite often, when I interact with the overlay, it does not always focus back to PoE correctly (e.g. send a party invite).
And because it keeps the focus on PoeLurker, some actions (e.g. send party invite), don't work properly.
So I have to click/Alt-Tab back to the game and retry.

Not a big problem, but quite annoying, because sometime it just keep on happening over and over every time I do something with the overlay.
But, usually it happen once, then it run properly for couple trades/interactions before it happen again.

I'm using Awakened PoE Trade to price check, validate maps, etc. Not sure if PoeLurker and APT can conflict themselves, so that could be the problem here. I'll try to use PoeLurker without APT for a while to see if the problem keep happening. I'll post hints here if I got any.

Meanwhile, here are some screenshot of AccEvent showing the problem with some comments.

**Screenshots**
Party invite bug example:
![PoeLurker-focus-bug](https://user-images.githubusercontent.com/25111613/95264619-a9b0f900-07fd-11eb-8a7f-ed475fabf8f9.png)

Awakened PoE Trade example as a reference (no focus problem):
![apt-focus](https://user-images.githubusercontent.com/25111613/95264659-bd5c5f80-07fd-11eb-9319-b8d09b9aeca4.png)

Using Google Chrome, APT and PoeLurker, like I do usually while playing (been able to get the bug while recording that one):
![all-focus-bug](https://user-images.githubusercontent.com/25111613/95264723-d9600100-07fd-11eb-9e64-8bec670418df.png)

**To Reproduce**
1. Litterally just interact with the overlay, while Alt-Tab-ing to other apps, then come back to the game, etc.

Here's a list of actions I did that causes the problem (may or may not be related directly to those actions, but that's just my observations):
- Invite a player (Offer click) (Happen really often)
- Re-invite a player (you know the long mouse down on the offer) (Happened once)
- Alt - Click an offer (Happen really often)
- Trade with a player (Offer click) (Happen often)
- Item highlight (Life bubble click) (Rare)

**Expected behavior**
Should focus to the appropriate app (PoE or PoeLurker) properly according to the requirements of the action triggered.

**Screenshots**

**Please complete the following information:**
 - Version 1.7.10
 - No logs

**Comment by C1rdec** [comment]
Thanks I will look this up

**Comment by C1rdec** [comment]
Every thing's fine on my side...

**Comment by nomis51** [comment]
So after testing more with and without APT running, seems like the bug mostly occur with the Alt + Click command, and the app start to "not focus properly" right after I did a Alt + Click, which mostly tells me that it's Alt + Click fault. If I restart and avoid the Alt + Click command, the app runs fine.

So I would say, investigate the Alt + Click listener to see if something in the call stack could potentially prevent the app from focusing back to PoE correctly and eventually cause other problems.

**Comment by C1rdec** [comment]
Can you get a video of your issue?

**Comment by C1rdec** [comment]
Fixed in 1.7.11

**Comment by nomis51** [comment]
Seems good so far!
