### ISSUE TITLE
Lurker Crashing

### ISSUE THREAD

**Issue by Necrozin** [C1rdec/Poe-Lurker#215]
**Describe the bug**
Poe Lurker crashing while clicking the lurker icon in the "show hidden app" menu.

**Please complete the following information:**
 - Version 1.7.11
[2020-10-13.log](https://github.com/C1rdec/Poe-Lurker/files/5369667/2020-10-13.log)

**Comment by C1rdec** [comment]
Can you provide me your `Tokens.json` file located:

"C:\Users\\[user]\AppData\Roaming\PoeLurker\Tokens.json".

After getting a copy you can delete the file on Poe Lurker will stop crashing.
