### ISSUE TITLE
Outgoing offer stay visible after the countdown.

### ISSUE THREAD

**Issue by C1rdec** [C1rdec/Poe-Lurker#216]
Outgoing offers stay visible even after the progress bar hit 0.

**Comment by nomis51** [comment]
It was not happening for me with the previous version, but with 1.7.11 i'm getting the problem aswell.

**Comment by C1rdec** [comment]
Yeah it's fixed in dev I'll make an update

**Comment by C1rdec** [comment]
Fixed in 1.7.12
