### ISSUE TITLE
Automatic whisper not working

### ISSUE THREAD

**Issue by drovardi1** [C1rdec/Poe-Lurker#217]
**Describe the bug**

When clicking "Whisper" on the path of exile trade website the message gets copied but does not get automatically pasted ingame. 

**To Reproduce**
3. See error

I'm not sure? This feature was working perfectly well on 14/10/2020 at like 8pm but around 9 or so pm it just stopped. 

**Expected behavior**

When I click the "Whisper" button on path of exile trade website I expected it to copy the message to my clipboard, which it did, and then automatically paste that message ingame completing the whisper process. It did not do the latter half. 

**Screenshots**

**Please complete the following information:**
 - Version [e.g. 
 - Provide Log (C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs)#

verison 1.7.11
I actually can't find any logs when I go to that place 

**Additional context**

**Comment by C1rdec** [comment]
It's working on my side... Can you try to uninstall and install the version that was working.

**Comment by drovardi1** [comment]
The setting was on. I did turn it on and off after the problem started to happen to test it. I also uninstalled and reinstalled the latest version. I wasn't sure what version I was on before when it was working but I assume it to be the latest because poe lurker automatically updates right? so 1.7.11

**Comment by C1rdec** [comment]
No you need to update manually. I want you to install the older version that was working to test if you are able to make it work again...

**Comment by drovardi1** [comment]
oh i see. is there anyway i can check what version I was using before cause I just thought i was on the latest version so i don't really know?

I did install an old random version of Poe lurker and that did fix the issue. On version v1.4.16 the auto whisper function works but it does not on the most recent version.

**Comment by C1rdec** [comment]
Can you try [1.7.4](https://github.com/C1rdec/Poe-Lurker/releases/tag/v1.7.4)

**Comment by C1rdec** [comment]
Fixed in 1.7.12
