### ISSUE TITLE
There is no place to set Character name

### ISSUE THREAD

**Issue by Murdoc84** [C1rdec/Poe-Lurker#219]
![image](https://user-images.githubusercontent.com/22428605/96331868-14b1c980-1061-11eb-8f63-fe719ac58dea.png)

**Comment by C1rdec** [comment]
Buildhelper for now

**Comment by C1rdec** [comment]
In the next update you'll be able to set the character with the system tray icon.

![image](https://user-images.githubusercontent.com/5436436/96463926-3d6ac800-11f5-11eb-81fe-a68f73072e69.png)
