### ISSUE TITLE
lurker is detected by bitdefender

### ISSUE THREAD

**Issue by fislysandi** [C1rdec/Poe-Lurker#220]
somehow lurker is marked as suspisious by an antivirus

1.download the av and install ir
2.install lurker 
3.get detected

**Expected behavior**
work

**Screenshots**
https://imgur.com/a/8p46Cuc

**Please complete the following information:**
latest version

**Additional context**

**Comment by fislysandi** [comment]
now i cant install lurker thanks av.

**Comment by C1rdec** [comment]
You'll need to give me the reason other than that I can do nothing. But the installer is sign soo I dont know why this is detected.

**Comment by C1rdec** [comment]
Add Poe Lurker to the WhiteList.
