### ISSUE TITLE
Item for sale not showing up as sold

### ISSUE THREAD

**Issue by Kataklysm83** [C1rdec/Poe-Lurker#221]
Description:
For the most part items are showing sold and the icon switches to the shopping cart like normal. But I am still seeing random items not showing up sold. Commonly it has been magic find-related items that bots are trying to swoop up. So will need request spams for the spot that is now vacant because it's sold.

Reproduce:
As stated before, magic find-related items or items bots in the game want, are commonly showing not as sold.

Expected behavior:
Show as sold

Version 1.7.11

**Comment by C1rdec** [comment]
Poe Lurker will remember your last 5 trades. The name and the position of the item is used to mark it as sold. 
This part of the code is unit tested I'm pretty confident that you had 2 items with the same name.

**Comment by Kataklysm83** [comment]
That is not the case. If you are the end of my description, there is nothing in that spot. The buyer will ask to buy that item right after it has been sold, the spot still vacant and sold less than 5 ago. I will test this again, this time with screenshots when it occurs again.

**Comment by C1rdec** [comment]
As soon as the item is sold if any other trades comes in they will be marked as sold. 
Are you saying that if you already have multiple trades and you complet one of those you'll like to see the others being flagged as sold?
