### ISSUE TITLE
Poe Lurker Installation has failed Bug

### ISSUE THREAD

**Issue by zalmoxis91** [C1rdec/Poe-Lurker#222]
New version suddenly gives me this error
[SquirrelSetup.log](https://github.com/C1rdec/Poe-Lurker/files/5421649/SquirrelSetup.log)

Tried to redownload poe lurker, still gives me this :(
Please fix, PoE is so horrible without it..

Thank you!

**Comment by C1rdec** [comment]
This seems to be an issue on your side try to uninstall using add or removes programs.


![Screenshot_20201022-063025.png](https://user-images.githubusercontent.com/5436436/96859963-282dad80-1430-11eb-815b-67545d310368.png)

**Comment by zalmoxis91** [comment]
I just tried and I get the same issue. After Lurker is uninstalled and doesn't even show in the installed programs list.

**Comment by zalmoxis91** [comment]
[SquirrelSetup.log](https://github.com/C1rdec/Poe-Lurker/files/5423024/SquirrelSetup.log)
Here's the new attachment, maybe it helps

**Comment by C1rdec** [comment]
Delete this folder:

`C:\Users\\[user]\AppData\Local\PoeLurker`

**Comment by zalmoxis91** [comment]
It works now. Thank you!!
