### ISSUE TITLE
poe lurker dashboard button (mana globe) is in forground of everything even if poe is not in focus

### ISSUE THREAD

**Issue by Xebtria** [C1rdec/Poe-Lurker#223]
**Describe the bug**
Not really a bug, more an annoyance
There are many notifications from windows or other apps and programs which appear in the lower right corner of the monitor. But when PoE is running, nothing on those notifications can be clicked because the lurker UI dashboard button is in foreground.

**To Reproduce**
Star lurker
start poe
be in hideout or town
have any sort of notification appear, whatever it might be, as long as it is in the bottom right corner.
it also affects if you have e.g. youtube on fullscreen, most of the buttons are "behind" that dashboard click button

**Expected behavior**
the circle thing from lurker should not be active if poe is not in focus. at the same time, the incoming trade buttons should be visible even if poe is not in focus (for incoming trades while I do something else, so I still see it even with poe not in focus). this issue is only affecting that mana circle thing.

**Screenshots**
https://i.imgur.com/oz5WLGl.png (showing the ui basically overlaps everything from youtube, only the fullscreen button is barely clickable, the other three are behind the lurker "button")

**Comment by C1rdec** [comment]
You should disable the `Always Visible` option. I will investigate a better way to open the dashboard.
