### ISSUE TITLE
Build Helper turns on everytime

### ISSUE THREAD

**Issue by Kzoomarine** [C1rdec/Poe-Lurker#224]
Everytime POE is restarted Build Helper reactivates even though it is toggled off in the settings.

Have to toggle it back on then off to get rid of it.

**Comment by C1rdec** [comment]
Working on my side make sure you close the setting window to save.

**Comment by C1rdec** [comment]
Can you provide more information or can we connect on discord?

**Comment by Kzoomarine** [comment]
Everytime I load up POE, regardless of whether lurker is running first or not, I have to go into Lurker settings, toggle Build Helper on and then off again, and close settings, then I mouse over the Build Helper bar and it disappears. 

It started when I toggled Build Helper on our of curiosity...haven't been able to get free of it since.

**Comment by C1rdec** [comment]
Can you try to capture the behavior in a video.
