### ISSUE TITLE
Make a health globe helper larger

### ISSUE THREAD

**Issue by DSCriErr** [C1rdec/Poe-Lurker#226]
Hi there.
Can you make this window a little bit wider? To keep auto b/o tabs working their name forced to start with "~b/o 1 chaos".
the showcase of an issue - https://imgur.com/a/lSObckU

I do many 1c trades when I feeling not playing, so I have to colour code them by adding text after the required b/o stuff, and its cuts off.

**Comment by C1rdec** [comment]
No the overlay block the dropdown menu of the chat.

**Comment by C1rdec** [comment]
https://github.com/C1rdec/Poe-Lurker/issues/74

**Comment by DSCriErr** [comment]
That's unfortunate.

https://imgur.com/7PKqhfB
