### ISSUE TITLE
Cannot switch to another active character

### ISSUE THREAD

**Issue by leohero92** [C1rdec/Poe-Lurker#227]
**Describe the bug**
Cannot switch to active character
This also cause Build Helper feature broken

Could you tell me how PoeLurker can detect active character, so I can try some workaround, hope it will work before launching of Mayhem?

**To Reproduce**
Precondition: 
Game is launched, signed in, select 1 character with char name is Ms****

1. Launch Poe Lurker version 1.8.0 as administrator, wait until timeline bar and ? icon are shown
2. Right click on Poe Lurker on system tray
3. Showing active character with char name is LoH**** (another character)
4. Left click on LoH****, only LoH**** show in the list

**Expected behavior**
3. Showing active character with char name is Ms*****
4. Name of active character Ms****  is shown in the list and can be selected

**Screenshots**
![image](https://user-images.githubusercontent.com/6971379/101194796-095a4200-3691-11eb-81c8-e429bdb49bb3.png)

This defect is also cause side effect to Build Helper feature and make it doesn't work.

**Please complete the following information:**
 - Version: 1.8.0
 - Provide Log (C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs): not found logs folder in app-1.8.0 folder

**Additional context**
Window 10 Version 2004 OS build 19041.630

**Comment by C1rdec** [comment]
Can you send me your `C:\Users\[user]\AppData\Roaming\PoeLurker\Players.json` you can change the name before sending:

![image](https://user-images.githubusercontent.com/5436436/101201432-bdc67a80-3635-11eb-9b4b-4a85d9e7df28.png)

**Comment by C1rdec** [comment]
Or if you prefer join the discord so we can investigate together.

https://discord.gg/C2FStKgz

**Comment by Xebtria** [comment]
Ran into this issue as well.

I understand that it detects it by level up, but I played one of my characters now to 95 and then leveled another one, found out I dont like it and switched back to the 95 one .... well, let's just say the probability of getting any further levels on that one is quite low. so it now means that all the party leave etc stuff does not work anymore on this character. this is quite "frustrating", considering how used to it I was. 

is there any chance that the add/delete character functionality could be increased a bit in priority?

**Comment by C1rdec** [comment]
You can click the player name to swap.

**Comment by Xebtria** [comment]
I tried, but it doesn't work. I click it, the popup comes, I click the name I want to have, it disappears, I click it again, still the old name shows.

what am I doing wrong?

**Comment by C1rdec** [comment]
Can you send me your `Players.json`

"C:\Users\username\AppData\Roaming\PoeLurker\Players.json"
and give me the player name that you want to be in the list.

**Comment by Xebtria** [comment]
maybe I was not accurate. the character name I want to switch to is available in that popup list, and I do click it seemingly successful, it gives me every impression that the character name has successfully changed, but when I check again, it hasn't.

**Comment by C1rdec** [comment]
Do you have logs?

**Comment by Xebtria** [comment]
where would I want to look for logs for that?

**Comment by C1rdec** [comment]
(C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs)

**Comment by Xebtria** [comment]
No, there is no logs folder there, sadly

**Comment by C1rdec** [comment]
Can you show me a video or connect on discord?

**Comment by Xebtria** [comment]
With the new league on the horizon, were you able to investigate this?

If not, maybe there should be a simple option in the settings window (instead of just being in the context menu of the systray icon, which isn't working for me for unknown reasons) to manually set the character name. I guess it could be so like that manually set character name persists until it gets overwritten by the current (working) method that detects it via the client.txt on level up. just an idea.

**Comment by C1rdec** [comment]
Yeah it's already done ;) There's just a small bug that I'm not able to get my head around it...
I will release it soon so you can play with it :)


![2021-04-12_8-53-16](https://user-images.githubusercontent.com/5436436/114397315-8da36100-9b6c-11eb-8c3d-ef2053cc3e5f.gif)
