### ISSUE TITLE
Program simply won't launch, no error messages either.

### ISSUE THREAD

**Issue by POE-Addon-Launcher** [C1rdec/Poe-Lurker#228]
**Describe the bug**
I launch the program and nothing happens, I then launched it from cmd and no output either, I haven't tried compiling from source and launching but might try if needed.

**Expected behavior**
The program to launch

Downloaded the latest version (14h as of writing)

**Additional context**
I have the required 4.8 .net framwork

**Comment by C1rdec** [comment]
Can you check if you have logs

**Comment by C1rdec** [comment]
Or if you prefer you can join the Discord so we can investigate together:

https://discord.gg/C2FStKgz

**Comment by POE-Addon-Launcher** [comment]
Yikes, bad news it doesn't create any logs either, I'm gonna try on a second pc to see if it's just my main pc that's messed up.

**Comment by C1rdec** [comment]
Can you check if the program is listed in Add/Remove programs of Windows.

**Comment by C1rdec** [comment]
A good place you could check is the `Windows Event Viewer`

**Comment by C1rdec** [comment]
Any updates?

**Comment by POE-Addon-Launcher** [comment]
Been busy with the temp league, I can't get it to work on my main pc, however, it works fine on other pcs, chalk it down as a unique bug on my own pc.
