### ISSUE TITLE
Running on epic

### ISSUE THREAD

**Issue by jjjcbc** [C1rdec/Poe-Lurker#229]
This program can not be uesd when i am Running poe on epic. On my computer，poe.exe was PathOfExile_x64EGS.exe，can you help me to check out why this happen？
Thank you very much!
Good luck!

**Comment by C1rdec** [comment]
I will do a fix.

**Comment by jjjcbc** [comment]
Thank you for reply me！i am chinese ， My English is very pool ，but i will&nbsp;cheer for you！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Cédric Lampron"<notifications@github.com&gt;; 
发送时间: 2020年12月21日(星期一) 晚上10:42
收件人: "C1rdec/Poe-Lurker"<Poe-Lurker@noreply.github.com&gt;; 
抄送: "张海波"<39397436@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [C1rdec/Poe-Lurker] Running on epic (#229)






我会解决的。

—
你收到这个是因为你编写了这个线程。
直接回复此邮件，在GitHub上查看，或取消订阅.

**Comment by C1rdec** [comment]
Fixed in 1.8.4.
