### ISSUE TITLE
Thanks Message

### ISSUE THREAD

**Issue by ngtrungkhanh** [C1rdec/Poe-Lurker#23]
I see thanks message in setting, but how can i use this?
And i think we need a readme.txt

**Comment by C1rdec** [comment]
Yes keep in mind that we are at the beginning of the project. I'll make a wiki when all the feature will be in place.

For your issue regarding the Thanks message, the message will be sent after the trade if you setup any string in the `<add key="ThanksMessage" value=""/>`
