### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by Madlib7** [C1rdec/Poe-Lurker#230]
[SquirrelSetup.log](https://github.com/C1rdec/Poe-Lurker/files/5822145/SquirrelSetup.log)
I get an error when I try to install. I've tried removing the program and deleting the folder in appdata and trying again, but no luck.

**Comment by C1rdec** [comment]
Can you join the discord so we can connect?

**Comment by C1rdec** [comment]
Could not find a part of the path 'C:\Users\IceBox\AppData\Local\PoeLurker\packages\RELEASES'

**Comment by C1rdec** [comment]
This issue seems to be related to Windows N

**Comment by C1rdec** [comment]
Not able to reproduce I will close this for now since we dont have enough information.
