### ISSUE TITLE
Custom Resolution (through Borderless Gaming) prevent the program from working

### ISSUE THREAD

**Issue by Arecurius0** [C1rdec/Poe-Lurker#232]
**Describe the bug**
When starting the Program whilst the resolution and position of  PoE is changed by the Program Bordlerless Gaming  (in my case to 1920x800 on a normal 1920*1080 desktop) i only get to see the "free trial" popup on the managlobe but basically nothing else. I dont see any trade offers or sends or anyhting.
The debug option in the settings show me a green bar where i think the offer elements should be placed.

**To Reproduce**
explained in the description or not applicable

**Expected behavior**
I expected the program to work or throw any error message.

**Screenshots**
Cant really show that nothing is there to see

**Please complete the following information:**
 - Version Lurker 1.8.5 (latest)
 - Provide Log there appears to be no folder orlog created in the "*\AppData\Local\PoeLurker\app-1.8.5" directory
 - Win10 1909 

**Additional context**

**Comment by C1rdec** [comment]
Can you join the Discord so I can investigate with you ?

**Comment by Arecurius0** [comment]
sure i just dont see any discord link anywhere

**Comment by Arecurius0** [comment]
ok so, starting the lurker.exe as admin restored some functionality. I can atleast see incoming traderequests now.
for outgoing trade messages im greeted by this screen though:
![grafik](https://user-images.githubusercontent.com/36637378/105579775-de36c980-5d88-11eb-9766-4d5cdfabec72.png)

**Comment by C1rdec** [comment]
Join the discord so we can investigate further I'm Cedrico.

https://discord.gg/hQERv7K

**Comment by C1rdec** [comment]
The problem was the configuration of "Borderless Gaming tool".
