### ISSUE TITLE
Outgoing trades wont dissaperar after they are finished

### ISSUE THREAD

**Issue by Blekota2k** [C1rdec/Poe-Lurker#234]
Version 1.8.5

When i buying something, the outgoing overlay showes up (the one on the flasks area). Sometimes when i finish the trade, the overlay wont go away, i cant even close it with the red corner button. It just stays here and i have to restart the app.

Edit: when i make another trade and i can see the bar filling animation, i can close it and it will close the previous trade as well.

**Comment by C1rdec** [comment]
Do you find a way to replicate the issue?

**Comment by mortan** [comment]
I have the same issue. Unfortunately I don't know how to reproduce it, but it happens quite frequently if you message multiple people. If I find a way to reproduce it I'll report it here.

**Comment by C1rdec** [comment]
Should be fixed in 1.8.6 let me know if the issue still occurs.

**Comment by Wibbbs** [comment]
I still have this issue all the time. V1.8.8. Outgoing trades open up, the timer goes across, then they never go away. I cant even manually clear them by clicking in the top right corner. Have to restart the program. I decided to just turn off the outgoing trades instead.
