### ISSUE TITLE
Feature request: add ingame location as message variable

### ISSUE THREAD

**Issue by kaeltis** [C1rdec/Poe-Lurker#235]
**Is your feature request related to a problem? Please describe.**
The current way the "Busy" message is implemented only lets you tell others that you are busy, but they have no way of knowing how long they'll have to wait, based on the players location for example. This often causes people to look for a different and more readily available trade.

**Describe the solution you'd like**
It would be awesome if something like `{Location}` and/or `{LocationCategory}` could be added to the message variables, so a message like "`I'm busy right now in {LocationCategory} ({Location}) - I'll send you a party invite soon.`" could be set, which would give others the possibility to estimate how long they'd have to wait.

`{LocationCategory} ({Location})` could then be filled with for example
`Mapping (Iceberg Map)`
`Lab (Uber Lab)`
`Delve (Delve Depth 123)`
`Heist (Contract: Records Office)`
`Questing (The Chamber of Sins Level 2)`
`Hideout (Alpine Hideout)`
...

**Comment by C1rdec** [comment]
There is no {LocationCategory}  that I could parse but regarding the location I can add it easily.

**Comment by kaeltis** [comment]
Awesome! :)
Maybe {LocationCategory} could be implemented using a small Lookup Table based on {Location}?

(Just guessing the Location Names here)
.* Map -> Mapping
.* Lab -> Lab
Depth .* -> Delve
Contract: .* -> Heist
.* Hideout -> Hideout
Everything else -> Questing

**Comment by C1rdec** [comment]
There is no map, lab or depth in the name of the instance

![image](https://user-images.githubusercontent.com/5436436/105897614-65cd4400-5fe6-11eb-9b19-87d5ce1f1608.png)

**Comment by kaeltis** [comment]
Oh, my bad, no Idea where I got that Idea from then, sorry!

**Comment by C1rdec** [comment]
Added in 1.8.7 :)

**Comment by kaeltis** [comment]
Thanks! :)
