### ISSUE TITLE
Lurker buttons do not work if the chat is open

### ISSUE THREAD

**Issue by xuvvy** [C1rdec/Poe-Lurker#236]
**Describe the bug**
If the chat is open, then clicking the button to invite to party or invite to trade won't send an invite.

**To Reproduce**
1. Have chat open and receive an invite or receive an invite and then open chat
2. Click on the button
3. No invite sent

**Expected behavior**
Invites should be sent out regardless of chat being open or not.

**Please complete the following information:**
Version 1.8.5

**Comment by C1rdec** [comment]
There is no way to detect if the chat is open.

Can't be fixed.
