### ISSUE TITLE
Auto-whisper sometimes doesn't work until I leave the party

### ISSUE THREAD

**Issue by Tartarus762** [C1rdec/Poe-Lurker#239]
Sometimes when using the auto-whisper functionality, no message will be sent.
The message will immediately get sent upon leaving a party, for example, if I manually sent the message and completed the trade. This typically results in messaging the person I just traded with for the item I just traded for.

Reproduction steps:

1. Have poe lurker open with auto whisper turned on
2. Locate desirable item on a trade website
3. Click the "whisper" button or otherwise copy the whisper message

I would expect that if I click the whisper button on the official trade website that poe lurker will send a whisper message immediately and will not send a message upon leaving a party.

Version: 1.8.8
No logs directory in the specified location (everything else appears to be present)

I haven't observed a pattern, for example, it does not appear to matter which language the whisper is in or how long it is or anything of the sort.

This only happens maybe 10-15% of the time and I can circumvent the issue by manually whispering then copying some unrelated text.

**Comment by C1rdec** [comment]
Leaving the party does not affect Poe Lurker in any way are you sure about this?

**Comment by Tartarus762** [comment]
Hi,

I am not sure at all that leaving the party has anything to do with it. 
I do observe that every time the auto-whisper fails, the whisper will be sent immediately upon leaving the party.

Co-incidence? Possibly.

Next time I observe the issue, I will try and record a video of it happening.

**Comment by C1rdec** [comment]
I'll close this for now. If you encounter the issue again let me know.

**Comment by Tartarus762** [comment]
Unfortunate timing since I just captured an example.

Please see this video:

https://youtu.be/efi1gjPNNac

**Comment by C1rdec** [comment]
Do you use any other third party app for POE?

**Comment by Tartarus762** [comment]
I use Awakened Poe Trade, however, I only have the hideout bind set.

I did wonder if it was related, but it seemed unlikely since the two tools don't appear to perform the same functions.

I don't use any additional third-party tools that interact with the game.
