### ISSUE TITLE
Add "Still Interested" command.

### ISSUE THREAD

**Issue by tamaroth** [C1rdec/Poe-Lurker#24]
Sometimes you leave your PC while PoE is still running. You then come back 5-10 minutes later just to see that someone was trying to buy something off of you. At the moment you must manually message that person whether they are still interested.

Some other trading apps (TraderForPoe, which is unfortunately discontinued) have a button for asking whether that person is still interested. I think it would be a great addition to PoE-Lurker, too.

**Comment by C1rdec** [comment]
Yass how do you see it ?

**Comment by C1rdec** [comment]
Ctrl + alt Click ?

**Comment by tamaroth** [comment]
Yeah, sounds reasonable. Similar to `just sold` option.

**Comment by C1rdec** [comment]
Will go this route for now

**Comment by C1rdec** [comment]
In 1.2.1
![image](https://user-images.githubusercontent.com/5436436/72127660-63963a00-333e-11ea-8b32-1193f0cd0eb4.png)
