### ISSUE TITLE
Changing the Notification Sound

### ISSUE THREAD

**Issue by ThatGuyEUW** [C1rdec/Poe-Lurker#240]
Love the tool so far, the only thing I would like to have a distincitve notification sound. I often have music/stream/discord chat while playing and dont really notice when getting a trade offer.

Cheers
That GUy

**Comment by C1rdec** [comment]
Will do :)

**Comment by C1rdec** [comment]
@ThatGuyEUW 

![image](https://user-images.githubusercontent.com/5436436/107472233-9495ff00-6b3c-11eb-8222-808aabdd0e05.png)
In the next release.

**Comment by C1rdec** [comment]
Added in 1.9.0.
