### ISSUE TITLE
LifeBulb messages get stuck sometimes

### ISSUE THREAD

**Issue by mortan** [C1rdec/Poe-Lurker#242]
**Describe the bug**
It is possible for the life bulb messages to get stuck without a corresponding Tradebar item.

**To Reproduce**
1. Write yourself a trade offer: @SpamSlowClearspeed Hi, I'd like to buy your 1 "Offer 1" for my 50 Chaos Orb in Ritual.
2. Set the offer active by pressing ALT + LMB (notice how SetActiveOffer in TradeBarViewModel inserts the Offer in _activeOffers)
3. Left click (LMB) on the offer to invite the player. This calls AddActiveOffer in TradeBarViewModel, notice how this also inserts the offer in _activeOffers
4. => The offer is now duplicated in the _activeOffers collection. Pressing the remove button on the offer will only remove it once from the _activeOffers collection. This will lead to a stuck message on the life bulb.

**Expected behavior**
There should be no stuck messages on the life bulb you can't get rid off.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1070913/107073687-f3c7dc80-67e7-11eb-8eab-89451a10b720.png)

**Please complete the following information:**
Version 1.8.8

**Comment by C1rdec** [comment]
Thanks man :)

This fix will be in 1.8.9
