### ISSUE TITLE
Outgoing whisper bars sometimes get stuck

### ISSUE THREAD

**Issue by Rottenbeer** [C1rdec/Poe-Lurker#245]
Sometimes the bars get stuck and don't move anymore and I need to restart the tool to get rid of them.

![image](https://user-images.githubusercontent.com/2014982/107852279-27ba8780-6e10-11eb-89b8-6fbd7a76df51.png)

Sadly I don't know how to reproduce this :/
I'm using the latest version 1.8.8

**Comment by hmcgonig** [comment]
This has been happening to me as well for a couple weeks now. I've noticed that sometimes completing another trade gets the stuck bars to go away, but most of the time I just restart the app.

**Comment by C1rdec** [comment]
Do you guys use Alt+Click to make the offer active?

**Comment by Rottenbeer** [comment]
No why?
I use the serach bar though.

**Comment by Rottenbeer** [comment]
Setting active offers only works on incoming trades, not outgoing according to the cheat sheet, right?

**Comment by C1rdec** [comment]
No you can set active offer on outgoing to.

The guide needs to be updated.

**Comment by Rottenbeer** [comment]
Is it required to do this?

**Comment by Rottenbeer** [comment]
How is it supposed to work? It also hangs for me if it set the active trade before trading.

**Comment by C1rdec** [comment]
Did you find a way to reproduce the issue constantly?

**Comment by Rottenbeer** [comment]
For me it's pretty often the case that it hangs, but I don't know how to reproduce it.
I'm not using the Steam Client but the native one, if this matters?

**Comment by C1rdec** [comment]
No it doesn't matter. Try to find a way to reproduce the issue because I'm not able to reproduce it on my side...

**Comment by Rottenbeer** [comment]
1) Whisper multiple people
2) Search for someone's name in the search bar
3) Wait for the other bars to clear
4) finish the trade with the guy you searched for
5) The outgoing trade window should be stuck like this:
![image](https://user-images.githubusercontent.com/2014982/109386917-4c2d5e00-78fe-11eb-96ae-101b79e1f1d0.png)

**Comment by Rottenbeer** [comment]
Another way to reproduce this is to not click on the "trade this player" icon on the health globe (e.g. when they trade you)

**Comment by hmcgonig** [comment]
I'm not exactly sure how to reproduce this, but I've noticed it happens very frequently when whispering many traders who dont respond. I'll whisper 5-10 non-responsive currency traders, one will finally respond, I complete the trade and notice that my bars are stuck. Then I have to restart the app to get them to clear. If we can't track this down, could we get a "relaunch" button or something as an option on the tray icon? That would at least make mitigating this a little easier.

**Comment by C1rdec** [comment]
Yeah I'm still trying to get my head around this one...

**Comment by EThaNol2005** [comment]
He, i have the same problem more then once a day.
When i exit the tool and start it again, it say another instance is running. But no task is running in my taskmanager.

**Comment by C1rdec** [comment]
Did you guys has been able to reproduce this issue with the latest build?

**Comment by EThaNol2005** [comment]
Not happend anymore. But i don't play this much at this moment.

**Comment by superness** [comment]
This happens all the time for me, I have to terminate Lurker and restart it several times a day
