### ISSUE TITLE
Poe-lurker sometimes stops popping

### ISSUE THREAD

**Issue by Witnessthis** [C1rdec/Poe-Lurker#246]
I've had an issue happening alot where poe-lurker stops popping up for incoming trades. I'm using multiple monitors and I believe it happens sometimes when I'm changeing my focused window and alt + tabbing etc. The only fix I've come up with is to restart the app itself every time it happens.

**Comment by C1rdec** [comment]
Enable debug mode you will see green box if the overlay is there. 

One thing I can see is that you are getting whispered by Korean player and since the Korean Poe client is not logging into the `client.txt` Poe Lurker cannot pick it up.

**Comment by Witnessthis** [comment]
I tried enabling debug now that it happend again, and I didn't see the green colors until I restarted the app.

**Comment by C1rdec** [comment]
Di you have any logs?

Can you try always visible?
