### ISSUE TITLE
Need a highlight feature for similarly named items

### ISSUE THREAD

**Issue by palme1337** [C1rdec/Poe-Lurker#248]
**Is your feature request related to a problem? Please describe.**
As a seller, I find it hard to locate items like cluster jewels so it would be nice if the application highlighted the area it should be in (top # left # is not helpful)

**Describe the solution you'd like**
Highlight an area. Like mercury trade

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by C1rdec** [comment]
There's alt + f 

![image](https://user-images.githubusercontent.com/5436436/109905465-d5c98c80-7c6c-11eb-9f35-cda445b0315b.png)
