### ISSUE TITLE
Not working for users with chines character

### ISSUE THREAD

**Issue by Psychogenius136** [C1rdec/Poe-Lurker#249]
When getting treade request from user  that his name is in chines characters Lurker wont recognize it as trade

**Comment by Psychogenius136** [comment]
You shoul add in description of program that it not workling becouse  korean client it requireing by koren law as that is offcial state of GGG 
https://www.pathofexile.com/forum/view-thread/2567280/page/4

**Comment by C1rdec** [comment]
#4
