### ISSUE TITLE
Auto-whisperer would be a great addition

### ISSUE THREAD

**Issue by leet0rz** [C1rdec/Poe-Lurker#25]
Would be great to have an auto whisperer like traderforpoe/trade companion has.

**Comment by C1rdec** [comment]
You will need to elaborate 😅

**Comment by C1rdec** [comment]
Auto whisler will afk?

**Comment by leet0rz** [comment]
I am messaging you on reddit currently, where would you like the messages? hehe
Res:
https://i.imgur.com/VJ6mvHQ.png

**Comment by C1rdec** [comment]
Ok ill close this issue...
