### ISSUE TITLE
CTRL+Shift+Click triggers Lurker's command when transferring items to ignore affinity in stash

### ISSUE THREAD

**Issue by genjiarmorxii** [C1rdec/Poe-Lurker#252]
**Describe the bug**
When using CTRL+Shift+Click to move items into a stash ignoring affinity the inventory window will either close or open depending on it's current state. 

**To Reproduce**
1. Bind inventory to "C".
2. Go to your stash and grab an item that has a stash affinity and put it into your inventory.
3. CTRL+Shift+Click the item into another tab.

**Expected behavior**
Lurker doesn't trigger while it's not actively being used. window doesn't close or open depending on it's status. 

**Video**
https://clips.twitch.tv/FragileNaiveRadicchioYouDontSay-p1ejBTV5K0CpW82g

**Please complete the following information:**
 - Version v1.9.3

**Comment by Ryanc13** [comment]
Having the same issue doesn't allow you to repeatedly ctrl + shift + click items into your stash. Broke on newest update was working fine in 1.9.2

**Comment by C1rdec** [comment]
This issue is fixed in dev.

**Comment by C1rdec** [comment]
Are you guys using any other trade tool? (Awakened Poe Trade, Poe Overlay)

**Comment by C1rdec** [comment]
Should be fixed in 1.9.4 let me know if this fix your issue.
