### ISSUE TITLE
Duplicate messages

### ISSUE THREAD

**Issue by Fugaz1** [C1rdec/Poe-Lurker#254]
**Describe the bug**
Sending messages to buyer is not working correctly. When clicking whisper on poe trade it should send whisper in game right away. More often than not it will not do it, when you send it manually and complete trade then it will send it.

**To Reproduce**
1. Go to poe trade website.
2. Click whisper.
3. Nothing will happen.
4. Paste whisper manually in poe.
5. Complete trade up to "thank you" message.
6. Whisper from 2. is sent now.

**Expected behavior**
1. Go to poe trade website.
2. Click whisper.
3. Whisper is sent.

**Screenshots**
![image](https://user-images.githubusercontent.com/759426/115305370-7ebd3f80-a166-11eb-9877-d91d3568c361.png)

**Please complete the following information:**
 - Version 1.9.3
 - Provide Log: did not found any log at that location

**Additional context**
Starter happening sometime around 3.13.

**Comment by C1rdec** [comment]
Can we connect on discord?

**Comment by Fugaz1** [comment]
Sure, Fugazi#4748

**Comment by C1rdec** [comment]
Can you join Poe Lurker discord? 

https://discord.com/invite/hQERv7K

**Comment by C1rdec** [comment]
After investigation we found that [Mouse Without Border](https://www.microsoft.com/en-us/download/details.aspx?id=35460) whas the culprit.
