### ISSUE TITLE
Elements misplaced if PoE Window is resized using PowerToys/FanzyZones

### ISSUE THREAD

**Issue by bvolkmer** [C1rdec/Poe-Lurker#255]
**Describe the bug**
If running PoE in windowed mode, and the window is resized using Microsofts [PowerToys](https://github.com/microsoft/PowerToys) feature called "FancyZones", the Elements of PoE-Lurker are misplaced/scaled. I.e. the home button is left below on another screen. This is not consistent. Very rarely it works as expected. Sometimes it is not visible at all. Sometimes in the window but misplaced and roughly at the scale before resizing the window. (I have an unusual screen setup. That as that might be related I added all screen screenshots at the end.)

**To Reproduce**
1. Install/Enable FanzyZones in PowerToys
2. Resize window by dragging and holding shift, selecting a zone.
3. Elements are now displaced

**Expected behavior**
Right placement of elements, like when manually resizing/moving the window.

**Screenshots**
<details><summary>Screenshots</summary>
<p>
Fullscreen (working):
![Fullscreen (working)](https://user-images.githubusercontent.com/7070761/115305224-4d447400-a166-11eb-845b-7ad73105740d.png)
Manually Scaled (working):
![Manually Scaled (working)](https://user-images.githubusercontent.com/7070761/115305342-71a05080-a166-11eb-99d8-a5f530bf68df.png)
FanzyZones scaled from a smaller window:
![Screenshot 2021-04-19 232623](https://user-images.githubusercontent.com/7070761/115305493-af9d7480-a166-11eb-8869-772685b72182.png)
</p></details>

**Please complete the following information:**
 - PoE-Lurker version 1.9.3
 - PowerToys version v0.35.0
 - Log is empty

**Comment by C1rdec** [comment]
Not supported sorry
