### ISSUE TITLE
Poe-Lurker crashes

### ISSUE THREAD

**Issue by ekunholy** [C1rdec/Poe-Lurker#257]
**Describe the bug**
PoE Lurker doesn't show overlay over PoE window, don't react to whispers, and crashes when trying to access Settings from tray icon. During crash no text errors or popup windows are shown.

**To Reproduce**
1. Start PoE
2. Start PoE Lurker
3. No overlay over PoE
4. RMB on icon in tray, click Settings
5. PoE Lurker crashes with no errors

**Expected behavior**
Overlay should be seen over PoE window, and opening Settings shouldn't crash the program.

**Screenshots**
https://i.imgur.com/RNJidjz.jpeg

**Please complete the following information:**
 - Version 1.9.2
 - Provide Log - [2021-04-21.log](https://github.com/C1rdec/Poe-Lurker/files/6349524/2021-04-21.log)

**Additional context**
Was using PoE Lurker for over 1 year with zero issues until last week (3.14 poe release).

**Comment by m4xolotl** [comment]
Same issue here. Been previously using Lurker for at least a year with no issues


Poe Lurker and PoE are running as administrator
heres my log 


[2021-04-21.log](https://github.com/C1rdec/Poe-Lurker/files/6349615/2021-04-21.log)

**Comment by C1rdec** [comment]
Fixed in 1.9.3
![image](https://user-images.githubusercontent.com/5436436/115744943-01115380-a361-11eb-9800-73349f7d87dc.png)
