### ISSUE TITLE
Not working in windowed mode

### ISSUE THREAD

**Issue by leet0rz** [C1rdec/Poe-Lurker#26]
I am playing in a resized widescreen window and the program is not showing up or anything while playing like this.

**Comment by C1rdec** [comment]
Resized widescreen?

**Comment by C1rdec** [comment]
What's the Windows Scaling option on your monitor ?

**Comment by leet0rz** [comment]
1928x901

**Comment by leet0rz** [comment]
Can I still answer here? Please dont close it so fast lol.

**Comment by C1rdec** [comment]
Yes you can I closed this issue because you open 2 issue and a reddit comment

**Comment by C1rdec** [comment]
Join my discord so we can trouble shoot your issue

**Comment by leet0rz** [comment]
Where is the discord link? I cannot find it anywhere.

**Comment by C1rdec** [comment]
In the read.me there is a big discord button

**Comment by C1rdec** [comment]
![image](https://user-images.githubusercontent.com/5436436/72077494-55580780-32c5-11ea-9d74-a364bfdd3807.png)
