### ISSUE TITLE
Cant auto-whisper

### ISSUE THREAD

**Issue by AnhPr0** [C1rdec/Poe-Lurker#262]
**Describe the bug**
I cannot auto-whisper players through POE trade chat. I've tried reinstalling it and tried to use older version of POE Lurker up to 1.9.3, reinstalling, ensuring "auto-whisper" is enabled, ensured i'm in window fullscreen mode, but I cannot auto-whisper players. This is first time this has happen and it has worked in the past since 3.13.

**Comment by C1rdec** [comment]
Do you know what's the auto whisper feature?
