### ISSUE TITLE
Can't change settings

### ISSUE THREAD

**Issue by gotya96** [C1rdec/Poe-Lurker#266]
**Describe the bug**
Program settings wiped randomly, can't get into settings again without program shutting down. Program run and works ingame, but i can't change settings.

**To Reproduce**
1. Go to 'Task bar'
2. Click on 'Icon->Settings = shutdown of program.'
3. No error.

**Expected behavior**
Being able to change settings.

**Screenshots**
-

**Please complete the following information:**
 - Version 1.9.11
 - Provide Log -

**Additional context**

**Comment by C1rdec** [comment]
You have logs for sure

**Comment by gotya96** [comment]
[2021-05-18.log](https://github.com/C1rdec/Poe-Lurker/files/6503668/2021-05-18.log)
Yes sorry.

**Comment by C1rdec** [comment]
Can you send me this file:

"C:\Users\\[user]\AppData\Roaming\PoeLurker\Builds.json"

**Comment by gotya96** [comment]
When i try to attach it says "We don't support that file type"
Uploaded it to mediafire - https://www.mediafire.com/file/yanryqtgfkro1n5/Builds.json/file

**Comment by C1rdec** [comment]
fixed in 1.9.12.

You had an invalid Path of Building build.

![image](https://user-images.githubusercontent.com/5436436/118898128-d7086e00-b8d9-11eb-942d-f7ae197c43bf.png)
