### ISSUE TITLE
Auto update fails

### ISSUE THREAD

**Issue by Barragek0** [C1rdec/Poe-Lurker#267]
When clicking the update icon at the bottom right, the program tries to update, but i'm guessing it doesn't close itself correctly as it says 'Another instance is running' then opens the github releases page for manual download. I then have to close it via process lasso / task manager to be able to open it again.

This same thing happens with multiple programs so I think it might be a windows 10 bug with closing out applications.

If this is a windows 10 issue, as a workaround this command could be used via command prompt by the app to force close all instances of the app: 'taskkill /im poelurker.exe', then run the updater under a different executable name, so that it doesn't get killed by that command.

**Comment by C1rdec** [comment]
This is done by a third party dll (Squirrel) be sure that there's no stuck process. 

I would suggest to uninstall to do a clean install.
