### ISSUE TITLE
Auto-kick removes players from party when trading with a vendor

### ISSUE THREAD

**Issue by OriginalThing** [C1rdec/Poe-Lurker#268]
**Description**
When you trade with a vendor, while waiting for buyer, the auto kick feature will kick the player from your party before you are able to initiate a trade. This can happen before they even enter your instance.

**To Reproduce**
1. Invite player for incoming trade
2. Sell items to a vendor
3. Player is kicked

**Expected behavior**
Trading with a vendor should not kick a player from the party before a trade can be initiated.

 - Version v1.9.12

**Comment by C1rdec** [comment]
This will not be fixed. When you invite some one to your party and you trade with a vendor there's a "trade accepted" logged in the client.txt. In a earlier version Poe Lurker was kicking buyer only were the offer was in the "Trade state" (Green) but multiple users had the issue that they were trading manually and they needed to kick manually the buyer.

Either option if you want to use the auto kick feature you'll need to learn to not vendor your items while in the trading sequence.

**Comment by OriginalThing** [comment]
Surely there is a solution that would appease both sets of players.

What if with the trade accepted log message returned to only kicking while in "Trade state", if in the "Invited state" (blue) if the red corner to dismiss the trade with auto-kick enabled then that would also kick the buyer from the party. Then manual traders still have an easy way to kick players from their party and is likely a step they were already used to doing. It would also be useful for no show trades, you can dismiss them trade and kick them from the party with 1 click.

Or perhaps shift clicking the trade (or some other combination) will kick the buyer from the party (and maybe also dismiss the trade).

Or provide an option to bring a trade back from the "grave" so that mistakes could be undone

Or provide an option to choose which method to use for auto kick, kick only in trade state, kick when trade accepted (including vendor trade), then people can choose which behavior they prefer.
