### ISSUE TITLE
few things id like to be added

### ISSUE THREAD

**Issue by SchmutzigerStefan** [C1rdec/Poe-Lurker#27]
first of all, i love poe lurker!

few important things for me, that are missing atm:

- the tooltip on mouseover that shows the item name should pop up instantly and the textsize should be way bigger or adjustable

- the price tag bottom right is way too small too (at least for me on wqhd)
- thank you button!! (!!)

- "sold" button

- add group kick on close (when we press the red corner for closing the overlay)

**Comment by C1rdec** [comment]
There is a thank you functionality you need to set a message in the application.config.
![image](https://user-images.githubusercontent.com/5436436/72011352-a3b6c900-3227-11ea-8203-67fa44559b97.png)

If you used the Setup.exe to install the application the file is located in `C:\Users\[user]\AppData\Local\PoeLurker\app-1.2.0`

Regarding the "Sold Action" can you Ctrl + Click on the main action

The buyer will be kick of the party at the end of the trade offer if you send the trade with the button.

**Comment by SchmutzigerStefan** [comment]
> What version are you using?
> 
> There is a thank you functionality you need to set a message in the application.config.
> ![image](https://user-images.githubusercontent.com/5436436/72011352-a3b6c900-3227-11ea-8203-67fa44559b97.png)
> 
> If you used the Setup.exe to install the application the file is located in `C:\Users\[user]\AppData\Local\PoeLurker\app-1.2.0`
> 
> Regarding the "Sold Action" can you Ctrl + Click on the main action
> 
> The buyer will be kick of the party at the end of the trade offer if you send the trade with the main action.

okay the kick and sold is clear now :) i just dont get how to send the "thank you" :)

**Comment by C1rdec** [comment]
You need to setup a "ThanksMessage" in the PoeLurker.exe.config

![image](https://user-images.githubusercontent.com/5436436/72012301-b4683e80-3229-11ea-9b50-a6b54ca6a39d.png)

**Comment by SchmutzigerStefan** [comment]
aight, i just restarted the porgram, now its working just fine!
regarding the delay on the pop up on mouseover and the text sizes, can i adjust this myself or is that too complicated?

**Comment by C1rdec** [comment]
If you Click on the main action you should have a pop with no delay.

![image](https://user-images.githubusercontent.com/5436436/72012987-fc3b9580-322a-11ea-9d4f-d0e8844d9fac.png)

**Comment by SchmutzigerStefan** [comment]
correct but this includes the invite at the same time ;)

**Comment by C1rdec** [comment]
And you have an issue with that? Why do you want to know what's the item if it's already for sale?

**Comment by SchmutzigerStefan** [comment]
yes because api is slow so often and i dont want to invite ppl just to tell em that the item is already sold^^

**Comment by C1rdec** [comment]
Good point

**Comment by C1rdec** [comment]
Can you log an Issue regarding the possibility the locate the item without inviting the buyer
