### ISSUE TITLE
Wrong trade is closed

### ISSUE THREAD

**Issue by ofbeaton** [C1rdec/Poe-Lurker#271]
**Describe the bug**
If I alt-click on an incoming trade because one person joined my hideout first, to say select the 2nd incoming trade and process that one first, once I complete the trade with the person and it auto closes / kicks, it will always close the first incoming trade even if I had manually alt-click selected the second one.

I would expect the addon to close the active trade. 

**To Reproduce**
1. Have two incoming trades
2. alt-click the second
3. trade the second person
4. first trade gets closed, you must now manually do the first trade without poe lurker

**Expected behavior**
I would expect it to close the active trade after I trade someone. That way I can go look up the next person. I don't mind if it re-selects the first trade again.

**Please complete the following information:**
 - Version 1.9.12

**Additional context**
I can see that you might disagree, some people may gather all items for everyone in their h/o at once then process them one at a time in order of the bucket, but I would think most people aren't currency sellers and are just handling 2-4 trades and are not doing this.

I haven't been paying attention if the auto-kick will also kick the wrong person from the party. It might...

**Comment by C1rdec** [comment]
Only active trade are getting "closed" by poe lurker.

**Comment by ofbeaton** [comment]
For the record I /think/ I finally figured out what was happening here. When having a large collection of trades, and trading with a korean client which is not part of the addon, the addon will auto close the active trade even though it is not the trade I am doing (with the Korean client).

If you have multiple pending trades it can cause a whole cascade of problems with the wrong people getting whispered, etc.

I'll re-iterate my idea from another issue which would have a "no-op" button you could make active, at the start of the trade tray whenever it is visible, which would let you deal with both korean clients and vendoring properly.

Another possible idea which may work, is to be able to alt-click a button to "deactivate" it, so you no longer have an active trade. This is less intuitive, but less cluttered UI wise.

I'm sure there are other ways to solve this too, but right now the situation is very frustrating unfortunately.
