### ISSUE TITLE
Vendor trade suggestion

### ISSUE THREAD

**Issue by ofbeaton** [C1rdec/Poe-Lurker#272]
**Is your feature request related to a problem? Please describe.**
Sometimes I come out of my map and my inventory is full of 6s, and my dump tab is full or I'm not using one. I want to vendor the 6s before trading the person to make room, but if I do that, the "trade accepted" chat message will make the addon close the active trade and kick them. It's happened to me so many times.

**Describe the solution you'd like**
I'd like a "vendor" button I can alt-select that will make it ignore not close trades when I trade. so I can alt-select it then do my vendoring of 6s, then alt-select the person and resume trading.

**Describe alternatives you've considered**
right now my workaround is to try and find an empty spot in my stash for something out of my inventory to make room, sometimes even swapping the item. This can be icky when I don't remember where I stashed it.

I considered suggesting that it shouldn't close trades where it doesn't know the person is in my HO, but when you're mapping they often join your HO before you get out of your map, so this would make a common use case feel really bad.

**Comment by C1rdec** [comment]
There's no good answer at first the tool kicked only when the offer was in "traded" state but alot of player was trading manually.

I'll try to come up with something.

**Comment by ofbeaton** [comment]
right a "ignore" button you can alt-select would solve both the case of the vendor and the manual trades. Especially if the special character names cannot be solved.
