### ISSUE TITLE
high contrast tab name feature request

### ISSUE THREAD

**Issue by ofbeaton** [C1rdec/Poe-Lurker#273]
**Is your feature request related to a problem? Please describe.**
When trying to find the item you're looking for, the tab name is displayed over the health globe. However I often find if you have energy shield the white text is hard to read.

**Describe the solution you'd like**
 I would like something more high contrast, perhaps with a black border around the text?

**Describe alternatives you've considered**
Right now I squint a lot sometimes, or I will sometimes hover over the trade card to see the tab name in the tooltip (take a few seconds to appear), or hit ENTER and scroll up to find the trade in the chat.

**Additional context**
Example
![image](https://user-images.githubusercontent.com/1781089/120059093-2d358980-c01d-11eb-9a7a-761b0d03d61a.png)

**Comment by C1rdec** [comment]
Can you please look into the option.

![image](https://user-images.githubusercontent.com/5436436/120080990-25abca00-c089-11eb-9a5f-624b5f3937ae.png)

**Comment by ofbeaton** [comment]
Ah, not quite what I was looking for in terms of making higher contrast text, as borders are super important for that, but thank you. This is an acceptable workaround. 

But if it's not too hard I would encourage you to consider adding a border thickness/colour option as well.

**Comment by ofbeaton** [comment]
Actually, after playing with it I find it impossible to pick a colour that stands out on a dark red background (the blood), the gray of life reservation, and the light blue/white of energy shield.

I think the only good solution would be to allow us to specify a border colour and thickness for readability.

Thank you for this option though.
