### ISSUE TITLE
customization tab name length feature request

### ISSUE THREAD

**Issue by ofbeaton** [C1rdec/Poe-Lurker#274]
**Is your feature request related to a problem? Please describe.**
Because of the limitations of the GGG tabs, if you price a whole tab the same price you can't have a unique name. So it's hard to differentiate two 5c tabs. Many of use fractions on the price to identify tabs, for example 4.9905 would be the "5th" 5c tab, and "4.9906" would be the "6th" 5c tab. But in poe-lurker when it displays what tab to find it, the name is cut off at "4.99"

The method was further popularized by streamers like CuteDog so I can't be the only one who already, or now, does this.

**Describe the solution you'd like**
I'd like a configuration option to be able to specify how many characters to display for the tab name. So I could display the whole "4.9906" name.

**Describe alternatives you've considered**
Right now I usually hover over the trade card and wait several second for the tooltip to display so I can figure out which tab it is actually in, or I will hit ENTER and look at the chat to read it there.

**Additional context**
![image](https://user-images.githubusercontent.com/1781089/120059154-a0d79680-c01d-11eb-89c6-33d45a2e8c6c.png)

**Comment by C1rdec** [comment]
Not possible...

**Comment by ofbeaton** [comment]
If I may ask, how come it is not possible? the full tab name is in the whisper and in the client.txt, and you already display it in the tooltip...

You're obviously shortening it programmatically.

Anyways, thank you for considering it.

**Comment by C1rdec** [comment]
Enable debug mode you'll see the size of the overlay please stop creating issues.

**Comment by ofbeaton** [comment]
Would it be possible to increase the size of the overlay to make more room?

I was creating issues for legitimate issues I had with the addon from months of use and suggestions I thought would help me and others.

But clearly this is not welcome. Thank you very much for the addon and have a good day.

**Comment by C1rdec** [comment]
What's not welcoming it's the issue spamming. Just take the time to look into closed issues.

**Comment by ofbeaton** [comment]
OK, sorry for wasting your time then. I will use the search feature more extensively in the future.

Thank you again for the great addon, I would not want to give input if I didn't already find it invaluable and of a high quality.

**Comment by C1rdec** [comment]
There's the discord for suggestions
