### ISSUE TITLE
Game still crashing when i use it even after the last patch

### ISSUE THREAD

**Issue by SaikoMVP** [C1rdec/Poe-Lurker#277]
Basically when i click the icon to trade to someone game just crash, it mess up with my resolution as changing my settings from windowed full screen 1080p to windowed with a random resolution.

I did uninstall and installed again no change.

**Comment by C1rdec** [comment]
Are you fullscreen?

**Comment by SaikoMVP** [comment]
No i play in windowed fullscreen

**Comment by C1rdec** [comment]
Poe Lurker cannot change your resolution something is fishy here

**Comment by SaikoMVP** [comment]
I havent change the resolution or mode in a year, the app was working wonderfull till last POE patch since then if i click the icon basically my game goes crazy start to freeze and my resolotion get changed till the game crash.

Once the game crash i go back in and i have to set up everything again, if i dont press the icon for trades that doesn happen.

**Comment by C1rdec** [comment]
Pressing the icon button tells windows to set poe in focus your issue is windows related.

**Comment by SaikoMVP** [comment]
I havent touch my windows at all, i only use the computer to play i dont understand how can be windows when was working all ok till 2 days ago

**Comment by C1rdec** [comment]
Like I said Poe Lurker cannot change the resolution of the game. 
There's an issue when you remove the focus of Poe and give it back.

**Comment by SaikoMVP** [comment]
At the moment im running it as administrator and see how it goes
