### ISSUE TITLE
So instead of try to help me you just close my report, wtf

### ISSUE THREAD

**Issue by SaikoMVP** [C1rdec/Poe-Lurker#279]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Version [e.g. v1.3.0]
 - Provide Log (C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs)

**Additional context**

**Comment by C1rdec** [comment]
First of all Issues are not meat to be used like that that will be your last warning.
Secondly, I offer my help to investigate the issue but you seems to be a person that dont wants to be helped.
