### ISSUE TITLE
Is it possible to disable UAC when launching?

### ISSUE THREAD

**Issue by GamerKingFaiz** [C1rdec/Poe-Lurker#280]
**Is your feature request related to a problem? Please describe.**
When launching Poe Lurker, it always has a UAC (User Account Control) prompt.

**Describe the solution you'd like**
Would it be possible to disable this prompt so that it just launches without needing to accept the UAC?

**Comment by GamerKingFaiz** [comment]
After restarting my computer and launching Poe Lurker again today it didn't need a UAC prompt to launch. I'll close this out for now.

**Comment by C1rdec** [comment]
Poe Lurker detect if he needs to run in admin to have the rights to read. 
My guess is that Path of Exile is not running as the same windows user of Poe Lurker.
