### ISSUE TITLE
App sometimes loses what character im on and won't show popup

### ISSUE THREAD

**Issue by sharmaalex1** [C1rdec/Poe-Lurker#282]
Hi,

I don't know how else to describe it but sometimes the list of characters that show up in the windows pull up menu in the bottom right will show a character im not currently logged into and the app wont function properly. maybe something like a refresh keybind could help this problem? Let me know if there is anything I can provide

**Comment by C1rdec** [comment]
There's no way for Poe Lurker to detect the character change.
Poe Lurker will swap character only when he detect a character lvl event.

**Comment by sharmaalex1** [comment]
Would it be possible to add some sort of keyboard shortcut to manually refresh it? I dont know how else to make that happen and restarting the program doesn't always fix it for me. Thank you for the reply

**Comment by C1rdec** [comment]
You need to set it manually
