### ISSUE TITLE
Won't auto-kick: Target not a party member

### ISSUE THREAD

**Issue by Kataklysm83** [C1rdec/Poe-Lurker#284]
Recently getting the error that the target of this operation was not a party member, when a trade is complete.

Reproduced by reaching out to someone to buy from them, and not auto-kicking myself when trade is accepted.

![screenshot-0017](https://user-images.githubusercontent.com/47700966/128120807-a8a57a24-bf51-44cc-9197-2b5b32faa5cc.png)

 - Version 1.10.3
 - Log file not found

**Comment by C1rdec** [comment]
This is because your current character was not set as the one you were using.

When you are buying from some one Poe Lurker will try to kick YOU out:

/kick [yourCharacter]

**Comment by Kataklysm83** [comment]
Where would I change this?

**Comment by C1rdec** [comment]
Right click the tray icon.
