### ISSUE TITLE
[Request] Invite Message

### ISSUE THREAD

**Issue by livejamie** [C1rdec/Poe-Lurker#286]
MercuryTrade and others have support for a message that's sent with the outgoing invite

By default it's something like "Ready for Pick Up {ItemName} - {ItemPrice}"

Would be nice to have that option with Lurker

**Comment by C1rdec** [comment]
I wont implement this sorry...  Since this is against TOS  (Multiple server actions for 1 client action). I know that there is already some features that are against TOS and I added an option to disable them.

I really want to limit those and I found this feature not worth it.
