### ISSUE TITLE
App Doesn't Seem to Work

### ISSUE THREAD

**Issue by Kohtas** [C1rdec/Poe-Lurker#295]
It doesn't seem to be working for me, I have .NET Framework 4.8 installed as well as the app and I'm getting no popups when people whisper me for trade, no alert sounds and menus don't open when I have the Remaining Monsters and Item Highlight features selected. The app itself opens but has no functionality it's just kind of there in the background.

**Comment by C1rdec** [comment]
Start the app as admin

**Comment by Kohtas** [comment]
I've done this and it still doesn't work.

**Comment by C1rdec** [comment]
Without logs I cannot help you.  (FOLLOW TEMPLATE)

**Comment by Kohtas** [comment]
Can't do that when the app isn't generating an actual log file (yes I've checked in the proper location where it should be) thanks anyways.

**Comment by C1rdec** [comment]
Ho do you laugh the application?
