### ISSUE TITLE
No instructions on how to build this software locally

### ISSUE THREAD

**Issue by johnsmithdoe970** [C1rdec/Poe-Lurker#297]
**Is your feature request related to a problem? Please describe.**
This is not linked to an issue

**Describe the solution you'd like**
I was wondering if we could have developer documentation. Might help on feature extending.

**Describe alternatives you've considered**
Trying on my own, lose time, being frustrated, move to another software.

**Additional context**
No extra data necessary.

**Comment by C1rdec** [comment]
What's the issue you are experiencing? You just need to have .net 4.8
