### ISSUE TITLE
Some trade messages aren't parsed properly (even without any "exotic" characters)

### ISSUE THREAD

**Issue by tbarusseau** [C1rdec/Poe-Lurker#298]
**Describe the bug**
Some trade messages fall through the cracks of  `Poe-Lurker`. Most of the time it's because of asian/russian symbols (which whatever software used by `Poe-Lurker` might not handle/decode properly), but sometimes it also happens to me with "regular" characters.

**To Reproduce**
This is infrequent (around 1 time in 20 trades, sometimes it happens often, and sometimes not).

**Please complete the following information:**
Example of a recent trade that didn't get caught by `Poe-Lurker`:

2021/11/09 15:33:59 363537500 b87 [INFO Client 21208] @From scionka_scourge: Hi, I would like to buy your The Undaunted listed for 4 chaos in Scourge (stash tab "Shop"; position: left 22, top 22)

**Comment by bhnn** [comment]
That's due to a legal issue with the Korean client from which messages are not saved into the logs, causing the malfunction of chat addons. This is mentioned in #4.

**Comment by tbarusseau** [comment]
Ah, I see. I also see that it's been mentioned quite a few times! Sorry.

As it's clearly a non-intuitive behavior and appears like a bug to users, could it be possible to integrate it somewhere in the program? I don't really see how, though.
