### ISSUE TITLE
Make it easier to learn

### ISSUE THREAD

**Issue by simonflick** [C1rdec/Poe-Lurker#299]
**Is your feature request related to a problem? Please describe.**
PoE Lurker doesn't clearly show, what actions you do if you click on something. This means you have to look up everything you need and remember it instead of learning by doing.

**Describe the solution you'd like**
Try to make all features explorable. For example you could add instant tooltips every time you hover something:
Hover the main action -> "Invite"
Hover the main action while holding CTRL+SHIFT -> "Still interested?"
Additionally you could implement a context menu on hover or right click on the main action for "Still interested" or other sub actions you don't need every time. In this context menu you could also display the hotkey for every action.

**Comment by C1rdec** [comment]
There's a quick user guide that you can follow. I agree that there's some stuff that you need to learn but when you know it it's pretty much straight forward
