### ISSUE TITLE
Shift-click on a stack will close inventory

### ISSUE THREAD

**Issue by sinatrocious** [C1rdec/Poe-Lurker#300]
**Describe the bug**
Shitt-clicking (to split stacks) in both inventory and stash will close inventory. Nothing critical, but very annoying.

**To Reproduce**
1. Open inventory or stash.
2. Shift-click on anything stackable (e.g. 5 Portal Scrolls)
3. The inventory is closed, but dialogue to split stack is still shown. To put result of split I need to open inventory again using hotkey.

**Expected behavior**
The inventory shouldn't be closed. 

**Please complete the following information:**
 - Version v1.16.1
 - Provide Log (C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs) - there is no logs folder inside PoeLurker\app-1.16.1 folder.

**Additional context**
The lurker updated himself just today (didn't see auto-update before, using it for few weeks). I noticed the issue immediately after update. Closing lurker - no issue, starting lurker - the problem appears again.

I've tried to look into settings, but found nothing. I guess it could be something to do with Lurker-Pro feature (I am not using pro):
 - [Lurker Pro] Shift-Click on item: "Item Lurker" Item Alert

**Comment by sinatrocious** [comment]
I forgot to mention, that I have custom bindings: "C" is used for inventory.

Tried to bind "C" to something else (e.g. Cosmetics) and voila - that something else is now opening on shift-click. It looks like lurker uses own bindings, but I have no idea where I can configure them. I didn't setup any "Hotkey" in lurker or anything.

**Comment by C1rdec** [comment]
Fixed in 1.16.2
