### ISSUE TITLE
Overlay not being showed after POE update

### ISSUE THREAD

**Issue by PatrickRorth** [C1rdec/Poe-Lurker#301]
**Describe the bug**
The HIDEOUT icon is being showen - which is fine.
But when doing a trade wisper, no overlay is showing.

**To Reproduce**
1. Paste the trade wisper - nothing is showing
2. recieve a trade - nothing is showing

**Expected behavior**
a button in the bottom of the coner should be shown doing trade

**Screenshots**
[https://imgur.com/a/UiuejxS](https://imgur.com/a/UiuejxS)

**Please complete the following information:**
 - Version 1.16.3

_[2021/12/01 01:56:20.892] Error [1] Samlingen er blevet ændret. Optællingen bliver muligvis ikke udført.
System.InvalidOperationException: Samlingen er blevet ændret. Optællingen bliver muligvis ikke udført.
   ved System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   ved System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   ved System.Collections.Generic.List`1.Enumerator.MoveNext()
   ved System.Linq.Enumerable.<OfTypeIterator>d__95`1.MoveNext()
   ved Caliburn.Micro.EnumerableExtensions.Apply[T](IEnumerable`1 enumerable, Action`1 action)
   ved Caliburn.Micro.Conductor`1.Collection.AllActive.OnDeactivate(Boolean close)
   ved Caliburn.Micro.Screen.Caliburn.Micro.IDeactivate.Deactivate(Boolean close)
   ved Caliburn.Micro.WindowManager.WindowConductor.Closed(Object sender, EventArgs e)
   ved System.Windows.Window.OnClosed(EventArgs e)
   ved System.Windows.Window.WmDestroy()
   ved System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   ved System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   ved MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   ved MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   ved System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   ved System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   ved System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   ved MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam) (Lurker.UI.AppBootstrapper)_

**Comment by C1rdec** [comment]
I'm not sure what's your issue but did you manage to make it work?

**Comment by PatrickRorth** [comment]
Yes i was a problem at my end.
Thanks
