### ISSUE TITLE
Thank you message is sent even if the trade (outgoing) for the message has been dismissed.

### ISSUE THREAD

**Issue by Xebtria** [C1rdec/Poe-Lurker#304]
**Describe the bug**
When I change party to trade with someone else and "close" the "lock" (or whatever you call it) of the first person, and then finish the trade with the second person, the "thank you" message is still sent to the first person

**To Reproduce**
Situation: I want to buy currency (e.g. exalted for chaos). Usually I have to whisper a bazillion people to get a reply.

1. Eventually someone sends an invite.
2. I accept invite, go to their hideout via that ui button (the "countdown bar" thing) of that guy, which makes that bar permanent.
3. they take an eternity to trade.
4. In the meantime I get an invite from a second person, who is either russian/korean whatever who doesnt have that countdown bar, or their countdown bar "expired" already.
5. I decide _"fuck that first guy when he takes an hour for a trade"_, accept the second invite, go (manually) to their hideout.
6. I disable the bar of the first guy (so it goes away), using the top right button of it.
7. I finish the trade with the second guy

**► the automatic thank you message is still sent to the first guy.**

**Expected behavior**
When I remove the that bar of the first guy (step 6), the "lock" on that person should also be removed, resulting in **no** thank you message being sent to either guy when I complete the trade

**Screenshots**
n/a

**Please complete the following information:**
 - Version 1.16.6
 - that location mentioned for the logs does not have any subfolder "logs": https://i.vgy.me/jWxcz7.png

**Additional context**
The problem can easily be reproduced by whispering yourself with a trade, then click the bar (as if you would be buying), then click the bar away, then sell anything to an npc. => message is also sent, but I would expect it to not be sent.

**Comment by C1rdec** [comment]
The problem here is that when you trade with an npc the same message is logged into `client.txt` alot of people requested that the trade needs to be register even if then trade manually. This is a side effect of that.

If you engaged a trade with some one and you trade with an npc Poe Lurker will think that you trade successfully with the player.
