### ISSUE TITLE
Ignore item for a period

### ISSUE THREAD

**Issue by dovry** [C1rdec/Poe-Lurker#307]
**Is your feature request related to a problem? Please describe.**
Getting 20 offers because you dumped an expensive item in a cheap buyout tab

**Describe the solution you'd like**
Ignore the Item A for Price A for X minutes

**Describe alternatives you've considered**
N/A

**Additional context**
Trade companion has this feature

**Comment by C1rdec** [comment]
Good idea how do you see this feature being used?  (UI related)

**Comment by C1rdec** [comment]
I think I'll add an option that you will ignore the item when you Ctrl + Click an Offer (Already Sold action).

This would be optional and the user will need to enable the feature.

**Comment by Getrektgasm** [comment]
Have some problems with poe lurker, commands dont paste and typing like human, i mean word by word, What it can be? App run as administrator etc.

**Comment by C1rdec** [comment]
Added in 1.17.6
