### ISSUE TITLE
Parse exchange Trades correcly for the Dashboard

### ISSUE THREAD

**Issue by Sykh** [C1rdec/Poe-Lurker#309]
My Dashboard looks like this:
![image](https://user-images.githubusercontent.com/5365955/154277778-92fcb342-97e9-485d-9925-811b6670cc60.png)

The big blue are multi item trades
> @From endless_queen: Hi, I'd like to buy your 20 Orb of Unmaking for my 36 Chaos Orb in Archnemesis.
Ideally it would recognice that Orb of Unmakings were sold and register 36c for them but instead it creates an unkown for the item "20 Orb of Unmaking", if i sell 10 its a different item etc

Plus i think its confused by buy orders
> @From <ðæ1qR[> carrybrother: Hi, I'd like to buy your 36 Chaos Orb for my 90 Explorer's Scouting Report in Archnemesis

As always, thanks for the awesome program!

**Comment by Sykh** [comment]
> If you click on the unknown you'll see all the items.
Not anymore, guess i had too many it just shows a blank graph but i've exportet you all exchange messages i've received this league
https://pastebin.com/kg1XWXgq
It looks like they work with "Hi, I'd like to buy your" instead of "Hi, I would like to buy your" for single trades but since you are reacting to both you already know that, it was new to me :)

Correction it does still load when i go fullscreen
![image](https://user-images.githubusercontent.com/5365955/154540619-9a1dadf4-3f56-4792-945e-660649437322.png)

Here is a sample
![image](https://user-images.githubusercontent.com/5365955/154540754-c2578a2a-d8e1-416b-be80-82b3e167f492.png)
The unknown are the chaos...it would be interesting if i get can get money spend somewhere aswell, i love numbers :D

**Comment by C1rdec** [comment]
I think you are the one that needs to work on yourself. I would step back and analyze the situation.

**Comment by C1rdec** [comment]
I think you are the one that needs to work on yourself. I would step back and analyze the situation. Side note I will fix the Unknown for next league I never said I would not.

**Comment by Sykh** [comment]
You asked for an example and the reaction was "That is your problem to figure out stop spamming my chat" is an interesting version of "i will fix it" after deleting every message...

Don't worry i wrote my own parser and it's working perfectly fine you can keep it as it is.

**Comment by C1rdec** [comment]
Cant you see your attitude here? Thanks for the idea I will close this issue since there's nothing constructive coming from you
