### ISSUE TITLE
3.17.1 no longer works after patch

### ISSUE THREAD

**Issue by thisisdumbstuff** [C1rdec/Poe-Lurker#310]
after latest patch does not function

**To Reproduce**
patch game, login

**Expected behavior**
nothing works

**Screenshots**
try it

**Please complete the following information:**
3.17.1

**Additional context**
I appreciate you and have been a lurker pro for a long time now, please fix this as I have become used to using it.

**Comment by C1rdec** [comment]
Can you provide some logs?

**Comment by Marval89** [comment]
I have same problem, where I can find any logs?

**Comment by C1rdec** [comment]
It's in the Bug Template when you created the issue. Take the time to read it next time please.

*Please complete the following information:**
 - Version [e.g. v1.3.0]
 - Provide Log (C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs

**Comment by Marval89** [comment]
There is no logs folder in this path, my poe in is english.
Noticed that incoming trade is working, but nothing on outcoming one. 
Also on tray icon there is no Preferences 

![image](https://user-images.githubusercontent.com/21313425/154847370-59efaf9d-a5a7-465a-a070-3867554b247b.png)

and btw, when I use function to paste name of item in search field and it is a map, i get 'Map-name' with T10 etc, and this doesn't work in poe search, have to manually delete tier number.

**Comment by C1rdec** [comment]
Lol look at the version 1.1.2 is VERY old

**Comment by Marval89** [comment]
Damn I had two version of Luker on my PC, sorry for that.
