### ISSUE TITLE
Closed after trying open settings

### ISSUE THREAD

**Issue by tvinki899** [C1rdec/Poe-Lurker#311]
**Describe the bug**
problem almost same like https://github.com/C1rdec/Poe-Lurker/issues/266
hud in game work almost fine, grid broken( and i think its can b fixed on settings but ^
**To Reproduce**

2. Click on settings
3. some hud windows pop up and program closed after couple of sec

**Please complete the following information:**
 - Version 1.17.5
 - Provide Log <details>[2022/02/20 01:29:15.062] Error [1] Не удается вызвать метод DragMove или Activate до вывода окна на экран.
System.InvalidOperationException: Не удается вызвать метод DragMove или Activate до вывода окна на экран.
   в System.Windows.Window.VerifyHwndCreateShowState()
   в System.Windows.Window.Activate()
   в Lurker.UI.ViewModels.SettingsViewModel.OnViewLoaded(Object view)
   в Caliburn.Micro.XamlPlatformProvider.<>c__DisplayClass11_0.<ExecuteOnFirstLoad>b__0(Object s, RoutedEventArgs e)
   в Caliburn.Micro.View.<>c__DisplayClass8_0.<ExecuteOnLoad>b__0(Object s, RoutedEventArgs e)
   в System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   в System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   в System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   в System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   в System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   в System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   в MS.Internal.LoadedOrUnloadedOperation.DoWork()
   в System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   в System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   в System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   в System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   в System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   в System.Windows.Interop.HwndTarget.OnResize()
   в System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   в System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam) (Lurker.UI.AppBootstrapper)
</details>

**Additional context**
Builds.json almost 44mb i dont think its good )

**Comment by C1rdec** [comment]
try to rename Build.json to Build.backup.json

**Comment by C1rdec** [comment]
Let me know if you need further assistance
