### ISSUE TITLE
App closing unexpectedly after few minutes

### ISSUE THREAD

**Issue by antoniocmf** [C1rdec/Poe-Lurker#312]
**Describe the bug**
App is closing unexpectedly after a few seconds/minutes open. Tried closing other third-party applications but couldn't find anything else related.

**Please complete the following information:**
 - Version 1.17.5
 - Log file attached. 
 - [2022-02-20.log](https://github.com/C1rdec/Poe-Lurker/files/8103395/2022-02-20.log)

**Additional context**
My OS is in Brazilian Portuguese (PTBR).

If you need any help understanding what the log is saying please let me know

**Comment by C1rdec** [comment]
Yes

**Comment by C1rdec** [comment]
This seems to be an issue with your OS. 
what is your Operating system?

**Comment by antoniocmf** [comment]
The errors translated:

[2022/02/20 00:34:45.533] Error Only a portion of a ReadProcessMemory or WriteProcessMemory request has completed System.ComponentModel.Win32Exception (0x80004005): Only a portion of a ReadProcessMemory or WriteProcessMemory request has completed 

[2022/02/20 00:40:40.405] Error The window handle is invalid System.ComponentModel.Win32Exception (0x80004005): The window handle is invalid

**Comment by antoniocmf** [comment]
Windows 11 Pro
Version 21H2
OS Compilation 22000.493

**Comment by C1rdec** [comment]
This issue seems to be related on your environment sadly...

**Comment by C1rdec** [comment]
https://windowsreport.com/readprocess-writeprocess-error/#:~:text=Recheck%20File%20Permissions,taking%20ownership%20of%20the%20file.
