### ISSUE TITLE
'Detect sold' misrecognises items with the same name as being sold

### ISSUE THREAD

**Issue by Barragek0** [C1rdec/Poe-Lurker#313]
A fix for this could be to include which stash tab / position the item is in when checking if it is sold. Selling charged compasses which all have the same name is very annoying with detect sold on.

**Comment by C1rdec** [comment]
It's already the case

**Comment by Barragek0** [comment]
I've checked and it doesn't seem so? It just checks one position against another, then it loops through all the possible items to check all of them. I'm not experienced with C# or i'd submit a pull, but you could just move the 'location' check to within the for loop?

**Comment by Barragek0** [comment]
If that's not the case, the incoming message is 'Hi, i'd like to buy your Charged Compass listed for x Chaos'.

**Comment by C1rdec** [comment]
Here's the code:

https://github.com/C1rdec/Poe-Lurker/blob/8bd312e9f5377e1e0a8a43e4395b63097077b196/src/Lurker.UI/ViewModels/TradebarViewModel.cs#L320

**Comment by C1rdec** [comment]
Here's the code:

https://github.com/C1rdec/Poe-Lurker/blob/8bd312e9f5377e1e0a8a43e4395b63097077b196/src/Lurker.UI/ViewModels/TradebarViewModel.cs#L320-L344
