### ISSUE TITLE
the trade button moving

### ISSUE THREAD

**Issue by DurkMC** [C1rdec/Poe-Lurker#316]
**Describe the bug**
the trade button sometimes movies
**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Version [e.g. v1.3.0]
 - Provide Log (C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs)

**Additional context**
the trade button sometimes movies

**Comment by C1rdec** [comment]
I'm not sure what you are referencing to...
