### ISSUE TITLE
Whisper problem.

### ISSUE THREAD

**Issue by surinasauva** [C1rdec/Poe-Lurker#318]
Lurker have been working great for a long time. This league whispers doesnt always get send, when pressing whisper button on poe trade site. Basically i have to copy paste some times manually. Also when doing other stuff, lurker randomly send latest whisper message again, which is quite annoying.

Ive met multiple ppl sending me whisper about item they already bought and when asked, are they using lurker, they all said yes and had noticed same problem. So this is some sort of copy and paste issue. English is not my main language. :D

Edit: After more testing, it seems poe lurker copies text from poe trade site, but doesnt paste it to ingame chat. When trying to go hideout with awakened poe trade f5 /hideout command, it instead sends poe lurkers copied message.

Edit: I have now removed hideout command from awakened poe trade and configuret it to poe lurker. Gonna see, if it helps.

**Comment by C1rdec** [comment]
try 1.18.0 it should fix this issue
