### ISSUE TITLE
Messages and commands being sent slowly one letter at a time

### ISSUE THREAD

**Issue by stephen-netu** [C1rdec/Poe-Lurker#319]
**Describe the bug**
Messages and commands sent by Lurker are typed out, one letter at a time, slowly, instead of immediately pasting or typing quickly.

**To Reproduce**
When I go to pathofexile/trade and send a trade message, PoEA types the message, one letter at a time, and it takes a few seconds for it to send.  I cannot do any other action during this.

Additionally, when I invite a user for a trade, it is the same phenomena, meaning I cannot invite anyone in a fight or something, as my trade window will be occupied and I cannot press any other keys otherwise the message will be messed up (including inviting someone for a trade).

**Expected behavior**
The trade messages and commands to be pasted immediately or typed more quickly than the many seconds it currently takes.

**Screenshots**
Settings/latency if relevant:
![image](https://user-images.githubusercontent.com/12437943/171016561-d551716a-01d1-4be3-9e83-051b63498dd1.png)
![image](https://user-images.githubusercontent.com/12437943/171016578-e8ee1d21-ccf7-40d4-b5d3-d5f45f23a1be.png)

**Please complete the following information:**
Version 1.18.0.

**Additional context**
I have tried all sorts of graphic settings changes, including but not limited to every renderer and having Vsync on or off.

I am not sure what else to report--and I am certainly not sure how to replicate--seems to be just a me-issue (I asked in the PoE Discord and no one else had the problem, I guess).

**Comment by C1rdec** [comment]
This is always related to another software installed

**Comment by stephen-netu** [comment]
> This is always related to another software installed. Let me know if you need help to investigate

Oh, no!

That's so peculiar, I cannot even think of what I might have installed since the last league (as it worked fine last league).

I use things such as DisplayFusion and PowerToys, do you think those or anything such as them might be the cause?  I will disable them and hop back into game and test.  Any way of ruling them out more easily?

**Comment by C1rdec** [comment]
I would close everything and test it out. One way to trigger the Keyboard easily is in the settings.
Those buttons will type in the focused textbox.
![image](https://user-images.githubusercontent.com/5436436/171075400-24ae87f5-edae-480a-9a1c-5b6bac66e86e.png)

Join the Discord and talk to me if you need further assistance.
