### ISSUE TITLE
App doesn't catch PMs

### ISSUE THREAD

**Issue by Ninjaskill** [C1rdec/Poe-Lurker#32]
Hi there, I tried this app multiple times tried rebooting PoE several times but not luck. It doesn't pick up any PMs including English ones worth mentioning to avoid confusions.
A few things to mention.

- I use English PoE
- I'm on a high DPI monitor 2560x1440, tried running at 100% instead of 150% scaling doesn't make a difference.
- Tried running PoE at 1080p still nothing
- I have installed .NET framework

Any clues what the issue might be?

**Comment by C1rdec** [comment]
When you turn down the WIndows scaling option to 100% did you close POE and the Lurker?

**Comment by C1rdec** [comment]
Why are you saying even English one? Are you Korean?

**Comment by Ninjaskill** [comment]
I did close both PoE and Lurker yes. I said English to avoid confusion I'm using another langauge client.

**Comment by C1rdec** [comment]
Can you see the whisper in `Client.txt` located in the folder of Path of Exile

**Comment by Ninjaskill** [comment]
I opened up client.txt and I can see my whispers people wanting to trade so client is slow or anything. I recently also archived my client.txt so the size of the txt file is much smaller.

**Comment by C1rdec** [comment]
Is there anything in the log of Poe Lurker?

**Comment by Ninjaskill** [comment]
No

**Comment by C1rdec** [comment]
if you set poe in `Windowed Mode` and reduce the size of the window to like 600X800 and you drag poe to the upper left part of your screen. Can you see the whispers?

**Comment by Ninjaskill** [comment]
Let me try

**Comment by C1rdec** [comment]
(You will need to have whisper)

**Comment by Ninjaskill** [comment]
it may have to do something with the high DPI. If freshly start PoE in 800x600 and put it the top left of the screen then go back to full screen after triggering the app it keeps working. One thing to note it does appear at a rather weird position and also rather small.
![image](https://user-images.githubusercontent.com/10984882/72081219-59544b80-32fe-11ea-8b75-9e1224aded05.png)

**Comment by C1rdec** [comment]
#9 Duplicate

**Comment by C1rdec** [comment]
I will try to fix this tonight and I'll keep you posted here

**Comment by Ninjaskill** [comment]
Ok thanks for your work! I have a 4k monitor for browsing and 1440p for gaming. If you need someone to test on those resolutions I'm in your Discord server.

**Comment by C1rdec** [comment]
Ill ping you thanks !
