### ISSUE TITLE
UI seems to shift up slightly when relaunching game

### ISSUE THREAD

**Issue by procrastin8** [C1rdec/Poe-Lurker#320]
**Describe the bug**
The poe lurker UI seems to shift up ~100 pixels when relaunching the game while lurker is active. it seems to align with the top of the taskbar

**To Reproduce**
1. Launch lurker while poe is active
2. Close PoE
3. Relaunch PoE

**Expected behavior**
UI shouldnt move when launching PoE while lurker is active

**Screenshots**
![image](https://user-images.githubusercontent.com/98596336/171204271-24a168e9-b18e-470d-8858-5d06252df702.png)

**Please complete the following information:**
 - Version [e.g. v1.18.0]
 - no log file found. the poe lurker folder exists but no log file

**Additional context**

**Comment by C1rdec** [comment]
A lot of the time this is caused by something installed on the machine. 

What's your resolution?
Are you playing in Windowed Fullscreen?
Are you using any third party software for recording or managing fullscreen windows?

**Comment by C1rdec** [comment]
You are the first one that raise this issue this seems to be related to your machine some how.

Can you join the discord so I can help you investigate ?
