### ISSUE TITLE
Resends outgoing whisper while pricechecking (CTRL+D) with Awakened PoE Trade #314

### ISSUE THREAD

**Issue by surinasauva** [C1rdec/Poe-Lurker#321]
This old issue, which was supposed to be fixed is still present in 1.18.0. When price checking item with awakened poe trade, lurker sends old copied whisper again. This happens randomly and not every time i price check.

**Comment by C1rdec** [comment]
I'm not able to reproduce this on my side are you still experiencing this issue?
