### ISSUE TITLE
UI Initialization sometimes unreliable

### ISSUE THREAD

**Issue by MaxKruse** [C1rdec/Poe-Lurker#322]
**Describe the bug**
The UI gets shifted up if windows does not remove the taskbar from the window's size calculation fast enough. Similar to #320 in behaviour, just a different offset.

This may have to do with Windows10, The selected renderer or general system speed.

**To Reproduce**
1. Launch Poe Lurker
2. Launch PoE
3. UI is shifted upwards

**Expected behavior**
UI should be positioned according to the game's (borderless) window setting.

**Screenshots**
https://i.imgur.com/saq2tGN.png

**Please complete the following information:**
 - PoeLurker 1.18.0
 - Awakened PoE Trade 3.18.10003
 - [2022-06-08.log](https://github.com/C1rdec/Poe-Lurker/files/8878595/2022-06-08.log)

**Additional context**
This does happen about once every 2 game starts.

**Comment by C1rdec** [comment]
Can you replicate this if you launch Poe Lurker after Poe?

**Comment by MaxKruse** [comment]
This does not happen if PoE Lurker is started after the game.

**Comment by C1rdec** [comment]
Should be fixed in 1.18,.1 Poe Lurker will initialize only when you join the first instance

**Comment by C1rdec** [comment]
Let me know if you can reproduce the issue with 1.18.1

**Comment by MaxKruse** [comment]
Perfect, works like a charm and no issues now! Thanks for fast fix UwU
