### ISSUE TITLE
Add more specific item highlighting

### ISSUE THREAD

**Issue by RhapsodySL** [C1rdec/Poe-Lurker#323]
**Is your feature request related to a problem? Please describe.**
Lurker currently has a feature to automatically input the name of an item that someone is attempting to buy from you. This is useful for items with unique names (which fit most items in the game), but for items that have static names that don't change (unique items, and especially charged compasses), Lurker falls short in that it will highlight all items with the matching name. For example, if someone tries to buy a charged compass from me with the mod "Areas contain a Smuggler's Cache", and I press on my health globe to highlight the item in my stash, _all_ charged compasses will be highlighted regardless of contents.

Adding more specific highlighting will be beneficial in multiple facets, but most notably to sextant sellers and people who sell corrupted uniques (where different uniques with the same name can both meet the name criteria).

**Describe the solution you'd like**
This doesn't appear to be possible to do within the PoE search bar, so it would require an implementation that directly highlights the item's location via an overlay. See the [Chaos Recipe Helper application ](https://github.com/kosace/EnhancePoEApp)for an example of how this could be done.

**Comment by C1rdec** [comment]
https://github.com/C1rdec/Poe-Lurker/releases/tag/v1.17.0

There's a marker
