### ISSUE TITLE
Awakened Sextants don't display properly when used as a currency

### ISSUE THREAD

**Issue by RhapsodySL** [C1rdec/Poe-Lurker#324]
Posting separately from [the other issue](https://github.com/C1rdec/Poe-Lurker/issues/296#issuecomment-1154744514) report for visibility, as I'm unable to open closed issues;

Awakened Sextants don't display properly;
![image](https://user-images.githubusercontent.com/8369578/173502588-e0e96789-a380-42e8-93f7-7661b83177e6.png)

In regards to https://github.com/C1rdec/Poe-Lurker/issues/296#issuecomment-963252835, Awakened Sextants are used commonly as the type of currency used to trade for Charged Compasses, as it eases the burden on sextant rollers. Look up almost any sextant and you'll see that a vast majority of them use Awakened Sextants.

**Comment by C1rdec** [comment]
Yeah I will add Sextants support for currency type.

I will take a look after work

**Comment by antoniocmf** [comment]
Hi, considering the usage of Awakened Sextant as a trade item has increased considerably this league maybe this fix could come in handy ?

**Comment by C1rdec** [comment]
Added in 1.21.8
