### ISSUE TITLE
Cant change Feature Hotkeys 

### ISSUE THREAD

**Issue by Caessss** [C1rdec/Poe-Lurker#326]
Im on the Version 1.18.1.
I cant change the Hotkeys from the Feature Tab

**Comment by C1rdec** [comment]
Working fine on my side

**Comment by Caessss** [comment]
Are you supposed to just click on the already assigned Buttons ? Because I can click as much as I want but the is no prompt showing up.

**Comment by Caessss** [comment]
The Application is working very well only the Feature Hotkey change doesnt. I want to change the Feature Hotkey for "Remaining Monsters"

**Comment by C1rdec** [comment]
To assign a new value you need to clear the old one

![image](https://user-images.githubusercontent.com/5436436/174458485-bac7d154-469c-4837-9b14-b36c4750fd73.png)

**Comment by Caessss** [comment]
jeez Im stupid thank you very much. Hope you have a nice evening

**Comment by C1rdec** [comment]
You to :)
