### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by anutting** [C1rdec/Poe-Lurker#337]
**Is your feature request related to a problem? Please describe.**
Poe-Lurker is built specifically for Windows environments. Path of Exile has a native Linux client distributed through steam and it would be really nice to see this library, my favorite trade manager, also have native Linux support.

**Describe the solution you'd like**
A release of Poe-Lurker available as a .appimage, flatpack, or rpm that can be installed on a variety of Linux distributions similar to how Awakened Poe trade does it: https://snosme.github.io/awakened-poe-trade/download

**Describe alternatives you've considered**
The alternative would be running Poe-Lurker through a compatibility layer like WINE or Proton, which may or (more likely) may not work. I will be doing my own testing with this and can update with request when complete.

EDIT: My assumptions were correct. It is not possible to run Poe-Lurker using a compatibility layer.

**Comment by C1rdec** [comment]
Poe Lurker is built with WPF (Windows Presentation Framework) To have a linux support a rewrite would need to occurs. 
Not on the road map for now sorry...
