### ISSUE TITLE
use new position search for item highlight

### ISSUE THREAD

**Issue by mrooney** [C1rdec/Poe-Lurker#339]
**Is your feature request related to a problem? Please describe.**
Sometimes multiple items can be highlighted when you click the button to do so (charged compasses)

**Describe the solution you'd like**
Use new `pos:x,y` search: https://www.reddit.com/r/pathofexile/comments/wr54ws/in_lake_of_kalandra_youre_able_to_search_stash/

**Describe alternatives you've considered**
The current system works well, but getting the x,y pos and searching by that seems the best possible scenario to highlight the precise item.

**Additional context**
I am also happy to give this a stab if you point me to the right files. I did some poking around but couldn't obviously find the code that parses the trade message and pastes the search in. I'm a programmer but primarily Python and web.

**Comment by C1rdec** [comment]
Already implemented I'm waiting for 3.19 to release :)

**Comment by C1rdec** [comment]
Added in 1.19.1
