### ISSUE TITLE
Tool unable to read messages from Russian or German clients

### ISSUE THREAD

**Issue by flapanther33781** [C1rdec/Poe-Lurker#341]
The tool doesn't recognize incoming messages from anyone whose language setting is Russian.  Looking at the log files it may be related to a non-printable character that appears in their messages.  Here are some examples (look for "_ за"):

2022/08/19 22:00:36 671747390 cff943d6 [INFO Client 15304] @From choppaonme_: Здравствуйте, хочу купить у вас level 1 0% _ за 1 alch в лиге Kalandr Ancestral Protector (stash tab "~price 1 alch"; position: left 2, top 2)

2022/08/20 19:28:29 749020812 cff943d6 [INFO Client 10580] @From eliauri: Здравствуйте, хочу купить у вас level 1 0% _ за 1 alch в лиге Kalandr Pride (stash tab "~price 1 alch"; position: left 3, top 12)

2022/08/20 19:36:26 749497875 cff943d6 [INFO Client 13428] @From Антистрессс: Здравствуйте, хочу купить у вас level 1 0% _ за 1 alch в лиге Kalandr Lesser Multiple Projectiles Support (stash tab "~price 1 alch"; position: left 1, top 10)

**Comment by flapanther33781** [comment]
It's also failing German requests:

2022/08/21 00:57:08 768740062 cff943d6 [INFO Client 13428] @From riandra: Determinationi, ich möchte '{{ITEM}}' zum angebotenen Preis von {1 alch} in der {Kalandra}-Liga kaufen. (stash tab "~price 1 alch"; position: left 3, top 11)

**Comment by flapanther33781** [comment]
I've also seen this issue with people whose messages are in English but I suppose those might be people in Korea who can speak English.

**Comment by C1rdec** [comment]
Only English incoming messages will be parsed for now... It's alot of work to support all languages in the parser you should set the whisper language to English on the trade site.

![image](https://user-images.githubusercontent.com/5436436/185848394-388b8d50-057d-46e1-8a04-8b7a982db7ea.png)
