### ISSUE TITLE
UI not aligned

### ISSUE THREAD

**Issue by fatings** [C1rdec/Poe-Lurker#342]
With the change GGG made to the limitations on ultrawide resolutions, the UI isn't aligned anymore:
![image](https://user-images.githubusercontent.com/39002567/185783240-23357ef7-2bda-4b99-a497-51a39a4842ce.png)

My resolution is 1969x831.
My suggestion would be to allow for a manual offset X axis value on the settings.

Thanks for all the work.

**Comment by C1rdec** [comment]
I think we will have to deal with it for now. I'm planning to add the offset to move overlays around but we are not close from having something ready.

**Comment by C1rdec** [comment]
I created the issue for this feature:

https://github.com/C1rdec/Poe-Lurker/issues/344
