### ISSUE TITLE
Allow us to cycle through requested items

### ISSUE THREAD

**Issue by flapanther33781** [C1rdec/Poe-Lurker#343]
**Is your feature request related to a problem? Please describe.**
I often get multiple trade requests at the same time.  When I invite people to trade they don't always show up in the same order that their orders came in.

**Describe the solution you'd like**
When we have multiple people who've accepted our invitation, and who are in our hideout, the tool is able to recognize this.  We know this because the application's icon changes to show they're in the hideout.  It would be nice if the tool would (a) allow us to click under the HP globe multiple times, to cycle through which order is highlighted in our inventory, (b) place a white border around the trading partner whose item is currently being highlighted, and (c) when the trade is completed, remove the correct person from the party.

**Describe alternatives you've considered**
My only possible options at this time are to either only accept 1 trade at a time, or hover my mouse over the trade icons to see what the person ordered if they arrived before the first trade person has arrived.  The first option means I miss out on trades, if I pursue the second option the tool is not currently smart enough to know I've traded with someone other than the first trade accepted, and so it will kick the first person out of the party as if I've traded with them.  A third option might be to consider using a different trade tool, but I haven't done looked at any others yet.

**Additional context**
N/A

**Comment by C1rdec** [comment]
Out of curiosity did you know that you are able to change the 'Active Offer' with `Alt + Click` ?

**Comment by flapanther33781** [comment]
I play in Windowed mode.  When I attempt this my game switches to full
screen mode.  I then attempted to alt-click when in fullscreen mode to see
if that worked, but it did not.

**Comment by C1rdec** [comment]
Alt + Click an offer should not trigger any text input

**Comment by flapanther33781** [comment]
Wait, are you saying I need to alt-click the offer, or alt-click the bottom
half of the HP globe?  I was doing the latter.

**Comment by C1rdec** [comment]
![2022-08-23_11-57-54](https://user-images.githubusercontent.com/5436436/186205576-5b7aae4e-4f6a-488b-9e32-113e9a1caf60.gif)

**Comment by flapanther33781** [comment]
Ah.  I'll give that a try next time it comes up, thanks.  I wonder if this
was in the tutorials I watched, or was a feature you added after I watched
them. I do also wonder, though, if what I suggested might be more
intuitive?  Clicking the HP globe (not alt-clicking, just regular) to cycle
through the people in the queue.
