### ISSUE TITLE
Application crashes

### ISSUE THREAD

**Issue by exonerati** [C1rdec/Poe-Lurker#356]
**Describe the bug**
When using the application it just dies. This happens quite often.

**To Reproduce**
Seems to happen when app is idle for periods of time.

**Expected behavior**
Expected the app to keep running :)

**Screenshots**

**Please complete the following information:**
 - Version 1.19.2
 - Provide Log (C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs)
[2022-09-15.log](https://github.com/C1rdec/Poe-Lurker/files/9578519/2022-09-15.log)
[2022-09-11.log](https://github.com/C1rdec/Poe-Lurker/files/9578529/2022-09-11.log)

**Additional context**
Don't have a lot, sorry. Really appreciate the app though :)

**Comment by C1rdec** [comment]
You seems to have a build that make the application crash.
Can you link your `Build.json` file located : "C:\Users\[user]\AppData\Roaming\PoeLurker\Builds.json"

**Comment by exonerati** [comment]
Couldn't upload .json format. But could turn it into a txt. Hope that helps! It does crash no matter which character I'm logged into though.
[Builds.txt](https://github.com/C1rdec/Poe-Lurker/files/9619060/Builds.txt)

**Comment by exonerati** [comment]
This is why you're in my patreon :)
