### ISSUE TITLE
[Request] Currency Trading Stack Assistance

### ISSUE THREAD

**Issue by livejamie** [C1rdec/Poe-Lurker#358]
When selling currency, especially Essences that come in stacks of 9 or Scours that come in stacks of 40 it's annoying to try to do the math of how much to get that person.

With Essences I usually get a calculator and divide how much they have by 9 so I know how many stacks to give them.

This feels like a great problem that Lurker could solve by having an indication on the icon or tooltip that tells me how many stacks to give the person.

Thanks!

**Comment by Davst** [comment]
I second this.. would be nice to see the amount of stacks + extra to expect.. or to send.

Another thing that'd be nice would be to have the 0.x div amount shown in chaos

**Comment by livejamie** [comment]
> Another thing that'd be nice would be to have the 0.x div amount shown in chaos

Doing div/chaos conversions would be clutch, good idea.

**Comment by C1rdec** [comment]
For now the Poe Ninja overlay is able to give fraction value of a Divine
