### ISSUE TITLE
[New Feature Request or I'm missing something] Centered UI Support

### ISSUE THREAD

**Issue by Muetze5** [C1rdec/Poe-Lurker#366]
**Is your feature request related to a problem? Please describe.**
In Centered UI Enabled mode i got the Trade Notifications above the Healthglobe and Flasks

**Describe the solution you'd like**
Maybe a Option to move the Notification positions or support for the centered UI Mode

I hope i'm not missing some features and it is already possible to move the UI Elements :)

**Comment by C1rdec** [comment]
You're not missing any feature. It's currently not possible to move the UI since it's 'linked' to the PathOfExile window.

I could create an offset for the `Tradebar`

**Comment by Muetze5** [comment]
That would be nice - some slider or an input field for a Integer would be great - currently i'm running 3440x1440
If u need a beta tester just tell me :)

**Comment by C1rdec** [comment]
`1.20.2` should fix the issue with black bars. I will work on supporting the `Centered UI `option.

**Comment by C1rdec** [comment]
I think Centred UI wont be supported sadly... 

Opening the stash tap change the UI and break the Stash Tab grid...

![2023-01-11_22-42-25](https://user-images.githubusercontent.com/5436436/211970660-8b72263b-fe14-4ca6-aa5e-27ba744c6d23.gif)
