### ISSUE TITLE
Show the chaos amount for divine fractions

### ISSUE THREAD

**Issue by Davst** [C1rdec/Poe-Lurker#370]
**Is your feature request related to a problem? Please describe.**
Feature request

**Describe the solution you'd like**
Since fraction divine trades are common. it'd be nice to have a calculated value of chaos that represents the fraction.. so for 2.4 divine it'd be something like 2 divines 102 chaos or such. 

**Describe alternatives you've considered**
none really.. this is just something that'd make life easier, not having to check it in awakened poe trade each time.

**Additional context**

**Comment by C1rdec** [comment]
Already implemented

https://github.com/C1rdec/Poe-Lurker/releases/tag/v1.10.4
