### ISSUE TITLE
Lurker close just after run

### ISSUE THREAD

**Issue by MrOne1676** [C1rdec/Poe-Lurker#377]
When i start Lurker it show in tray, but close after few seconds, try run also as admin but no difference.

What i already try:
- remove appdata local folder and install it again
- instal older version and update by autoupdate

Env:
Win11
2 x 1080p monitors
PoE windowed (with title bar)

[2023/04/08 17:34:32.059] Error [1] „-0,611111111111111” is an invalid value for the property „Height”.
System.ArgumentException: „-0,611111111111111” is an invalid value for the property „Height”.
   w System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   w System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   w Lurker.UI.ViewModels.TradebarViewModel.<>c__DisplayClass49_0.<SetWindowPosition>b__0()
   w Caliburn.Micro.XamlPlatformProvider.OnUIThread(Action action)
   w Lurker.UI.ViewModels.TradebarViewModel.SetWindowPosition(PoeWindowInformation windowInformation)
   w Lurker.UI.ViewModels.PoeOverlayBase.OnViewLoaded(Object view)
   w Caliburn.Micro.XamlPlatformProvider.<>c__DisplayClass11_0.<ExecuteOnFirstLoad>b__0(Object s, RoutedEventArgs e)
   w Caliburn.Micro.View.<>c__DisplayClass8_0.<ExecuteOnLoad>b__0(Object s, RoutedEventArgs e)
   w System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   w System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   w System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   w System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   w System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   w System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   w MS.Internal.LoadedOrUnloadedOperation.DoWork()
   w System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   w System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   w System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   w System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   w System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   w System.Windows.Interop.HwndTarget.OnResize()
   w System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   w System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   w MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   w MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   w System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   w MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam) (Lurker.UI.AppBootstrapper)

**Comment by syc418** [comment]
Same here.

**Comment by dfredlund** [comment]
I have also had the same issue - windowed fullscreen 2560x1440.
For anyone reading this, I have had some success by starting POE Lurker prior to starting POE. Attempting to start Lurker while POE is running causes the instant crash.

**Comment by C1rdec** [comment]
Fixed in 1.21.1
