### ISSUE TITLE
Add option to disable automation

### ISSUE THREAD

**Issue by ghr74** [C1rdec/Poe-Lurker#38]
As previously discussed on discord, the automated kicking after trades breaks GGG's guidelines on one server action per hardware input. 
I would like to request an option to turn this automation off.
Since you've since deleted our conversation and banned me from your discord, I suppose this feature will have to be requested as a github issue. 
Hope it can be addressed swiftly so as to not put any users at risk.

**Comment by C1rdec** [comment]
Regarding your issue we already talked about it. Macro can use chat command without limits. The only things that GGG doesn't want is a timer. Poe Lurker do not violate the guideline.

Example: A timer that would execute `/remaining` and display the remaining monster on the screen. That's a violation.

I will at the option to kick the buyer in setting window.

Stay away of trade manager.
