### ISSUE TITLE
[Request] Dismiss All Current Offers

### ISSUE THREAD

**Issue by rtucker88** [C1rdec/Poe-Lurker#380]
**Is your feature request related to a problem? Please describe.**
If I misprice an item or flip currency, I get bombarded with messages. I currently don't see a way to bulk dismiss. Generally I just close and reopen the program.

**Describe the solution you'd like**
Some hotkey to dismiss all current offers.

**Describe alternatives you've considered**
Closing and reopening the program.

**Additional context**
![image](https://user-images.githubusercontent.com/1187866/231823220-f2e8181b-1902-4094-8c76-85fb7f7373b0.png)

**Comment by C1rdec** [comment]
CTRL + Click the top right Red corner will dismiss all trade offers
