### ISSUE TITLE
"Auto Kick" -  does not work in the Chinese language.

### ISSUE THREAD

**Issue by EeroLai** [C1rdec/Poe-Lurker#382]
Hi, I'm a Taiwanese poe player. I've recently found that using the Chinese patch with this tool causes it to malfunction. I wanted to try to modify the code myself, but I found that the "Event" is in the Lurker.Patreon.dll file. Could you add the Chinese phrase "完成交易。" ("Trade completed.") as a judgment for the "TradeAcceptedEvent" in the code or could you tell me how to modify it myself? 

I am using the [https://poedb.tw/tw/chinese](https://poedb.tw/tw/chinese) Chinese patch.

I'm sorry, my English is not very good.

**Comment by C1rdec** [comment]
Fix in 1.21.5
