### ISSUE TITLE
Auto Kick only for Incoming Trades

### ISSUE THREAD

**Issue by Inch4Tk** [C1rdec/Poe-Lurker#387]
**Is your feature request related to a problem? Please describe.**
Oftentimes for outgoing trades, where I want to buy something in bulk, I whisper multiple people at the same time and then trade with everybody who responds. E.g. the following scenario:
1. Player A invites me. I go to hideout of Player A. 
2. Before Player A is finished trading with me I get a party offer from Player B. 
3. If I accept this party offer before finishing the trade, I will get autokicked from Player B's party as soon as I finish trading with Player A. And then have to PM Player B to reinvite me to actually do the trade.

**Describe the solution you'd like**
Separate the option for enabling Auto-Kick in outgoing and incoming trades. So I can keep Auto-Kick for incoming trades, but disable it for outgoing trades.

As a sidenote there are two other QoL features for outgoing trades I can think of:
1. It would also be nice if the chaos/divine value of outgoing trades is listed next to each outgoing name and not only when selecting/moving to someone's hideout. This way I can easily prepare stacksizes while still in other peoples parties.
2. Make the timeout for auto-removing outgoing trades configurable. Right now I still often get invites from people after the timeout (or have to wait for another trade to finish before accepting party requests).

Anyways, thanks a lot for the work you put into creating an awesome QoL tool!

**Comment by C1rdec** [comment]
The auto-kick only kick you if there's a `trade accepted` message accepting the party invite doesn't trigger the auto-kick.
But I will add a settings to separate the auto-kick options.

**Comment by C1rdec** [comment]
Added in 1.21.10
