### ISSUE TITLE
no way to reconfigure hotkeys under features

### ISSUE THREAD

**Issue by eskoONE** [C1rdec/Poe-Lurker#388]
**Describe the bug**
i accidentally set the hotkey for item highlight to the return key. i cant change it to anything else after settings it once. 

**To Reproduce**
1. Go to features
2. Click on plus sign under item highlight
3. press enter
4. try pressing the area again to set something else
5. nothing happens

**Expected behavior**
i expect to be able to set the hotkey to something else.

**Screenshots**
no need for a screenshot.

**Please complete the following information:**
 - Version 1.21.10
 - Provide Log, no log

**Additional context**
i was able to edit the AppData\Roaming\PoeLurker\HotKeys.json to reset the hotkey.

**Comment by C1rdec** [comment]
There's a red corner in the top right of the hotkey to clear it
