### ISSUE TITLE
"Add Sextant" commit partially works

### ISSUE THREAD

**Issue by joestrach** [C1rdec/Poe-Lurker#390]
**Describe the bug**
Depending on how the direct whisper is created (either from bulk or main trade site) the value for the currency is either "Awakened Sextant" or "awakened-sextant". 

POELurker only correctly parses whispers from the Bulk Trade portion of poe.sale.

**To Reproduce**
1. List a memory for sextants.
2. Go to https://www.pathofexile.com/trade/exchange/Crucible/a05qwyBTe and replace YourAccountName with your account name.
3. Whisper for the item. Valid artwork ✅ 
4. Go to https://www.pathofexile.com/trade/search/Crucible/vYglQOLcE and replace YourAccountName with your account name.
5. Whisper for this item. Invalid artwork ❌ 

**Expected behavior**
Both types of whispers display the sextant artwork.

**Screenshots**
# From Trade
![1683146198-Awakened_PoE_Trade](https://user-images.githubusercontent.com/5495465/236044785-49c106f6-f0e4-4eea-8c41-58237ac47864.png)

# From Bulk Trade
![1683146236-Awakened_PoE_Trade](https://user-images.githubusercontent.com/5495465/236044799-7c973460-2b70-47ab-a409-a0dd2b0793df.png)

**Please complete the following information:**
 - Version 1.21.13
 - Provide Log N/A

**Comment by C1rdec** [comment]
Thanks for letting me know I will fix it 💪

**Comment by joestrach** [comment]
Thanks, I was going to give it a crack myself but I'm a python developer by trade and I had the suspicion that the "Sextent" aliased as "awakened-sextant" would be a bigger undertaking than updating some map somewhere 👍 

Appreciate it! I love this addon.

**Comment by C1rdec** [comment]
Fixed in 1.21.15
