### ISSUE TITLE
Black windows show up repeatedly for several seconds in hideout and in maps

### ISSUE THREAD

**Issue by Thorogrim** [C1rdec/Poe-Lurker#392]
The windows show up when entering a map and as well as after inviting a player to the party. This is particularly annoying, because the windows block vision of the stash when trying to perform a trade. This behavior has not occurred with version 1.21.3.

Version 1.21.5 running PoW stand alone client on Win7x64

![poe-lurker_black-windows](https://github.com/C1rdec/Poe-Lurker/assets/133484864/e9ae572f-5c79-4842-8022-179e021b34d4)

**Comment by C1rdec** [comment]
Win7 is not supported.
This is a configuration on your side that block window transparency.

There is alot of issue with Windows7
