### ISSUE TITLE
Trading Helper Not Working With Hangul or Cyrillic Names

### ISSUE THREAD

**Issue by flanigana** [C1rdec/Poe-Lurker#393]
I've noticed that if I'm attempting to trade someone (incoming or outgoing) with _at least_ a name (or maybe more likely language including) Hangul or Cyrillic that the tool fails to work. I thought this was working a few days ago but hasn't been working at least since the most recent update (1.21.15).

**Comment by C1rdec** [comment]
Those player are using a Poe Client that block the logging into client.txt 

#2
