### ISSUE TITLE
PoE-Lurker sometimes has misaligned UI and sometimes not recognizing Path of Exile at all

### ISSUE THREAD

**Issue by grallbring** [C1rdec/Poe-Lurker#396]
**Describe the bug**
Hello, I've the problem that PoE-Lurker only works very sporadically for me.
I've encountered the following problems:
- Sometimes when starting Path of Exile (I'm using the Steam version), PoE-Lurker simply does nothing as if it wouldn't recognize that Path of Exile has started. No UI loads, no hideout button in the lower left corner is visible and incoming/outgoing trades are not visible as UI buttons.
- Sometimes the UI (hideout button in the lower left corner, incoming/outgoing trade buttons) are shifted upwards by the height of the taskbar.
- Sometimes the previously mentioned problems happen after the application has been working fine for a couple of hours.

**To Reproduce**
Sadly I don't know how I can reproduce the problems. I've not found any trigger for the problems nor can I force them to happen.

**Expected behavior**
The mentioned behaviour shouldn't happen.

**Screenshots**
![image](https://github.com/C1rdec/Poe-Lurker/assets/134601573/dd9b4522-21f8-49d3-8617-237923817055)

**Please complete the following information:**
 - Version 1.21.15

**Additional context**
Running Windows 11, using 2 screens both having a resolution of 2560x1440 if that's relevant.

**Comment by C1rdec** [comment]
I would try to delete your client.txt file.

**Comment by grallbring** [comment]
Quick update, while trying to pinpoint the issue I've encountered a very weird issue.
The `ProcessLurker.GetProcess` function finds a process that doesn't exist:
![image](https://github.com/C1rdec/Poe-Lurker/assets/134601573/c5f689f9-82fe-42f6-a0b8-38b891da8356)
![image](https://github.com/C1rdec/Poe-Lurker/assets/134601573/3766594a-4296-47f0-a787-42d1a807c1fa)

It seems like `Process.GetProcessesByName(text).FirstOrDefault<Process>();` returns a `PathOfExileSteam.exe` process even though Path of Exile isn't running at all.

**Comment by C1rdec** [comment]
Yeah that's weird... But this is an issue with your  machine. I'm pretty sure there's a process running with this ID. The .NET framework is always right :p

**Comment by grallbring** [comment]
> I would try to delete your client.txt file.
> 
> Regarding the misalignment are you using any third party software that makes windowed game full screen?
> 
> Like : https://github.com/Codeusa/Borderless-Gaming

Have deleted the game's log file and from the 10 test starts I did PoE-Lurker always recognized the game, however the UI is misaligned.
The only software I'm using that in any way interacts with the game is PoE-Lurker, Awakened PoE Trade and RivaTunerStatisticsServer. Have also tried running PoE-Lurker without them running and having the same issues.

**Comment by C1rdec** [comment]
Weird I would be very curious if you find the source of the problem. It's something on your computer that's causing the issue otherwise I would have a lot of complaints :p

If you try to set Poe In window mode and reduce the size of the window does Poe Lurker react correctly or you still of the cap?

**Comment by grallbring** [comment]
https://github.com/C1rdec/Poe-Lurker/assets/134601573/70b298c2-33d8-4922-9fd4-7fbd763d5db3

So changing from Borderless to Windowed does not seem to update the UI position by itself but then resizing the window does.

**Comment by C1rdec** [comment]
What's your Windows task bar behaviour? I'm trying to reproduce the issue on my side without success... We need to find what makes the taskbar margin for the overlay.

**Comment by grallbring** [comment]
Taskbar settings:
![image](https://github.com/C1rdec/Poe-Lurker/assets/134601573/a31073a2-c943-44e7-b0fa-49c69516d017)


Windows build version:
![image](https://github.com/C1rdec/Poe-Lurker/assets/134601573/557b37f3-b27c-48fb-a34c-42894467d1d1)
