### ISSUE TITLE
Ability to close all trades

### ISSUE THREAD

**Issue by dmack152** [C1rdec/Poe-Lurker#398]
First off thank you for this. Great tool! 

**Is your feature request related to a problem? Please describe.**

Sometimes trade requests pile up and it would be nice to be able to close all. This could be a button near the health globe or maybe some other short cut. 

**Describe the solution you'd like**

Ability to close all trades quickly.

**Comment by C1rdec** [comment]
Ctrl + click any close button (red corner) will clear the list

**Comment by dmack152** [comment]
Thank you. Also realized you can hotkey dismiss and do it that way. awesome. great work!
