### ISSUE TITLE
APP crashing when trying to enable Pro

### ISSUE THREAD

**Issue by vertex101** [C1rdec/Poe-Lurker#399]
**Describe the bug**

When i try to setup my Pro the app just crashes

**To Reproduce**
1. Go to '...' settings
2. Click on '....' Lurker Pro
3. See error

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Version [e.g. v1.3.0] latest 1.22.0
 - Provide Log (C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs)
 - https://gist.github.com/vertex101/5b2fab0e076944f7017763a6673bdf1a

**Additional context**

**Comment by C1rdec** [comment]
In the log we can see that a file is being used by another process.

**Comment by vertex101** [comment]
i have tried the restart and it didnt work still came up with the same error in the log

i have also tried running the program as admin too

**Comment by C1rdec** [comment]
A program was using the 8080 port
