### ISSUE TITLE
Save moved UI element positions

### ISSUE THREAD

**Issue by PhantomGamers** [C1rdec/Poe-Lurker#405]
**Is your feature request related to a problem? Please describe.**
I have an ultrawide monitor (3440x1440) and POE lurker auto places the trade requests in the incorrect position

![image](https://github.com/C1rdec/Poe-Lurker/assets/844685/10d5c177-cf70-4a61-af7a-7d01052d1c25)

If I move the elements to the desired position by alt dragging them it's fine until I alt tab from the game, then when I alt tab back it resets to the original incorrect position

![image](https://github.com/C1rdec/Poe-Lurker/assets/844685/80e7d88d-7049-456c-8464-7051140a8741)

**Describe the solution you'd like**
I would like the elements to stay where I moved them

**Describe alternatives you've considered**
Improved detection of the default element positions for different aspect ratio displays would be nice as well, but I don't mind just correcting the position manually.

**Comment by Aezriel82** [comment]
same issue as above

only i cant seem to figure out how to even move the elements.. when i press alt+Lclick on one of the lurker elements the game goes from windows mode to FULLSCREEN.? am i missing something> any help appreciated

**Comment by C1rdec** [comment]
I'll add centred UI Support l'll close this issue to centralise everything on #442

**Comment by PhantomGamers** [comment]
> I'll add centred UI Support l'll close this issue to centralise everything on #442

Imo it's still worth having an option to save the moved positions for people who want to place the elements in different places but that fix would be fine for me at least
