### ISSUE TITLE
Close all existing request button

### ISSUE THREAD

**Issue by ericellb** [C1rdec/Poe-Lurker#408]
**Is your feature request related to a problem? Please describe.**
Often a lot of trades are visible due to going afk, not responding etc..

**Describe the solution you'd like**
A clear button, or hotkey support to close ALL existing opened incoming trade icons.

**Comment by C1rdec** [comment]
Ctrl + Click any red button

**Comment by C1rdec** [comment]
Just a friendly tip before opening issues try to search in closed issue first :)

**Comment by C1rdec** [comment]
![image](https://github.com/C1rdec/Poe-Lurker/assets/5436436/4f6e59b5-9eb9-4e11-a5c1-34962f9b84ce)
