### ISSUE TITLE
Add a timer for current trades.

### ISSUE THREAD

**Issue by tamaroth** [C1rdec/Poe-Lurker#41]
Whether a trade is outgoing or incoming, it would be nice to have a timer for that particular trade.

for instance, just above the icon we could have a timer in format MM:SS to indicate how long time ago the message was sent.

This would be useful for cases like leaving the PC with the game open for couple of minutes and coming back seeing 2-3 trade requests. With a timer, it would be a piece of additional information whether we should send a party invite (if it was relatively recently) or perhaps ask whether the buyer is still interested in the offer.

PS: You're doing a great job! I find your tool easy to use to, inobtrusive, and still making my life so much easier without any hassle. Keep up the good work!

**Comment by C1rdec** [comment]
Offer will stack up in order. I already of the date of the Offer i can make a diff I guess. 

I just dont know were to put the information

**Comment by tamaroth** [comment]
Hi, sorry for taking so long to respond.

I was thinking a small timer above the icon would do well as well. But if it's a bit too jarring, it could be placed in the tooltip. 

Placing it in the tooltip would remove the necessity for another thread that would update the timer and would make the implementation much easier.

**Comment by C1rdec** [comment]
Do you want to give it a try?

Every events have a Datetime located in the [base class](https://github.com/C1rdec/Poe-Lurker/blob/05900c05d3f9add75e6b4c1d696a9e64c1cf7e89/src/Lurker/Events/PoeEvent.cs#L43)

You'll need to hook your self OnMouseHover of the Offer button and juste make a diff with DateTime.Now and the actual event time and update the tooltip content.

Here is the [tooltip content](https://github.com/C1rdec/Poe-Lurker/blob/05900c05d3f9add75e6b4c1d696a9e64c1cf7e89/src/Lurker.UI/Views/OfferView.xaml#L262-L264).

**Comment by tamaroth** [comment]
I'll give it a go, not sure if I have the time today, but tomorrow certainly!

**Comment by C1rdec** [comment]
No rush man

**Comment by tamaroth** [comment]
I had a look but I can't figure out where and how the mouse hover event should be hooked (I have never done any real C# development). If you could point me in the right direction, everything else will be done no problem.

**Comment by C1rdec** [comment]
Do you have a branch that I could show you?

**Comment by C1rdec** [comment]
You'll need to use Caliburn Micro Action 

`cal:Message.Attach="[Event MouseEnter] = [Action Talk('Hello', Name.Text)]"`

https://caliburnmicro.com/documentation/actions

**Comment by tamaroth** [comment]
I'll have a look, in the meantime, you can push here: https://github.com/tamaroth/Poe-Lurker/tree/feature-event-timer
