### ISSUE TITLE
Korean Trade Messages Not Caught

### ISSUE THREAD

**Issue by adamrybak** [C1rdec/Poe-Lurker#410]
When receiving messages from Korean players, (Korean letters in their names). The application does not catch the message and no icons appear.

 - Version: 1.23.4
 - Provide Log: I don't have any logs.

**Comment by adamrybak** [comment]
I want to also note, that I am really liking this application.

**Comment by C1rdec** [comment]
https://github.com/C1rdec/Poe-Lurker/issues/249#issuecomment-790251750
