### ISSUE TITLE
black windows popping up

### ISSUE THREAD

**Issue by norecha** [C1rdec/Poe-Lurker#411]
**Describe the bug**
Sometimes when I'm doing inventory dumping, these black windows would show up and they would freeze for some time, then go away on their own. they belong to process "Lurker.UI"

It only happens when im clicking around fast

**Screenshots**
![image](https://github.com/C1rdec/Poe-Lurker/assets/10354246/2cf4f33c-1e34-4691-9cd2-4b15f6f0a548)

**Please complete the following information:**
 - Version 1.23.4

**Comment by C1rdec** [comment]
Make sure to update your graphic driver
