### ISSUE TITLE
Numerous Issues

### ISSUE THREAD

**Issue by hankinsohl** [C1rdec/Poe-Lurker#414]
POE Lurker is fairly nice, but has numerous issues:

* Often, a trade is whispered and POE Lurker fails to display its icon.
* More often still, a trade is completed and the POE Lurker icon remains, instead of recognizing that the trade is complete, that the trader has left the party, and therefore that the icon display should be removed.

What works best is:
* The appeal to give money to the author.  2$ a month?  - Look, if the implementation were flawless, and if the prompt to contribute were less intrusive, I'd probably give a one-time $10 donation.  2$ a month is ridiculous because monthly contributions are forgotten and often continue way past when you've exceeded your intended contribution.

MIssing features or possiblly features that are too complicated to access:
* After a trade is complete, some obvious, configurable way to thank the trader and simultaneously kick him or her from party.

**Comment by C1rdec** [comment]
Thanks for your feedback. 
I think you are missing the settings window... You can configure the auto kick after the trade and the `Thank You` message. 

![image](https://github.com/C1rdec/Poe-Lurker/assets/5436436/2267dfcc-395c-423d-bfca-ff9f1fdd3d82)


I would suggest you to revisit how you give your numerous feedback ;)
