### ISSUE TITLE
Outgoing trade?

### ISSUE THREAD

**Issue by thisisdumbstuff** [C1rdec/Poe-Lurker#418]
I have been paying for pro for years and its made my PoE life much easier so much appreciated. However I have never once been able to get the "outgoing trade" feature to work. I assume it means that when I message to buy something from another player. It would automatically message them the thank you message. Am I wrong in this assumption? What does the outgoing trade feature actually do and how do I make it function?

Thanks

**Comment by C1rdec** [comment]
Basically when you whisper someone to buy an item you can an overlay.

Please check the user guide:

https://docs.google.com/presentation/d/1XhaSSNAFGxzouc5amzAW8c_6ifToNjnsQq5UmNgLXoo/present?slide=id.p

**Comment by thisisdumbstuff** [comment]
So it just resends the message I already sent? Thats it? Can you make it say the thank you message when the trade closes? Like the incoming trades.

**Comment by thisisdumbstuff** [comment]
> So it just resends the message I already sent? Thats it? Can you make it say the thank you message when the trade closes? Like the incoming trades.

Thoughts? Is it possible?

**Comment by thisisdumbstuff** [comment]
?
