### ISSUE TITLE
Item highlight in stash does not work correctly with bulk items

### ISSUE THREAD

**Issue by rezk2ll** [C1rdec/Poe-Lurker#42]
Hello, great tool.

currently, the item highlight in stash does not work with bulk sale items.

for example:

![image](https://user-images.githubusercontent.com/6764881/72211376-a9800900-34ca-11ea-9fc1-b24092887bcc.png)

the item highlight will put 2 shrieking essence of rage in the search bar instead of just "shrieking essence".

so it would be cool if you find a way to remove the amount from the item/currency in the stash highlight functionality.

thanks

**Comment by C1rdec** [comment]
It's an easy fix will be in 1.2.4

**Comment by C1rdec** [comment]
Fixed doing the 1.2.4 build right now
