### ISSUE TITLE
Holding ALT while trade gets accepted messes up resolution

### ISSUE THREAD

**Issue by 0vertime** [C1rdec/Poe-Lurker#424]
Title.

Seems to go fullscreen then back to some default resolution in windowed. Trade whisper enabled but I think its the party kick function somehow.

1.24.0 and before.

**Comment by C1rdec** [comment]
Nothing we can do here other then nothing holding alt Poe Lurker will trigger 'enter' to open the chat

**Comment by 0vertime** [comment]
Solved this by remapping the shortcut in PowerToys keyboard manager.
