### ISSUE TITLE
[Request] Disable Profit Shortcut

### ISSUE THREAD

**Issue by livejamie** [C1rdec/Poe-Lurker#425]
Hello it's annoying for this area of my screen to have an invisible circular overlay that prevents me from clicking any button underneath it.

![image](https://github.com/user-attachments/assets/32c8af3e-52a7-43a7-ae7f-dd980471db03)

I like the feature but I don't like the overlay.

I'd like an option to turn that off.

**Comment by C1rdec** [comment]
I'm not sure that I understand your problem :( where do you try to click?

**Comment by livejamie** [comment]
It's a invisible circular overlay there that brings up the dashboard, is it meant to go over the mana orb?

**Comment by livejamie** [comment]
Here's a recording of it happening:

https://i.imgur.com/wonRiid.gif

It thinks the mana orb should be there, but I'm on a widescreen. It prevents me from interacting with the hideout buttons, or that's where I like to have my Spotify overlay.

**Comment by C1rdec** [comment]
You can already disable the dashboard

![image](https://github.com/user-attachments/assets/a051ab76-9002-44c8-803f-0f9b66a558f9)

**Comment by livejamie** [comment]
Does that disable the dashboard itself or just the orb shortcut? It's unclear.

**Comment by C1rdec** [comment]
Orb shortcut?
