### ISSUE TITLE
[Request] Hideout Invitation Option

### ISSUE THREAD

**Issue by livejamie** [C1rdec/Poe-Lurker#426]
It's possible to trade with players by inviting them to hideout without having to add to your party.

This is convienent for privacy, for trading with people who are already in a party, and for trading when in a full party.

It would be cool if you could enable hideout invitations as the default behavior.

The best option would be if Lurker could be smart enough to recognize you're in a full party and fallback to the Hideout Invitation method but I imagine that would be more difficult to implement.

Thanks!

**Comment by C1rdec** [comment]
Maybe I'm stupid but how can I invite some one to my HO?

**Comment by livejamie** [comment]
![image](https://github.com/user-attachments/assets/e0843389-871b-4e9e-8476-0e4ec6acd607)

**Comment by livejamie** [comment]
![image](https://github.com/user-attachments/assets/6a0141ec-7952-4f2c-bd3d-75916aebbf83)

Here's an example, I'm in a 5 way carry in a full party, I get trade requests but can't invite to party. I _can_ invite to hideout and trade with them though.

It would be cool if Lurker allowed me to do that.
