### ISSUE TITLE
item highlight in stash does not work correctly with gems

### ISSUE THREAD

**Issue by rezk2ll** [C1rdec/Poe-Lurker#43]
hello, 

currently, highlighting gems doesn't work, for example:

![image](https://user-images.githubusercontent.com/6764881/72211751-bf90c800-34d0-11ea-80be-45df1d28b154.png)

it will search for "level 20 0% increased critical strikes support" and it will not highlight anything.

instead, maybe it can search for "increased critical strikes support 20" or "increased critical strikes support 13%" if gem quality is 13. filtering gems maybe is confusing, I think using the stash positions in the trade request maybe can solve this.

sorry for making a separate issue, I was going to add this to the old issue but it's closed now.

thanks

**Comment by C1rdec** [comment]
What's your version ?

**Comment by C1rdec** [comment]
Will look into this today

**Comment by C1rdec** [comment]
Fixed will be in next release 1.2.5
