### ISSUE TITLE
Whispers not being registered as "buy" offers

### ISSUE THREAD

**Issue by RomeoAlphaEkko** [C1rdec/Poe-Lurker#433]
**Describe the bug**

**To Reproduce**
as shown in the screenshot - getting a whisper to buy something

**Expected behavior**
poe lurker registering the whisper and showing the trade icon next to the flasks

**Screenshots**
![image](https://github.com/user-attachments/assets/ceacf4b5-2dd9-4630-b639-2c0854f4e7f3)
None of them (as example) triggered the poe-lurker

**Please complete the following information:**
 - Version 1.24.0
 - Provide Log no file fron the last 2 weeks / 14 days

**Additional context**
not happening every time, but sometimes, might be for non ascii names

**Comment by C1rdec** [comment]
#4
