### ISSUE TITLE
POE Lurker spams open multiple Patreon browser tabs when opened.

### ISSUE THREAD

**Issue by Nethstar** [C1rdec/Poe-Lurker#435]
Bug:
When you open POE Lurker. It spams open at least 3 tabs to a Patreon link that's broken/errored.

Steps to reproduce the behaviour:
1. Download an install POELurker
2. Run POELurker
3. Observe the browser opens up multiple browser tabs forwarding you to patreon

SS of what is shown on the patreon tab.
![2024-12-05 14_54_41-](https://github.com/user-attachments/assets/308d62ac-32cf-4719-bb64-7dedaea042e5)

Ver 2.0.0
Log attached
[log.txt](https://github.com/user-attachments/files/18025127/log.txt)

Extra Notes:
Probably tied to multiple issues with the 2.0.0 release as there are other bugs.

**Comment by C1rdec** [comment]
Can you try to uninstall an reinstall the application

**Comment by Nethstar** [comment]
Uninstalling and Reinstalling with the latest installer gave me the same issue.

Uninstalling, Deleting both POELurker and PatreonLurker folders, and Reinstalling causes POELurker to crash when POE is running.
(Loading it up before POE keeps it running but as soon as POE is running, it crashes)

**Comment by Nethstar** [comment]
Restarted my PC.
Ok, I saw the correct Patreon redirect to share data and accepted. Got the "happy lurking" confirmation.
However, when POE is running it's still just closing/crashing.

Log attached:
[log.txt](https://github.com/user-attachments/files/18025680/log.txt)

Have also tried running PoeLurker in as admin in case of random permission issues.

np problem on testing. Happy to!

**Comment by C1rdec** [comment]
I've deployed 2.0.1 can you try this version ?

**Comment by C1rdec** [comment]
I found the issue 2.0.2 is on the way 🤣

**Comment by Nethstar** [comment]
I'll wait for 2.0.2 then drop in the discord if there's still an error!

**Comment by C1rdec** [comment]
It's released try it out and let me know :)

**Comment by Nethstar** [comment]
Seems to all be good and working. Has not crashed - I'm yet to get a trade request to check that side of things but it's stable! Thanks a lot!
