### ISSUE TITLE
If POELurker has been left open after the POE client is closed, It will not attach to the client again upon reopening

### ISSUE THREAD

**Issue by Nethstar** [C1rdec/Poe-Lurker#436]
**Describe the bug**
If you close and reopen Poe while POELurker is running in the background, Lurker will not recapture the POE window and the functionality stops.

**To Reproduce**
1. Open POE and log in
2. Open POELurker and Confirm Lurker is active (the house icon on bottom left is visible/Initiate a trade)
3. Close and reopen POE
4. Confirm Whether Lurker is active (House icon in bottom left is no longer visible/trade requests no longer show any interaction with Lurker)

**Expected behavior**
As with previous versions, POELurker should capture the POE window if it's reopened again after closing. 

**Please complete the following information:**
 - Ver 2.0.2
No log file appears in the appdata\local\poelurker folder

**Additional context**
Am in the Discord under the same name if you wish to follow up more on this later today and test things further.

**Comment by Nethstar** [comment]
I've joined an instance, even ported in and out of various spaces (Menagerie, Kingsmarch, Hideout, in and out of various maps) and it does not capture POE again.

**Comment by C1rdec** [comment]
Fixed in 2.0.3
