### ISSUE TITLE
Huge Performance drop

### ISSUE THREAD

**Issue by Trad11** [C1rdec/Poe-Lurker#437]
Hey just tried the tool in PoE2 and unfortunately my fps halves when having poelurker running.
Is this a common issue with it not working correctly with PoE2 yet perhaps?

**Comment by C1rdec** [comment]
Lets connect on discord so we can investigate

**Comment by C1rdec** [comment]
Make sure Windows is up to date and you have the latest .NET version.

If you need further assistance Join the [Discord](https://discord.gg/hQERv7K)
