### ISSUE TITLE
poe lurker fails to start on windows

### ISSUE THREAD

**Issue by Xebtria** [C1rdec/Poe-Lurker#439]
**Describe the bug**
every time I start my pc, I get greeted with a dialog to define the program in which to open a dll file. I chose notepad++ for that and it turns out to be the poelurker.dll. As a result, poelurker is not running, I have to manually start it. something must be wrong with autostarting it with windows.

**To Reproduce**
(re-)start windows

**Expected behavior**
poelurker should just startup normally on boot without trying to open its dll for some reason and therefore failing to start

**Screenshots**
n/a

**Please complete the following information:**
 - Version: so far happened with every 2.0.x version up to 2.0.5. haven't tried with 2.0.6 and 2.0.7 yet, as I have just installed them
 - Provide Log (C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs) ► no "app-...." folder exists in that folder for me: 
![grafik](https://github.com/user-attachments/assets/32d7116b-dbf6-4cd5-abce-c1e473e71ec0)

**Additional context**
N/A

**Comment by C1rdec** [comment]
Your installation seems corrupted after the installer migration. Can we connect on discord to investigate.

**Comment by Xebtria** [comment]
I chatted you on discord

**Comment by Xebtria** [comment]
@C1rdec yesterday I had forgotten to set the start with windows part so I hadn't checked it, but today the dll opening thing happened again.

Still no logs folder in localappdata.
