### ISSUE TITLE
Tool doesn't start

### ISSUE THREAD

**Issue by Xebtria** [C1rdec/Poe-Lurker#44]
the tool doesn't start for me. The setup exe does not even run at all, and the zip version, when I start the exe, I see the tool in the systray but as soon as I hover the icon it disappears, as if it gets killed immediately by the antivirus or so, but I also see nothing in the log of the antivirus that it has blocked something or whatever.

**Comment by C1rdec** [comment]
Do you know how to open the windows event viewer !

**Comment by C1rdec** [comment]
Did you check the log if PoeLurker?

**Comment by Xebtria** [comment]
I actually got it working, had to start it as admin.
Since I start my poe itself also as admin, could it be that this does not work then (poe started as admin, lurker started normally?)

and if that is a problem, does the start with windows option then maybe also cause a problem?

**Comment by C1rdec** [comment]
Can you get the log ?

**Comment by C1rdec** [comment]
C:\Users\[user]\AppData\Local\PoeLurker\app-version

**Comment by Xebtria** [comment]
only has one like entry, says "ERROR access denied"

**Comment by C1rdec** [comment]
Version?

**Comment by Xebtria** [comment]
1.2.4

it is weird. I have used the zip dl version now, and I am starting this from this folder:
https://i.imgur.com/hIAGLAt.png

but in the app data there seems to be the exact same files again.
https://i.imgur.com/aJ9AI12.png

only difference is, the one from where I start has also a lurker.pdb, while the appdata one does not have this file.

btw, the log in the location from where I start the tool from also has only one line as well, with the the same exact entry (error: access denied)

**Comment by C1rdec** [comment]
Are you in the discord ?

**Comment by Xebtria** [comment]
no i'm not

**Comment by C1rdec** [comment]
Can you join so I can see what's going on I'm intrigued

Cédric Lampron

________________________________

**Comment by Xebtria** [comment]
I am in now

**Comment by C1rdec** [comment]
Ok I will be home in 30m

**Comment by C1rdec** [comment]
What's your name on discord?

**Comment by C1rdec** [comment]
After investigation we found that POE was running in admin. 
If POE runs in admin PoeLurker needs to have admin rights to get the process.
