### ISSUE TITLE
Can't get my patreon to link to poe lurker for pro features

### ISSUE THREAD

**Issue by Xebtria** [C1rdec/Poe-Lurker#440]
**Describe the bug**
I think I should be a lurker pro, but when I click on "Become a patreon" button, nothing happens. nothing opens in browser whatsoever.
All that happens is that the "save" icon appears on top but that's it.

**To Reproduce**
Click on "Become a patreon" button

**Expected behavior**
I think in the past (pre-poe2) the browser opened and told me some thank you stuff, and then I had the pro features available.

**Screenshots**
step 1: https://i.vgy.me/HSHxBy.png click on button
step 2: https://i.vgy.me/G6QMfD.png notice that nothing happened other than the save icon appearing. 

**Please complete the following information:**
 - Version 2.0.7
 - Provide Log (C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs) ► no "app-...." folder exists in that folder for me: 
![grafik](https://github.com/user-attachments/assets/32d7116b-dbf6-4cd5-abce-c1e473e71ec0)

**Additional context**
N/A

**Comment by C1rdec** [comment]
I will close this issue and combine it with your other one
