### ISSUE TITLE
support for centred UI

### ISSUE THREAD

**Issue by nbusseneau** [C1rdec/Poe-Lurker#442]
Hey, thanks for Poe Lurker!

When playing PoE on wider monitors, enabling the `Interface` > `Centred UI` option helps to keep the UI in view by acting "as if" the screen was 16:9 regardless of its actuel ratio. However this soft conflicts with Poe Lurker, making it spawn its UI in the wrong position relative to the orbs (because they are not located on the window edges anymore). It's perfectly usable still, just not ideal 😅 

![2024-12-17_22-55-46_PathOfExileSteam](https://github.com/user-attachments/assets/e1061ca9-a45c-4fa4-beb7-35b5e79594c5)

Would you consider adding an option for centering Poe Lurker's UI accordingly?

From a technical standpoint, AFAICT the way to do it would be to compute a virtual 16:9 viewport relative to the current window size, and then place the UI based on this viewport rather than the window 🤔 

Cheers 😄

**Comment by HiMarioLopez** [comment]
+1!!!

centered Ui in game + lurker (overlaps health):
![image](https://github.com/user-attachments/assets/9ebf2b31-0413-420b-8d1f-6709b4383117)

**Comment by C1rdec** [comment]
On it :)

**Comment by PhantomGamers** [comment]
It's worth noting that even with that option, the UI will be non-centered in certain cases (e.g. when the skills panel is open or the passive tree window is open)

**Comment by C1rdec** [comment]
Yup and when the stash is open to

**Comment by nbusseneau** [comment]
It's fine IMO, being able to see and interact with the UI without it being layered on top of the globes is worth having extra space on the side for the small amount of time a side panel is open :D

**Comment by C1rdec** [comment]
![2024-12-21_23-15-04](https://github.com/user-attachments/assets/a06cbd81-66c2-4cb8-b27b-7345dce185e9)

**Comment by C1rdec** [comment]
Deployed in 2.1.11

![image](https://github.com/user-attachments/assets/7fa3482c-ba5c-42b5-befc-2021dfb46c5b)

**Comment by nbusseneau** [comment]
Thanks!
