### ISSUE TITLE
New incoming trade are not registered while afk.

### ISSUE THREAD

**Issue by Ninjaskill** [C1rdec/Poe-Lurker#46]
When i'm afking in hideout app doesn't seem to pick up pms when i auto reply afk. When playing the game app seems to work fine.

**Comment by C1rdec** [comment]
Are you sure ? :P

**Comment by Ninjaskill** [comment]
Yeah I just tested with my other account. If i'm in the game playing it works. When I'm afk and tabbed out and tab back to the game no pop up.

**Comment by Ninjaskill** [comment]
When tabbed in back into the game and active and someone PMs me for a trade it works.

**Comment by C1rdec** [comment]
After investigation this was due to #4

**Comment by Ninjaskill** [comment]
Are you saying it's an issue on the Korean client? Because I'm not on a Korean client.

**Comment by C1rdec** [comment]
No you have been whisper why a Korean while afk.

**Comment by Ninjaskill** [comment]
> No you have been whispered by a Korean while afk.

No, because I tested it with my roommate both are using English accounts. Both accounts are English.

**Comment by C1rdec** [comment]
It's working on my side... We can setup a discord screen share so we can investigate

**Comment by C1rdec** [comment]
I found the issue... I will fix it in 1.2.5
