### ISSUE TITLE
Manual Update Check

### ISSUE THREAD

**Issue by Reaver01** [C1rdec/Poe-Lurker#47]
Add manual update check to context menu. Saves having to exit PoE if you know an update is there but Lurker hasn't checked in a while due to not closing/opening the game.

**Comment by C1rdec** [comment]
![image](https://user-images.githubusercontent.com/5436436/72400494-6070c480-3717-11ea-94e8-b8392544b3ac.png)

Thoughts on that?

**Comment by Xebtria** [comment]
https://i.imgur.com/VCaZd8v.png

Installed 1.2.5, then also deleted all the other stuff I had left from the 1.2.4 zip-"install".
I have no update button in the tool

**Comment by C1rdec** [comment]
Its nornal you have the latest version 😉

**Comment by Xebtria** [comment]
🤦‍♂ 😆

**Comment by Reaver01** [comment]
Is it now just checking for update upon opening the settings menu?

**Comment by C1rdec** [comment]
Yes
