### ISSUE TITLE
Tab name instead of item name in tooltip

### ISSUE THREAD

**Issue by Blekota2k** [C1rdec/Poe-Lurker#49]
Hey, wouldnt be better if the tooltip (the one you click on to type item name into filter box) showed tab name instead of item name? I mean ... i dont need to know the name of the item, it will be typed down once i click on that tooltip, but i would like to know in which tab is that item.
Blekota

**Comment by C1rdec** [comment]
Mmmm good idea

**Comment by C1rdec** [comment]
Will be in 1.3.0
