### ISSUE TITLE
Add player name in Offer ToolTip

### ISSUE THREAD

**Issue by domagojmedo** [C1rdec/Poe-Lurker#50]
There is no way to see the name of player that sent you trade request.

**Comment by C1rdec** [comment]
??

When you log issue can you be more precise :)

**Comment by domagojmedo** [comment]
Not sure if I missed it somewhere but on hover you can see the item that the buyer wants but you can't see buyers name.

**Comment by C1rdec** [comment]
I can add that. But why would you need to see the player name? Clicking on the main action will send a trade request to the proper player.

**Comment by domagojmedo** [comment]
True, but I thought it would be nice to have. Sometimes you have mutiple people in HO and if they send you trade request you don't know what each player needs.
