### ISSUE TITLE
Make the Offer tooltip InitialShowDelay configurable

### ISSUE THREAD

**Issue by domagojmedo** [C1rdec/Poe-Lurker#51]
You can't see what item buyer wants unless you hover over box but wait time for hover seems too long. Can you shorten it ?

**Comment by C1rdec** [comment]
You can see the item name if you set the offer to Active (Alt + Click)

**Comment by domagojmedo** [comment]
But then you need to alt click each offer. I really think on hover it should instantly show buyer name + item name + stash location + price

**Comment by C1rdec** [comment]
No this will be annoying. Alt Click is the way to go sorry

**Comment by domagojmedo** [comment]
Can you at least lower the tooltip service InitialShowDelay? Or have it configurable?

**Comment by C1rdec** [comment]
I can make it configurable.
