### ISSUE TITLE
Create a User Guide

### ISSUE THREAD

**Issue by Xebtria** [C1rdec/Poe-Lurker#52]
although using it for over two weeks now I always get confused, which modified does what now, was it shift+click or ctrl+click for the sorry sold, and what again was the "still interested" one.
and what does the left corner button again?

and there is literally nowhere to look this up. the readme.md would be the perfect place for now, although having some help menu on the tool itself wouldn't be too bad either, but that could wait for the future.

**Comment by C1rdec** [comment]
Yes I'm working on a User Guide

**Comment by C1rdec** [comment]
Furthermore, I'll add configuration for action.

**Comment by C1rdec** [comment]
Here is the [User Guide](https://docs.google.com/presentation/d/1XhaSSNAFGxzouc5amzAW8c_6ifToNjnsQq5UmNgLXoo/present)
