### ISSUE TITLE
Improperly typing an item name into search box if it contains a hyphen.

### ISSUE THREAD

**Issue by tamaroth** [C1rdec/Poe-Lurker#54]
If an item that you're selling has a hyphen in its name, like for instance `Two-Stone Ring`, that hyphen is not being inserted into the search box, resulting in not highlighting the item as expected.

Expected:
![screenshot-0026](https://user-images.githubusercontent.com/51408/73141915-75d7de00-4089-11ea-81e3-d74b4f8fb502.png)

Actual:
![screenshot-0025](https://user-images.githubusercontent.com/51408/73141921-7ec8af80-4089-11ea-87a0-2f938d7b2245.png)

**Comment by C1rdec** [comment]
Thanks! I will take a look

**Comment by C1rdec** [comment]
Fixed will be in 1.3.0
