### ISSUE TITLE
Could not create SSL/TLS secure channel on CheckForUpdate

### ISSUE THREAD

**Issue by fatings** [C1rdec/Poe-Lurker#58]
Steps:
1. Started with a fresh install by downloading setup.exe
2. Executed setup.exe
3. Executed Lurker.UI on desktop
4. Tray icon appears for a brief moment and then it's gone

Log: [2020-01-31.log](https://github.com/C1rdec/Poe-Lurker/files/4140891/2020-01-31.log)
Event viewer 1: 
![image](https://user-images.githubusercontent.com/39002567/73566203-34657b00-445b-11ea-8bdf-09ad7452efbf.png)
Event viewer 2:
![image](https://user-images.githubusercontent.com/39002567/73566267-5bbc4800-445b-11ea-8529-57cc37ee52de.png)

**Comment by C1rdec** [comment]
The only thing I can see is the call I made to get all the Affix out of the official TradeAPI

Can you try to open this url in the browser and show me the result :) 

https://www.pathofexile.com/api/trade/data/stats

**Comment by fatings** [comment]
The json seems to load properly in the browser.

[stats.zip](https://github.com/C1rdec/Poe-Lurker/files/4141156/stats.zip)

**Comment by C1rdec** [comment]
OK after further investigation this is due to the "check for update". I will need to connect with you to see how you installed Poe Lurker

**Comment by fatings** [comment]
You can message me on discord @ fatings

**Comment by C1rdec** [comment]
Will do after work :P

**Comment by C1rdec** [comment]
Are you able to run the application?

**Comment by fatings** [comment]
Everything is still the same. I start the application and it closes seconds later.

**Comment by C1rdec** [comment]
What is your time zone so we can setup a call?

**Comment by fatings** [comment]
Western European Standard Time (Lisbon)
Message me on Discord (same name as here, fatings) and we can schedule it.

**Comment by C1rdec** [comment]
I need the number after your name fatings#****

**Comment by C1rdec** [comment]
Will close this issue for now since I'm not able to replicate the issue.
