### ISSUE TITLE
something broke between yesterday and today.

### ISSUE THREAD

**Issue by Xebtria** [C1rdec/Poe-Lurker#62]
**Describe the bug**
https://i.imgur.com/BwtUr8t.jpg 
yesterday it worked fine, today my window for incoming trades is fricking tiny and in the middle of the screen (marked it with the mouse on the screenshot).

**To Reproduce**
start tool, get a trade whisper

**Expected behavior**
have the button be there where it used to be

**Screenshots**
see description

**Please complete the following information:**
 - Version 1.3.1
 - Provide Log [2020-02-05.log](https://github.com/C1rdec/Poe-Lurker/files/4161279/2020-02-05.log)

**Additional context**
can also be simulated by whispering stuff to yourself, I did that at the end of the log file. perfectly reproducible.

**Comment by C1rdec** [comment]
If you set PoE in Window mode and move the window does the trade overlay reposition ?

**Comment by C1rdec** [comment]
Enable debug mode and restart POE

**Comment by Xebtria** [comment]
moved window to second screen in windowed mode, trade overlay button thingy remained on the same position on same monitor

with debug mode it is not there at all anymore

**Comment by C1rdec** [comment]
And if you restart Poe?

**Comment by Xebtria** [comment]
I set it to debug mode and restarted and it is not there anymore. I mean the tool is running but no overlay button at all anymore.

**Comment by C1rdec** [comment]
I pm you on Discord

**Comment by C1rdec** [comment]
I'll close this for now since we dont have enough information
