### ISSUE TITLE
Improvement request: clipboard watcher

### ISSUE THREAD

**Issue by rainfordays** [C1rdec/Poe-Lurker#69]
When copying a whisper message from pathofexile.com/trade have it auto paste the message in game. "TraderForPoe" does this and its by far my favourite feature and what really makes me stay with it.

**Comment by C1rdec** [comment]
Yes that was the next thing I was about to tackle 👊.

So the scenario would be you copy the text out of trade site and you would press the hotkey you had configure in the settings to send it to Poe. Default would be `Ctrl + Shift + V`.

Any thoughts ?

**Comment by C1rdec** [comment]
You can try this out in 1.4.7
