### ISSUE TITLE
Responding to custom messages (Support for community service)

### ISSUE THREAD

**Issue by Quasireal** [C1rdec/Poe-Lurker#70]
Can the program let users to change the message that triggers it ?

This way people providing community service can choose a custom message (like 'craft-service', 'boss-service' etc.) and announce it in their threads to enjoy the organization and quick response capabilities of Poe Lurker.

In my, rather limited, coding knowledge; the idea seemed like a reasonable effort to effectively double PoE Lurker as a "service helper" too. 

(i can see myself running 2 instances, one for community crafting and one for trades) 

Trivialmatters.

**Comment by C1rdec** [comment]
The main action (Click of the button) would always be invite to the party?

**Comment by Quasireal** [comment]
it is reasonable to keep that as invite to party. Response-wise providing services is not much different from trading, you invite ppl or ask for a minute etc. 
The most important thing is being able to backtrack the requests, so as long as there is a box/icon for each request that shows the crafts requested (a textbox like mercury trade will be good, but even mouseover text on the icon will do the trick) it will be  a huge boon

**Comment by C1rdec** [comment]
Will close this issue since this will be done in the chat scanner.

#131
