### ISSUE TITLE
/whois last whisper

### ISSUE THREAD

**Issue by minhpro279** [C1rdec/Poe-Lurker#72]
I would love to be able to check on the buyer/seller to see whether they are mappin, doing lab or just afking in hideout.
To be able to bind it to a hotkey would be nice as well. 
Thanks a lot.

**Comment by C1rdec** [comment]
I'm not sure I'm following you here

**Comment by C1rdec** [comment]
Ohhh the whois chat command

**Comment by C1rdec** [comment]
Do you think that Right Click on the offer is to aggressive?

**Comment by C1rdec** [comment]
Will be in the next release 1.4.11

**Comment by minhpro279** [comment]
> Do you think that Right Click on the offer is to aggressive?

Errr, sorry for the late reply. I kinda forgot about this. 
I think it's alright. IMO being able to do most thing with my mouse is definitely quicker and more convenient than keyboard hotkeys.

**Comment by C1rdec** [comment]
Try it out and give me some feed back 🤗

**Comment by minhpro279** [comment]
> Try it out and give me some feed back 🤗

Howdy, I just tried out the new update after getting back from work. The tool works well as it should. Thanks a lot for the quick update.
