### ISSUE TITLE
Resends outgoing whisper after completed trade.

### ISSUE THREAD

**Issue by p1xel8ted** [C1rdec/Poe-Lurker#73]
**Describe the bug**
I used Awakened PoE Trade and Lurker - sometimes after completing a trade, if I push Ctrl + D on an item to price check and still have the message in my clipboard, it re-sends the "Hi, id like to buy..." message to the previous seller. Issue stops when I close Lurker.

**To Reproduce**
Steps to reproduce the behaviour:
1. Buy something off someone, making sure to use the Lurker functionality
2. Price check an item with Ctrl+D

**Expected behaviour**
Nothing with Lurker

**Screenshots**

**Please complete the following information:**
1.4.9
[2020-03-07.log](https://github.com/C1rdec/Poe-Lurker/files/4303976/2020-03-07.log)
No logs from days where the issue happened

**Additional context**
Perhaps a toggle to turn off outgoing auto-whispers altogether.

**Comment by C1rdec** [comment]
Yeah the problem with Awakened is that the copy the item and replace the cliboard content with the old value... I'll need to add a verification

**Comment by C1rdec** [comment]
Fixed in 1.4.10
