### ISSUE TITLE
Health overlay gets in way of dropdown

### ISSUE THREAD

**Issue by p1xel8ted** [C1rdec/Poe-Lurker#74]
**Describe the bug**
Setting prices on items that are down the bottom of a stash just above the health orb - results in odd behaviour due to the overlay intercepting the clicks. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Put item down the bottom of stash above the orb
2. Attempt to price
3. See error

**Expected behaviour**
Price normally without Lurker interfering

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/10510767/76172491-c2671b00-61ea-11ea-9dca-788ce96d8e19.png)

**Please complete the following information:**
 - Version 1.4.9
[2020-03-09.log](https://github.com/C1rdec/Poe-Lurker/files/4303995/2020-03-09.log)

**Additional context**
Debug on to display issue

**Comment by C1rdec** [comment]
Will be in 1.4.10

![image](https://user-images.githubusercontent.com/5436436/76179251-9c149180-6190-11ea-94bc-3b8652fa45a6.png)

**Comment by p1xel8ted** [comment]
Thank you! Excellent tool :)
