### ISSUE TITLE
Switch through multiple offers to find the items quickly?

### ISSUE THREAD

**Issue by HighOnBuffs** [C1rdec/Poe-Lurker#75]
Not sure if this is possible but id like to somehow (maybe middle click or scroll) through multiple whispers so i can find the items with clicking the lifeglobe to collect all the items in one go (useful for selling maps etc) so i can get them all in my inventory and trade in one go.
Sometimes i invite someone and invite another person and then i dont know how to select the first trade again to help me find the item.
Thanks!

**Comment by C1rdec** [comment]
Alt + click
