### ISSUE TITLE
Auto-close trades if other user is offline [3.10]

### ISSUE THREAD

**Issue by Reaver01** [C1rdec/Poe-Lurker#76]
**Is your feature request related to a problem? Please describe.**
New feature for 3.10: When you attempt to send a message to a player that is not online, the auto-response will now specify which player it is referring to.

**Describe the solution you'd like**
This could be used to auto close outgoing and/or incoming trades if at anytime during the interaction they end up offline and an offline message is received.

**Comment by Reaver01** [comment]
I'll throw a chat log in here once we get into 3.10.

**Comment by C1rdec** [comment]
Any news on that?
I'm not playing alot
