### ISSUE TITLE
Copied outgoing trade message not getting sent to PoE client

### ISSUE THREAD

**Issue by Reaver01** [C1rdec/Poe-Lurker#77]
**Describe the bug**
When lurker is first opened, the first copied trade message does not send to the PoE client

**To Reproduce**
1. Open lurker (If you had it open already, close and reopen)
2. Go to pathofexile.com/trade and click on a trade message
3. Nothing is sent in the client, browser window is scrolled down and sometimes refreshed as enter button is pressed
4. If any subsequent trade messages are clicked they will get sent, but the first one isn't.

**Expected behavior**
Trade message is sent to the PoE client

**Please complete the following information:**
 - Version 1.4.X
 - Provide Log (C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs)
No logs generated

**Comment by Reaver01** [comment]
![image](https://user-images.githubusercontent.com/1864450/76381203-66031900-631a-11ea-9126-161552556045.png)

**Comment by Reaver01** [comment]
![2A9uP2FW26](https://user-images.githubusercontent.com/1864450/76381257-89c65f00-631a-11ea-808d-10d5896ab5a1.gif)

**Comment by p1xel8ted** [comment]
Can confirm - the same issue here.

**Comment by C1rdec** [comment]
I'll take a look after work

**Comment by C1rdec** [comment]
Fixed in 1.4.12

**Comment by C1rdec** [comment]
@Reaver01 @p1xel8ted 
Can you guys confirm that 1.4.12 fix the issue?

**Comment by Reaver01** [comment]
Works for me!
