### ISSUE TITLE
Multiple Open Accounts

### ISSUE THREAD

**Issue by synicasm** [C1rdec/Poe-Lurker#78]
It appears that this only works on 1 of the 2 POE sessions that are open if you happen to have 2 open.

FYI I was testing how it works and came across this.

**Comment by C1rdec** [comment]
Multiple accounts are not supported right now

**Comment by C1rdec** [comment]
Is there really a need for that ?

**Comment by C1rdec** [comment]
Sorry I missclicked the close and comment...

**Comment by C1rdec** [comment]
Not supported
