### ISSUE TITLE
Program is blocking mouse macros?

### ISSUE THREAD

**Issue by SiderealDay** [C1rdec/Poe-Lurker#79]
It seems Lurker is blocking my Logitech mouse button 4 and 5 macro.
Terminating Lurker solves the problem.
My MB4 clicks "e", while MB5 clicks "1", which Lurker should not interfer with.

Using v1.4.12 on Standard league.
Windows10 x64, Logitech G502 Proteus mouse.

**Comment by C1rdec** [comment]
Can we connect on discord I think I found the culprit but I want to confirm.

**Comment by SiderealDay** [comment]
Sure. Do you have a discord for your program or your own?

**Comment by C1rdec** [comment]
Let me know if 1.4.13 fix this issue.

**Comment by C1rdec** [comment]
Adding poelurker.exe to [Logitech Gaming Software](https://support.logi.com/hc/en-001/articles/360025298053-Logitech-Gaming-Software) (LGD) for the profile related to Path of Exile fixes the macro problem.
