### ISSUE TITLE
Crashes immediately after being opened

### ISSUE THREAD

**Issue by H4xoltl** [C1rdec/Poe-Lurker#80]
Basically I try to open the PoeLurker.exe

It launches in the system tray for 2 seconds, then closes itself. Same happens after an reinstallation and running the app as administrator 

 Nothing ever appears in the actual PoE game.

**Comment by C1rdec** [comment]
I will need to the log...

**Please complete the following information:**
 - Version [e.g. v1.3.0]
 - Provide Log (C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs)

**Comment by H4xoltl** [comment]
Version: v1.4.12
[2020-03-14.log](https://github.com/C1rdec/Poe-Lurker/files/4331857/2020-03-14.log)

**Comment by C1rdec** [comment]
This is an Admin issue

**Comment by H4xoltl** [comment]
I'm running poe lurker as an administrator

**Comment by C1rdec** [comment]
Can we connect on discord?

**Comment by Tripwyr** [comment]
Not sure if related, but PoE Lurker was detected and quarantined by my antivirus. I am using BitDefender, but it is likely detected by others.

**Comment by C1rdec** [comment]
@Tripwyr I need to buy a certificate to sign the installer that's why antivirus flag Poe Lurker

https://docs.microsoft.com/en-us/windows/win32/seccrypto/cryptography-tools

**Comment by C1rdec** [comment]
@H4xoltl are you still experiencing this issue?

**Comment by kempol181** [comment]
Hi, I have the same problem. Lurker just closes itself

**Comment by Seta19** [comment]
I've also had the same issue, I tried running as administrator, didn't work. 
[2020-03-15.log](https://github.com/C1rdec/Poe-Lurker/files/4337573/2020-03-15.log)

**Comment by C1rdec** [comment]
I will need to connect whit one of you guys for a debug session.

**Comment by barnowan** [comment]
Same issue here.  Running as Admin.

[2020/03/16 10:04:22.872] Error [1] Access is denied
System.ComponentModel.Win32Exception (0x80004005): Access is denied

What other information do you need?  How would you like to debug?

**Comment by C1rdec** [comment]
I would like to connect on [discord](https://discordapp.com/invite/pPxsvdX) to setup a screen share.

**Comment by barnowan** [comment]
I'm in the Debugging channel if you're free.

**Comment by C1rdec** [comment]
I just connect with @barnowan and we fix his issue.
Everything is pointing on an admin issue for all of you let me know when you guys are free to test this out.

**Comment by C1rdec** [comment]
To run Poe Lurker as Admin you need to: 
`Right Click` the Desktop Shortcut (`Lurker.UI`) and check the run as Admin in the `Compatibility` Tab

If you dont have any shortcut you can navigate to the `PoeLurker.exe` located in :
`C:\Users\[user]\AppData\Local\PoeLurker`

![image](https://user-images.githubusercontent.com/5436436/76795351-557df300-679f-11ea-8d46-29d47005f05c.png)

**Comment by Seta19** [comment]
I figured it out, i was running the original .exe and not from the actual folder. It works now.

**Comment by C1rdec** [comment]
I will close this issue for now.

**Comment by kempol181** [comment]
> 
> 
> I figured it out, i was running the original .exe and not from the actual folder. It works now.

lol so thats why
