### ISSUE TITLE
Incoming trade popup no longer close

### ISSUE THREAD

**Issue by Chocapic** [C1rdec/Poe-Lurker#84]
v1.4.17 when I click to send the trade invite. once the trade is done and the "Thank you" message is sent, the main button is still there and I have to manually clsoe it everytime

**Comment by C1rdec** [comment]
On it

**Comment by Chocapic** [comment]
Nevermind found the issue. I had the process running twice in the tasmanager. Killed both, restarted and it was working fine. Maybe prevent poelurker to start if its already running ?

Cheers

**Comment by C1rdec** [comment]
Yeah good idea
