### ISSUE TITLE
Make "clicking the mana globe to open settings" optional

### ISSUE THREAD

**Issue by omriharel** [C1rdec/Poe-Lurker#85]
**Is your feature request related to a problem? Please describe.**
It can be very frustrating when misclicking it in the middle of hectic fight causes a pop-up followed by a character death.

**Describe the solution you'd like**
Please add a toggle in the settings for the mana globe being unclickable.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by C1rdec** [comment]
I'll make that the mana will be clickable only in the hideout

**Comment by omriharel** [comment]
That's fantastic, thanks!

**Comment by C1rdec** [comment]
Try it out in 1.4.19

**Comment by omriharel** [comment]
Works great, thank you!
