### ISSUE TITLE
remove mana orb settings

### ISSUE THREAD

**Issue by rainfordays** [C1rdec/Poe-Lurker#88]
Since we're not accessing settings several times per hour it's really more of a disturbance than it is a convenience to have the mana orb be tied to opening the settings window. Right clicking the icon for settings is already a clear and intuitive way of getting to the options menu.

**Comment by DSCriErr** [comment]
Agree, there absolutely no reason for such a thing.

**Comment by C1rdec** [comment]
Agreed I'm the culprit here... Since i'm developing the tool this was a QoL for me :stuck_out_tongue_winking_eye:. I will remove it in the next release

**Comment by C1rdec** [comment]
Removed in 1.4.23
