### ISSUE TITLE
Item already sold, duplicate buy request

### ISSUE THREAD

**Issue by DSCriErr** [C1rdec/Poe-Lurker#89]
Store some last buy offers, add some icon over duplicate and another one if I actually clicked accept trade and dude got kicked from the party - item is sold.

Do something like that for an outgoing buy request as well.

**Comment by C1rdec** [comment]
I like the idea. I will store the last 5 sold items. But regarding outgoing trade I'm not sure those rules applies.

**Comment by C1rdec** [comment]
in 1.4.23

**Comment by Skrity** [comment]
It kinda backfired because now when I sell same maps in bulk I can't use it after the first trade. Maybe make an alternative action (e.g. ctrl+click) to actually proceed to trade

**Comment by C1rdec** [comment]
Mmn

**Comment by C1rdec** [comment]
@Skrity I made that `Map `and `Currency `will never be flagged as sold.
