### ISSUE TITLE
Changing the incoming trade icon

### ISSUE THREAD

**Issue by LeithBA** [C1rdec/Poe-Lurker#93]
Would it be possible to give the user to change the icons for incoming trades to the icon of the item that will be traded instead of the currency? 

It would make it easier to respond to trade request for items that have already been sold. Currently the user has to hover on top of each request and wait until the small pop up appears.

**Comment by C1rdec** [comment]
No. Sold Item will have it's own button. This is available in 1.4.23.
https://github.com/C1rdec/Poe-Lurker/releases/tag/v1.4.23
