### ISSUE TITLE
Setup crashes everytime

### ISSUE THREAD

**Issue by fjndeleeuw** [C1rdec/Poe-Lurker#94]
The current verion 1.5.2 starts normally when PoE is not started, but then crashes at PoE startup. I tried starting Lurker when PoE already is started but still crashes immediately. (With or without admin)

I tried older versions like 1.2.2 and 1.2.4 and those i can use when installing with the files in the zip. And starting the exe with administrator rights. But when i use de setup.exe instead it once again crashes immediately.

I have:
.net framework 4.8.03752
Windows 10 Pro 1909 build 29363.720 64 bit
Intel Core i5-6500 3.20GHz
PoE version 3.10.0f (Only tested in delirium)

**Comment by C1rdec** [comment]
#80

**Comment by C1rdec** [comment]
Please complete the following information:
• Version [e.g. v1.3.0]
• Provide Log (C:\Users[user]\AppData\Local\PoeLurker\app-[version]\logs)

**Comment by fjndeleeuw** [comment]
Thanks for your quick reply!! Yes it worked. I didn't know the files where being installed in a different location from the setup.exe (because it also starts the program). 

Just a suggestion:
It could be a good idea to visually show the location of the new files or the installation itself. Or not also start the program when launching the setup. Or let us choose the location of the installation.

Please considering adding this to your release page. Btw, love your app. Its the best out there!!
 
Setup:
1. Start setup.exe
2. Go to %userprofile%\AppData\Local\PoeLurker
3. Go to properties in the PoeLurker.exe
4. Set administrator rights in comparability

**Comment by C1rdec** [comment]
Thanks man! I will nake an FAQ in the readme

**Comment by C1rdec** [comment]
I think the best scenario would be to detect that POE is elevated(admin) and warn the user with the steps you just gave me
