### ISSUE TITLE
Item highlight field is not losing focus after search

### ISSUE THREAD

**Issue by Deop** [C1rdec/Poe-Lurker#95]
**Describe the bug**
When using item highlight action after item name was typed into the highlight field it's still have the focus, so if you move item from the stash with ctrl+click and then use main action to send trade request chat opens instead.

**To Reproduce**
1. Receive buy request
2. Open stash
3. Click item highlight action (over the health bar)
4. Ctrl+click highlighted item to move it to your inventory
5. Click main action to send trade request

**Expected behavior**
Trade request is sent

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/7953144/77791051-9e228f80-706e-11ea-8677-ba50575e609b.png)

**Please complete the following information:**
 - Version 1.5.3
 - Provide Log (C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs)

**Additional context**
I believe this commit broke it https://github.com/C1rdec/Poe-Lurker/commit/0d0e15141189ae170580d71f2a801ace42f856d4 specifically removal of Return key press

**Comment by C1rdec** [comment]
Yeah I'll take a look. I removed the return since some users was experiencing a delay for the key press.

**Comment by C1rdec** [comment]
Fixed in 1.5.4
