### ISSUE TITLE
Cannot Highlight Skill Gems or Flasks using Ctrl-F

### ISSUE THREAD

**Issue by jaycsin** [C1rdec/Poe-Lurker#96]
When you press control-f when hovering over a skill gem/flask you would expect to get the text box and the approiate item become highlighted.  Instead it just leaves a blinking cursor in the highlight box and nothing highlighted.  There may be other items that don't work, but only found these two.

Side note: I also use PoE overlay, they have a similar feature, it uses alt-f.  They have skill gems and flasks working, but if both programs are running together neither program's highlight feature works for skill gems or flasks.  If I turn off Poe-Lurker or disable it in the settings, the PoE Overlay feature works again.

**Comment by C1rdec** [comment]
Yes some work need to be done there

**Comment by C1rdec** [comment]
Try it out in 1.5.5.
