### ISSUE TITLE
Customize the appearance and position of incoming trades

### ISSUE THREAD

**Issue by DSCriErr** [C1rdec/Poe-Lurker#97]
Hello.
Requesting more settings.
Add please settings to 
- offset incoming trade bar position with an anchor from bottom left
- custom scale for high and width of incoming trade boxes
- settings for actions on bar being left and right half of the box instead of the top left and top right.

Thanks.

**Comment by C1rdec** [comment]
I'm already working on a scaling feature. I like the offset idea but regarding the option to move the button sub actions I'm not sure that I want to support that.

**Comment by DSCriErr** [comment]
Yea, I forgot that the click on the button is also an action itself.
What about over the icon and lower of it?
Right now, pixel hunt is super stressful in maps.

**Comment by C1rdec** [comment]
Scaling will fix this issue

**Comment by DSCriErr** [comment]
We shall see, but it is not that EZ for me for sure, league to frantic on hc.
Maybe you can hook into alt key as mod for left and right mouse click?

**Comment by C1rdec** [comment]
`Alt+Click` is already in use. I'll close this issue since it is to broad.
Scaling is on the road map.
