### ISSUE TITLE
Treat Oils as Currency

### ISSUE THREAD

**Issue by RuriRyan** [C1rdec/Poe-Lurker#98]
Selling stacks of blight oils is literally impossible, as after the first trade the item is marked as sold. The only solution i've found is to restart poe-lurker.

Also people us the item search, instead of the currency search on the trade side, maybe this is related to the parser in not recognizing the oils.

**Comment by C1rdec** [comment]
I'm on it

**Comment by C1rdec** [comment]
Try it out in 1.5.6.
