### ISSUE TITLE
Green placeholders instead of transparency

### ISSUE THREAD

**Issue by galik79** [C1rdec/Poe-Lurker#99]
After lunching POE i get green placeholders in places where POE Lurker buttons should be. They stay visible all the time.
Tried reinstalling, updating no effect.

![blad](https://user-images.githubusercontent.com/62701579/77847690-53645d00-71bf-11ea-98b2-158079ebbb34.png)

**Comment by RuriRyan** [comment]
It looks like you have "Debug Mode" enabled. Open the Settings -> Advanced and switch Debug Mode to Off.

**Comment by galik79** [comment]
Yep. thank you, i feel so stupid right now.
